/**
 * Pulsar — Built-in Music Catalog
 * Static fallback so the site always shows music, even with no
 * database configured. Supabase releases (when available) are
 * shown alongside / on top of this catalog.
 *
 * Collections: Rolling Stone Top 500 · Stoner/Psych/Doom classics ·
 * Grammy winners (recent years, major categories)
 */

import type { Release } from "./types";

const sp = (q: string) =>
  `https://open.spotify.com/search/${encodeURIComponent(q)}`;
const am = (q: string) =>
  `https://music.apple.com/search?term=${encodeURIComponent(q)}`;
const td = (q: string) =>
  `https://tidal.com/search?q=${encodeURIComponent(q)}`;
const sc = (q: string) =>
  `https://soundcloud.com/search?q=${encodeURIComponent(q)}`;
const yt = (q: string) =>
  `https://music.youtube.com/search?q=${encodeURIComponent(q)}`;

function links(artist: string, title: string) {
  const q = `${artist} ${title}`;
  return { spotify: sp(q), apple_music: am(q), tidal: td(q), soundcloud: sc(q), youtube_music: yt(q) };
}

const wiki = (path: string) =>
  `https://upload.wikimedia.org/wikipedia/en/${path}`;

// ─────────────────────────────────────────────
// Seed data
// ─────────────────────────────────────────────

const RELEASES = [

  // ════════════════════════════════════════════
  // ROLLING STONE TOP 500 ALBUMS OF ALL TIME
  // ════════════════════════════════════════════

  {
    artist: "The Beatles",
    title: "Sgt. Pepper's Lonely Hearts Club Band",
    type: "album" as const,
    artwork_url: wiki("5/50/Sgt._Pepper%27s_Lonely_Hearts_Club_Band.jpg"),
    release_date: "1967-06-01",
    genre: "Psychedelic Pop / Rock",
    tags: ["psychedelic", "pop", "classic-rock", "british-invasion"],
    mood: "euphoric" as const,
    ...links("The Beatles", "Sgt. Pepper's Lonely Hearts Club Band"),
    curator_note: "The record that made the album an art form — and then dared to be silly about it.",
  },
  {
    artist: "The Beach Boys",
    title: "Pet Sounds",
    type: "album" as const,
    artwork_url: wiki("b/bb/PetSoundsCover.jpg"),
    release_date: "1966-05-16",
    genre: "Baroque Pop / Psychedelic",
    tags: ["baroque-pop", "psychedelic", "orchestral", "classic"],
    mood: "melancholic" as const,
    ...links("The Beach Boys", "Pet Sounds"),
    curator_note: "Wilson heard the ocean and built a cathedral from it.",
  },
  {
    artist: "The Beatles",
    title: "Revolver",
    type: "album" as const,
    artwork_url: wiki("6/6b/Revolver_cover_The_Beatles.jpg"),
    release_date: "1966-08-05",
    genre: "Psychedelic Rock / Pop",
    tags: ["psychedelic", "rock", "pop", "classic"],
    mood: "hypnotic" as const,
    ...links("The Beatles", "Revolver"),
    curator_note: "The Beatles deciding that songs were a place where physics didn't have to apply.",
  },
  {
    artist: "Marvin Gaye",
    title: "What's Going On",
    type: "album" as const,
    artwork_url: wiki("0/03/Marvin_Gaye_-_What%27s_Going_On.jpg"),
    release_date: "1971-05-21",
    genre: "Soul / R&B",
    tags: ["soul", "r&b", "funk", "protest", "classic"],
    mood: "melancholic" as const,
    ...links("Marvin Gaye", "What's Going On"),
    curator_note: "Asked the hardest question and answered it with the most beautiful sound imaginable.",
  },
  {
    artist: "The Rolling Stones",
    title: "Exile on Main St.",
    type: "album" as const,
    artwork_url: wiki("9/9c/ExileonMainSt.jpg"),
    release_date: "1972-05-12",
    genre: "Rock / Blues",
    tags: ["rock", "blues", "country", "soul", "classic"],
    mood: "raw" as const,
    ...links("The Rolling Stones", "Exile on Main St."),
    curator_note: "Recorded in a basement in southern France. Sounds like it.",
  },
  {
    artist: "The Clash",
    title: "London Calling",
    type: "album" as const,
    artwork_url: wiki("0/02/LondonCallingalbum.jpg"),
    release_date: "1979-12-14",
    genre: "Punk / Rock / Reggae",
    tags: ["punk", "rock", "reggae", "ska", "classic"],
    mood: "energetic" as const,
    ...links("The Clash", "London Calling"),
    curator_note: "The end of punk was the beginning of everything — all on one double album.",
  },
  {
    artist: "Bob Dylan",
    title: "Blonde on Blonde",
    type: "album" as const,
    artwork_url: wiki("3/38/Bob_Dylan_-_Blonde_on_Blonde.jpg"),
    release_date: "1966-05-16",
    genre: "Folk Rock / Psychedelic",
    tags: ["folk", "rock", "psychedelic", "classic", "dylan"],
    mood: "hypnotic" as const,
    ...links("Bob Dylan", "Blonde on Blonde"),
    curator_note: "Six sides of surrealist American poetry that nobody has topped in sixty years.",
  },
  {
    artist: "Bob Dylan",
    title: "Highway 61 Revisited",
    type: "album" as const,
    artwork_url: wiki("c/c9/Highway61.jpg"),
    release_date: "1965-08-30",
    genre: "Folk Rock / Blues",
    tags: ["folk", "rock", "blues", "electric", "classic"],
    mood: "raw" as const,
    ...links("Bob Dylan", "Highway 61 Revisited"),
    curator_note: "The moment Dylan went electric — and the whole crowd booed the future.",
  },
  {
    artist: "Stevie Wonder",
    title: "Songs in the Key of Life",
    type: "album" as const,
    artwork_url: wiki("9/9c/Stevie_Wonder_-_Songs_in_the_Key_of_Life.jpg"),
    release_date: "1976-09-28",
    genre: "Soul / Funk / R&B",
    tags: ["soul", "funk", "r&b", "jazz", "classic"],
    mood: "euphoric" as const,
    ...links("Stevie Wonder", "Songs in the Key of Life"),
    curator_note: "Wonder playing every instrument, writing every lyric, feeling everything at once.",
  },
  {
    artist: "Stevie Wonder",
    title: "Innervisions",
    type: "album" as const,
    artwork_url: wiki("8/8b/Innervisions_-_Stevie_Wonder.jpg"),
    release_date: "1973-08-03",
    genre: "Soul / Funk",
    tags: ["soul", "funk", "r&b", "classic", "wonder"],
    mood: "cinematic" as const,
    ...links("Stevie Wonder", "Innervisions"),
    curator_note: "Stevie having a conversation with America that America wasn't ready to hear.",
  },
  {
    artist: "Pink Floyd",
    title: "The Dark Side of the Moon",
    type: "album" as const,
    artwork_url: wiki("3/3b/Dark_Side_of_the_Moon.png"),
    release_date: "1973-03-01",
    genre: "Progressive Rock / Psychedelic",
    tags: ["progressive", "psychedelic", "rock", "ambient", "classic"],
    mood: "cinematic" as const,
    ...links("Pink Floyd", "The Dark Side of the Moon"),
    curator_note: "Light hits a prism. Everything you think you know scatters into something larger.",
  },
  {
    artist: "Fleetwood Mac",
    title: "Rumours",
    type: "album" as const,
    artwork_url: wiki("e/eb/Fleetwood_Mac_-_Rumours.jpg"),
    release_date: "1977-02-04",
    genre: "Soft Rock / Pop Rock",
    tags: ["soft-rock", "pop", "california", "classic"],
    mood: "melancholic" as const,
    ...links("Fleetwood Mac", "Rumours"),
    curator_note: "Five people in the middle of four collapsing relationships made the perfect record.",
  },
  {
    artist: "The Beatles",
    title: "Abbey Road",
    type: "album" as const,
    artwork_url: wiki("4/42/Beatles_-_Abbey_Road.jpg"),
    release_date: "1969-09-26",
    genre: "Rock / Pop",
    tags: ["rock", "pop", "classic", "beatles"],
    mood: "euphoric" as const,
    ...links("The Beatles", "Abbey Road"),
    curator_note: "The last thing they built together — and they built it like they knew.",
  },
  {
    artist: "Joni Mitchell",
    title: "Blue",
    type: "album" as const,
    artwork_url: wiki("a/a9/Joni_Mitchell_-_Blue.jpg"),
    release_date: "1971-06-22",
    genre: "Folk / Singer-Songwriter",
    tags: ["folk", "singer-songwriter", "confessional", "classic"],
    mood: "melancholic" as const,
    ...links("Joni Mitchell", "Blue"),
    curator_note: "So naked it still feels intrusive to listen. The most intimate record ever made.",
  },
  {
    artist: "Carole King",
    title: "Tapestry",
    type: "album" as const,
    artwork_url: wiki("f/fb/Tapestry_%28carole_king_album%29.jpg"),
    release_date: "1971-02-10",
    genre: "Singer-Songwriter / Soft Rock",
    tags: ["singer-songwriter", "soft-rock", "pop", "classic"],
    mood: "tender" as const,
    ...links("Carole King", "Tapestry"),
    curator_note: "She wrote half the songs you already knew — and saved the best for herself.",
  },
  {
    artist: "Bruce Springsteen",
    title: "Born to Run",
    type: "album" as const,
    artwork_url: wiki("7/7a/Born_to_Run_%28Front_Cover%29.jpg"),
    release_date: "1975-08-25",
    genre: "Rock",
    tags: ["rock", "americana", "heartland", "classic"],
    mood: "energetic" as const,
    ...links("Bruce Springsteen", "Born to Run"),
    curator_note: "A guy from New Jersey writing the great American escape fantasy. And pulling it off.",
  },
  {
    artist: "Miles Davis",
    title: "Kind of Blue",
    type: "album" as const,
    artwork_url: wiki("9/9c/MilesDavisKindofBlue.jpg"),
    release_date: "1959-08-17",
    genre: "Jazz / Modal Jazz",
    tags: ["jazz", "modal", "blue-note", "classic", "instrumental"],
    mood: "ambient" as const,
    ...links("Miles Davis", "Kind of Blue"),
    curator_note: "Modal jazz invented in a single session. The calm at the center of everything loud.",
  },
  {
    artist: "Jimi Hendrix Experience",
    title: "Are You Experienced",
    type: "album" as const,
    artwork_url: wiki("3/33/Are_You_Experienced_-_US_cover-edit.jpg"),
    release_date: "1967-05-12",
    genre: "Psychedelic Rock / Blues",
    tags: ["psychedelic", "blues", "rock", "electric-guitar", "classic"],
    mood: "energetic" as const,
    ...links("Jimi Hendrix", "Are You Experienced"),
    curator_note: "The guitar had a new owner. Nobody told the guitar, so it sounded shocked too.",
  },
  {
    artist: "Nirvana",
    title: "Nevermind",
    type: "album" as const,
    artwork_url: wiki("b/b7/NirvanaNevermindalbumcover.jpg"),
    release_date: "1991-09-24",
    genre: "Grunge / Alternative Rock",
    tags: ["grunge", "alternative", "rock", "90s"],
    mood: "raw" as const,
    ...links("Nirvana", "Nevermind"),
    curator_note: "A baby reaching for a dollar. America's id, perfectly compressed into 45 minutes.",
  },
  {
    artist: "Radiohead",
    title: "OK Computer",
    type: "album" as const,
    artwork_url: wiki("b/ba/Radioheadokcomputer.png"),
    release_date: "1997-05-21",
    genre: "Alternative Rock / Art Rock",
    tags: ["alternative", "art-rock", "electronic", "dystopian", "90s"],
    mood: "cinematic" as const,
    ...links("Radiohead", "OK Computer"),
    curator_note: "1997 predicting 2007 predicting now. Still the only anxiety album that actually helps.",
  },
  {
    artist: "Nas",
    title: "Illmatic",
    type: "album" as const,
    artwork_url: wiki("9/93/Nas_Illmatic.jpg"),
    release_date: "1994-04-19",
    genre: "Hip-Hop / East Coast Rap",
    tags: ["hip-hop", "rap", "east-coast", "nyc", "90s"],
    mood: "cinematic" as const,
    ...links("Nas", "Illmatic"),
    curator_note: "Ten tracks, thirty-nine minutes — and nobody has written a better New York rap album.",
  },
  {
    artist: "Kendrick Lamar",
    title: "To Pimp a Butterfly",
    type: "album" as const,
    artwork_url: wiki("f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png"),
    release_date: "2015-03-15",
    genre: "Hip-Hop / Jazz Rap / Funk",
    tags: ["hip-hop", "jazz-rap", "funk", "soul", "political"],
    mood: "cinematic" as const,
    ...links("Kendrick Lamar", "To Pimp a Butterfly"),
    curator_note: "A conversation with Tupac's ghost. He had something to say about all of us.",
  },
  {
    artist: "Kanye West",
    title: "My Beautiful Dark Twisted Fantasy",
    type: "album" as const,
    artwork_url: wiki("f/f0/My_Beautiful_Dark_Twisted_Fantasy.jpg"),
    release_date: "2010-11-22",
    genre: "Hip-Hop / Art Rap",
    tags: ["hip-hop", "art-rap", "maximalist", "2010s"],
    mood: "cinematic" as const,
    ...links("Kanye West", "My Beautiful Dark Twisted Fantasy"),
    curator_note: "A man building a monument to his own contradictions — and making it sound transcendent.",
  },
  {
    artist: "Prince",
    title: "Purple Rain",
    type: "album" as const,
    artwork_url: wiki("9/98/PurpleRainSoundtrack.jpg"),
    release_date: "1984-06-25",
    genre: "Funk / Rock / R&B",
    tags: ["funk", "rock", "r&b", "pop", "80s"],
    mood: "euphoric" as const,
    ...links("Prince", "Purple Rain"),
    curator_note: "The guitar solo at the end of the title track is seven minutes long and it still ends too soon.",
  },
  {
    artist: "Michael Jackson",
    title: "Thriller",
    type: "album" as const,
    artwork_url: wiki("5/55/Michael_Jackson_-_Thriller.png"),
    release_date: "1982-11-30",
    genre: "Pop / Funk / R&B",
    tags: ["pop", "funk", "r&b", "80s", "classic"],
    mood: "euphoric" as const,
    ...links("Michael Jackson", "Thriller"),
    curator_note: "Best-selling record of all time. No adjective left to add. It just is.",
  },
  {
    artist: "The Velvet Underground",
    title: "The Velvet Underground & Nico",
    type: "album" as const,
    artwork_url: wiki("0/0c/Velvet_Underground_and_Nico.jpg"),
    release_date: "1967-03-12",
    genre: "Avant-Garde / Art Rock",
    tags: ["avant-garde", "art-rock", "experimental", "proto-punk"],
    mood: "hypnotic" as const,
    ...links("The Velvet Underground", "The Velvet Underground & Nico"),
    curator_note: "Only 30,000 people bought it. Every one of them started a band.",
  },
  {
    artist: "Talking Heads",
    title: "Remain in Light",
    type: "album" as const,
    artwork_url: wiki("3/36/Remain_in_Light.jpg"),
    release_date: "1980-10-08",
    genre: "New Wave / Art Rock / African",
    tags: ["new-wave", "art-rock", "funk", "afrobeat", "80s"],
    mood: "energetic" as const,
    ...links("Talking Heads", "Remain in Light"),
    curator_note: "Byrne studied Fela Kuti and had a breakdown and made the greatest dance record of the 80s.",
  },
  {
    artist: "My Bloody Valentine",
    title: "Loveless",
    type: "album" as const,
    artwork_url: wiki("a/a5/MBV_-_Loveless.png"),
    release_date: "1991-11-04",
    genre: "Shoegaze / Dream Pop",
    tags: ["shoegaze", "dream-pop", "noise", "walls-of-sound"],
    mood: "ambient" as const,
    ...links("My Bloody Valentine", "Loveless"),
    curator_note: "Kevin Shields nearly bankrupted a label. The sound he found was worth it.",
  },
  {
    artist: "Led Zeppelin",
    title: "Led Zeppelin IV",
    type: "album" as const,
    artwork_url: wiki("2/26/Led_Zeppelin_-_Led_Zeppelin_IV.jpg"),
    release_date: "1971-11-08",
    genre: "Hard Rock / Folk / Blues",
    tags: ["hard-rock", "folk", "blues", "heavy-metal", "classic"],
    mood: "energetic" as const,
    ...links("Led Zeppelin", "Led Zeppelin IV"),
    curator_note: "Side two alone contains enough riffs to sustain ten other bands for their entire careers.",
  },
  {
    artist: "Public Enemy",
    title: "It Takes a Nation of Millions to Hold Us Back",
    type: "album" as const,
    artwork_url: wiki("5/54/ItTakesANation.jpg"),
    release_date: "1988-06-28",
    genre: "Hip-Hop / Political Rap",
    tags: ["hip-hop", "political", "rap", "noise", "80s"],
    mood: "energetic" as const,
    ...links("Public Enemy", "It Takes a Nation of Millions to Hold Us Back"),
    curator_note: "Chuck D rapping over a wall of noise samples — and every word landing like a verdict.",
  },
  {
    artist: "Patti Smith",
    title: "Horses",
    type: "album" as const,
    artwork_url: wiki("b/bd/Patti_smith_horses.jpg"),
    release_date: "1975-12-13",
    genre: "Punk / Art Rock / Poetry",
    tags: ["punk", "art-rock", "poetry", "proto-punk"],
    mood: "raw" as const,
    ...links("Patti Smith", "Horses"),
    curator_note: "She opened with three chords and a poem about Jesus and horses. Punk began here.",
  },
  {
    artist: "Radiohead",
    title: "Kid A",
    type: "album" as const,
    artwork_url: wiki("1/16/Radiohead_KidA.png"),
    release_date: "2000-10-02",
    genre: "Electronic / Experimental Rock",
    tags: ["electronic", "experimental", "ambient", "art-rock", "2000s"],
    mood: "hypnotic" as const,
    ...links("Radiohead", "Kid A"),
    curator_note: "The band killed themselves and became something colder and stranger and better.",
  },
  {
    artist: "Jay-Z",
    title: "The Blueprint",
    type: "album" as const,
    artwork_url: wiki("1/15/Jay-Z_-_The_Blueprint_album_cover.jpg"),
    release_date: "2001-09-11",
    genre: "Hip-Hop / East Coast",
    tags: ["hip-hop", "rap", "east-coast", "classic", "2000s"],
    mood: "energetic" as const,
    ...links("Jay-Z", "The Blueprint"),
    curator_note: "Released the morning the world changed. Nobody heard it properly until a week later.",
  },
  {
    artist: "Outkast",
    title: "Aquemini",
    type: "album" as const,
    artwork_url: wiki("b/b5/Aquemini.jpg"),
    release_date: "1998-09-29",
    genre: "Hip-Hop / Funk / Soul",
    tags: ["hip-hop", "funk", "soul", "southern-rap", "90s"],
    mood: "hypnotic" as const,
    ...links("Outkast", "Aquemini"),
    curator_note: "André 3000 and Big Boi completing each other's sentences from different galaxies.",
  },
  {
    artist: "Neil Young",
    title: "After the Gold Rush",
    type: "album" as const,
    artwork_url: wiki("3/3c/ATGR.png"),
    release_date: "1970-09-19",
    genre: "Folk Rock / Country Rock",
    tags: ["folk", "country", "rock", "classic", "70s"],
    mood: "melancholic" as const,
    ...links("Neil Young", "After the Gold Rush"),
    curator_note: "Young wrote these songs from a farmhouse and somehow they still feel planetary.",
  },

  // ════════════════════════════════════════════
  // STONER / PSYCHEDELIC / DOOM CLASSICS
  // ════════════════════════════════════════════

  {
    artist: "Black Sabbath",
    title: "Paranoid",
    type: "album" as const,
    artwork_url: wiki("2/2b/Black_Sabbath_Paranoid.jpg"),
    release_date: "1970-09-18",
    genre: "Heavy Metal / Hard Rock",
    tags: ["heavy-metal", "hard-rock", "doom", "proto-metal", "classic"],
    mood: "raw" as const,
    ...links("Black Sabbath", "Paranoid"),
    curator_note: "Iron Maiden said 'War Pigs' arrived and turned every guitar amp up to eleven forever.",
  },
  {
    artist: "Black Sabbath",
    title: "Master of Reality",
    type: "album" as const,
    artwork_url: wiki("0/05/Sabbath_MasterofReality.jpg"),
    release_date: "1971-07-21",
    genre: "Heavy Metal / Doom Metal",
    tags: ["heavy-metal", "doom", "stoner", "proto-doom", "classic"],
    mood: "hypnotic" as const,
    ...links("Black Sabbath", "Master of Reality"),
    curator_note: "Iommi tuned down after losing his fingertips. The slowest, heaviest accident in rock.",
  },
  {
    artist: "Sleep",
    title: "Dopesmoker",
    type: "album" as const,
    artwork_url: wiki("6/66/Sleep_Dopesmoker.jpg"),
    release_date: "2003-03-26",
    genre: "Doom Metal / Stoner Rock",
    tags: ["doom", "stoner-rock", "sludge", "psychedelic", "heavy"],
    mood: "hypnotic" as const,
    ...links("Sleep", "Dopesmoker"),
    curator_note: "One riff. Sixty-three minutes. The Book of Riff made flesh and immovable.",
  },
  {
    artist: "Electric Wizard",
    title: "Dopethrone",
    type: "album" as const,
    artwork_url: wiki("a/a2/Dopethrone.jpg"),
    release_date: "2000-10-16",
    genre: "Doom Metal / Stoner Doom",
    tags: ["doom", "stoner", "sludge", "heavy", "psychedelic"],
    mood: "hypnotic" as const,
    ...links("Electric Wizard", "Dopethrone"),
    curator_note: "The heaviest record ever made, recorded in a condemned building with broken equipment.",
  },
  {
    artist: "Kyuss",
    title: "Welcome to Sky Valley",
    type: "album" as const,
    artwork_url: wiki("c/c1/KyussWelcometoSkyValley.jpg"),
    release_date: "1994-06-21",
    genre: "Stoner Rock / Desert Rock",
    tags: ["stoner-rock", "desert-rock", "psychedelic", "heavy", "90s"],
    mood: "hypnotic" as const,
    ...links("Kyuss", "Welcome to Sky Valley"),
    curator_note: "Palm Desert teenagers playing generator parties in the dark. This is what that felt like.",
  },
  {
    artist: "Kyuss",
    title: "Blues for the Red Sun",
    type: "album" as const,
    artwork_url: wiki("3/35/Blues_for_the_Red_Sun.jpg"),
    release_date: "1992-05-26",
    genre: "Stoner Rock / Desert Rock",
    tags: ["stoner-rock", "desert-rock", "psychedelic", "fuzzy"],
    mood: "energetic" as const,
    ...links("Kyuss", "Blues for the Red Sun"),
    curator_note: "Josh Homme at seventeen. The fuzz on this record still hasn't been reproduced.",
  },
  {
    artist: "Tame Impala",
    title: "Currents",
    type: "album" as const,
    artwork_url: wiki("9/9b/Tame_Impala_-_Currents.png"),
    release_date: "2015-07-17",
    genre: "Psychedelic Pop / Neo-Psychedelia",
    tags: ["psychedelic", "pop", "electronic", "indie", "2010s"],
    mood: "melancholic" as const,
    ...links("Tame Impala", "Currents"),
    curator_note: "Kevin Parker breaking up with himself in a studio. Came out sounding like the future.",
  },
  {
    artist: "Tame Impala",
    title: "Lonerism",
    type: "album" as const,
    artwork_url: wiki("2/24/Tame_Impala_-_Lonerism_-_Artwork.jpg"),
    release_date: "2012-10-05",
    genre: "Psychedelic Rock / Neo-Psychedelia",
    tags: ["psychedelic", "rock", "indie", "lo-fi", "2010s"],
    mood: "melancholic" as const,
    ...links("Tame Impala", "Lonerism"),
    curator_note: "Recorded in a Paris apartment where he didn't speak the language. Sounds like it.",
  },
  {
    artist: "Pink Floyd",
    title: "Wish You Were Here",
    type: "album" as const,
    artwork_url: wiki("7/79/WishYouWereHere%28PinkFloyd%29.jpg"),
    release_date: "1975-09-12",
    genre: "Progressive Rock / Psychedelic",
    tags: ["progressive", "psychedelic", "rock", "ambient", "classic"],
    mood: "melancholic" as const,
    ...links("Pink Floyd", "Wish You Were Here"),
    curator_note: "An album about a man who wasn't there, made by men who knew exactly where he'd gone.",
  },
  {
    artist: "The Grateful Dead",
    title: "American Beauty",
    type: "album" as const,
    artwork_url: wiki("5/58/AmericanBeautyDeadAlbum.jpg"),
    release_date: "1970-11-01",
    genre: "Folk Rock / Country Rock",
    tags: ["folk", "country", "psychedelic", "americana", "classic"],
    mood: "tender" as const,
    ...links("The Grateful Dead", "American Beauty"),
    curator_note: "The Dead sat down and wrote their gentlest songs. Then went back to playing five-hour sets.",
  },
  {
    artist: "Primus",
    title: "Sailing the Seas of Cheese",
    type: "album" as const,
    artwork_url: wiki("1/1e/SailingTheSeasOfCheese.jpg"),
    release_date: "1991-04-16",
    genre: "Funk Metal / Alternative",
    tags: ["funk-metal", "alternative", "stoner", "bass-heavy", "90s"],
    mood: "energetic" as const,
    ...links("Primus", "Sailing the Seas of Cheese"),
    curator_note: "Les Claypool made bass the lead instrument and everyone else a rhythm section.",
  },
  {
    artist: "Monster Magnet",
    title: "Spine of God",
    type: "album" as const,
    artwork_url: wiki("d/d2/SpineofGod.jpg"),
    release_date: "1991-10-22",
    genre: "Stoner Rock / Space Rock",
    tags: ["stoner-rock", "space-rock", "psychedelic", "heavy", "90s"],
    mood: "hypnotic" as const,
    ...links("Monster Magnet", "Spine of God"),
    curator_note: "Dave Wyndorf operating a psychedelic death machine with no off switch.",
  },
  {
    artist: "Clutch",
    title: "Elephant Riders",
    type: "album" as const,
    artwork_url: wiki("5/56/Elephant_Riders.jpg"),
    release_date: "1998-05-19",
    genre: "Stoner Rock / Hard Rock",
    tags: ["stoner-rock", "hard-rock", "groove-metal", "90s"],
    mood: "raw" as const,
    ...links("Clutch", "Elephant Riders"),
    curator_note: "Neil Fallon preaching the gospel of heavy groove to anyone with ears to hear it.",
  },
  {
    artist: "High on Fire",
    title: "Blessed Black Wings",
    type: "album" as const,
    artwork_url: wiki("5/5b/Blessed_Black_Wings.jpg"),
    release_date: "2005-02-22",
    genre: "Sludge Metal / Stoner Metal",
    tags: ["sludge", "stoner-metal", "doom", "heavy", "2000s"],
    mood: "raw" as const,
    ...links("High on Fire", "Blessed Black Wings"),
    curator_note: "Matt Pike wrote this during a period of extreme self-destruction. Sounds correct.",
  },
  {
    artist: "Boards of Canada",
    title: "Music Has the Right to Children",
    type: "album" as const,
    artwork_url: wiki("9/95/MHTRtC.jpg"),
    release_date: "1998-04-20",
    genre: "Electronic / Ambient / IDM",
    tags: ["electronic", "ambient", "idm", "psychedelic", "nostalgic"],
    mood: "ambient" as const,
    ...links("Boards of Canada", "Music Has the Right to Children"),
    curator_note: "Scottish brothers sampling static to make something that feels like childhood remembered wrong.",
  },

  // ════════════════════════════════════════════
  // GRAMMY ALBUM OF THE YEAR — RECENT WINNERS
  // ════════════════════════════════════════════

  {
    artist: "Taylor Swift",
    title: "Midnights",
    type: "album" as const,
    artwork_url: wiki("9/9f/Midnights_-_Taylor_Swift.png"),
    release_date: "2022-10-21",
    genre: "Synth-Pop / Indie Pop",
    tags: ["synth-pop", "indie-pop", "2020s", "grammy-winner"],
    mood: "melancholic" as const,
    ...links("Taylor Swift", "Midnights"),
    curator_note: "3am thoughts structured like pop music. The album that won her a fourth Album of the Year.",
  },
  {
    artist: "Harry Styles",
    title: "Harry's House",
    type: "album" as const,
    artwork_url: wiki("8/84/Harry%27s_House_-_Harry_Styles.png"),
    release_date: "2022-05-20",
    genre: "Pop / Indie Pop",
    tags: ["pop", "indie-pop", "2020s", "grammy-winner"],
    mood: "euphoric" as const,
    ...links("Harry Styles", "Harry's House"),
    curator_note: "He found his own voice and it sounded like summer and a little like Joni Mitchell.",
  },
  {
    artist: "Jon Batiste",
    title: "We Are",
    type: "album" as const,
    artwork_url: wiki("d/d4/Jon_Batiste_We_Are.jpg"),
    release_date: "2021-03-19",
    genre: "R&B / Soul / Jazz",
    tags: ["r&b", "soul", "jazz", "2020s", "grammy-winner"],
    mood: "euphoric" as const,
    ...links("Jon Batiste", "We Are"),
    curator_note: "New Orleans blood + classical training + undeniable joy. The happiest Grammy winner in years.",
  },
  {
    artist: "Taylor Swift",
    title: "Folklore",
    type: "album" as const,
    artwork_url: wiki("f/f8/Taylor_Swift_-_Folklore.png"),
    release_date: "2020-07-24",
    genre: "Indie Folk / Alternative",
    tags: ["indie-folk", "alternative", "2020s", "grammy-winner", "pandemic"],
    mood: "melancholic" as const,
    ...links("Taylor Swift", "Folklore"),
    curator_note: "Made in quarantine with Aaron Dessner. She invented a fictional town and moved there.",
  },
  {
    artist: "Billie Eilish",
    title: "When We All Fall Asleep, Where Do We Go?",
    type: "album" as const,
    artwork_url: wiki("3/38/When_We_All_Fall_Asleep%2C_Where_Do_We_Go%3F.png"),
    release_date: "2019-03-29",
    genre: "Electropop / Dark Pop",
    tags: ["electropop", "dark-pop", "asmr", "2010s", "grammy-winner"],
    mood: "hypnotic" as const,
    ...links("Billie Eilish", "When We All Fall Asleep, Where Do We Go?"),
    curator_note: "Made in her brother's bedroom. Sounded like nothing else. Became everything immediately.",
  },
  {
    artist: "Kacey Musgraves",
    title: "Golden Hour",
    type: "album" as const,
    artwork_url: wiki("6/65/Kacey_Musgraves_-_Golden_Hour.png"),
    release_date: "2018-03-30",
    genre: "Country Pop / Psychedelic Country",
    tags: ["country", "pop", "psychedelic", "2010s", "grammy-winner"],
    mood: "euphoric" as const,
    ...links("Kacey Musgraves", "Golden Hour"),
    curator_note: "Country music discovered MDMA and it was genuinely beautiful. Musgraves at her peak.",
  },
  {
    artist: "Bruno Mars",
    title: "24K Magic",
    type: "album" as const,
    artwork_url: wiki("0/00/24K_Magic_Bruno_Mars.png"),
    release_date: "2016-11-18",
    genre: "R&B / Funk",
    tags: ["r&b", "funk", "pop", "2010s", "grammy-winner"],
    mood: "euphoric" as const,
    ...links("Bruno Mars", "24K Magic"),
    curator_note: "Pure, unapologetic funk worship. Mars playing every reference and making it his own.",
  },
  {
    artist: "Adele",
    title: "25",
    type: "album" as const,
    artwork_url: wiki("8/8a/Adele_-_25.png"),
    release_date: "2015-11-20",
    genre: "Pop / Soul",
    tags: ["pop", "soul", "2010s", "grammy-winner", "ballad"],
    mood: "melancholic" as const,
    ...links("Adele", "25"),
    curator_note: "The voice that can stop a room — and the songs that gave it somewhere to go.",
  },
  {
    artist: "Beck",
    title: "Morning Phase",
    type: "album" as const,
    artwork_url: wiki("7/7c/Beck_Morning_Phase.png"),
    release_date: "2014-02-21",
    genre: "Folk Rock / Dream Pop",
    tags: ["folk-rock", "dream-pop", "2010s", "grammy-winner"],
    mood: "ambient" as const,
    ...links("Beck", "Morning Phase"),
    curator_note: "Beck made a record about dawn that actually sounds like dawn. Very few artists manage that.",
  },
  {
    artist: "Daft Punk",
    title: "Random Access Memories",
    type: "album" as const,
    artwork_url: wiki("a/a7/Random_Access_Memories.jpg"),
    release_date: "2013-05-17",
    genre: "Electronic / Disco / Funk",
    tags: ["electronic", "disco", "funk", "2010s", "grammy-winner"],
    mood: "euphoric" as const,
    ...links("Daft Punk", "Random Access Memories"),
    curator_note: "Two French robots brought Giorgio Moroder back. The internet wept with gratitude.",
  },

  // ════════════════════════════════════════════
  // GRAMMY — MAJOR CATEGORY WINNERS (RECENT)
  // ════════════════════════════════════════════

  {
    artist: "Beyoncé",
    title: "Renaissance",
    type: "album" as const,
    artwork_url: wiki("5/5a/Renaissance_album_cover.jpg"),
    release_date: "2022-07-29",
    genre: "Dance / Electronic / R&B",
    tags: ["dance", "electronic", "r&b", "house", "2020s", "grammy-winner"],
    mood: "euphoric" as const,
    ...links("Beyoncé", "Renaissance"),
    curator_note: "A love letter to Black queer dance music that became the biggest album of the year.",
  },
  {
    artist: "Kendrick Lamar",
    title: "Mr. Morale & the Big Steppers",
    type: "album" as const,
    artwork_url: wiki("4/41/Mr._Morale_%26_the_Big_Steppers.png"),
    release_date: "2022-05-13",
    genre: "Hip-Hop / Conscious Rap",
    tags: ["hip-hop", "conscious-rap", "2020s", "grammy-winner"],
    mood: "raw" as const,
    ...links("Kendrick Lamar", "Mr. Morale & the Big Steppers"),
    curator_note: "Five years of therapy disguised as rap music. The most uncomfortable comfortable listen.",
  },
  {
    artist: "Wet Leg",
    title: "Wet Leg",
    type: "album" as const,
    artwork_url: wiki("e/e7/Wet_Leg_album_cover.png"),
    release_date: "2022-04-08",
    genre: "Indie Rock / Post-Punk",
    tags: ["indie-rock", "post-punk", "wit", "2020s", "grammy-winner"],
    mood: "energetic" as const,
    ...links("Wet Leg", "Wet Leg"),
    curator_note: "Two women from the Isle of Wight being extremely funny about very serious things.",
  },
  {
    artist: "Silk Sonic",
    title: "An Evening with Silk Sonic",
    type: "album" as const,
    artwork_url: wiki("8/8e/Silk_Sonic_-_An_Evening_with_Silk_Sonic.png"),
    release_date: "2021-11-05",
    genre: "R&B / Soul / Funk",
    tags: ["r&b", "soul", "funk", "2020s", "grammy-winner"],
    mood: "euphoric" as const,
    ...links("Silk Sonic", "An Evening with Silk Sonic"),
    curator_note: "Anderson .Paak and Bruno Mars settled into the 70s like they'd been waiting to return.",
  },
  {
    artist: "Olivia Rodrigo",
    title: "SOUR",
    type: "album" as const,
    artwork_url: wiki("b/b0/Olivia_Rodrigo_-_Sour.png"),
    release_date: "2021-05-21",
    genre: "Pop / Bedroom Pop / Pop-Punk",
    tags: ["pop", "bedroom-pop", "pop-punk", "2020s", "grammy-winner"],
    mood: "raw" as const,
    ...links("Olivia Rodrigo", "SOUR"),
    curator_note: "Heartbreak at nineteen, documented live. The specificity is what makes it universal.",
  },
  {
    artist: "SZA",
    title: "SOS",
    type: "album" as const,
    artwork_url: wiki("6/65/SZA_-_SOS_%28album_cover%29.png"),
    release_date: "2022-12-09",
    genre: "R&B / Alternative R&B",
    tags: ["r&b", "alternative-r&b", "2020s", "grammy-winner"],
    mood: "melancholic" as const,
    ...links("SZA", "SOS"),
    curator_note: "The S.O.S. distress call that R&B needed. She crams seventy minutes of feeling into every song.",
  },
  {
    artist: "Bad Bunny",
    title: "Un Verano Sin Ti",
    type: "album" as const,
    artwork_url: wiki("5/5e/Un_Verano_Sin_Ti.jpg"),
    release_date: "2022-05-06",
    genre: "Reggaeton / Latin Trap",
    tags: ["reggaeton", "latin-trap", "dembow", "2020s", "grammy-winner"],
    mood: "euphoric" as const,
    ...links("Bad Bunny", "Un Verano Sin Ti"),
    curator_note: "Puerto Rico's summer distilled into two hours. Most-streamed album on Spotify. Justifiably.",
  },
  {
    artist: "Lana Del Rey",
    title: "Did You Know That There's a Tunnel Under Ocean Blvd",
    type: "album" as const,
    artwork_url: wiki("3/39/Did_You_Know_That_There%27s_a_Tunnel_Under_Ocean_Blvd.png"),
    release_date: "2023-03-24",
    genre: "Art Pop / Dream Pop",
    tags: ["art-pop", "dream-pop", "americana", "2020s"],
    mood: "melancholic" as const,
    ...links("Lana Del Rey", "Did You Know That There's a Tunnel Under Ocean Blvd"),
    curator_note: "Her longest album and her best. The sadness has become a landscape she lives in now.",
  },
  {
    artist: "Tyler, the Creator",
    title: "IGOR",
    type: "album" as const,
    artwork_url: wiki("d/de/Tyler%2C_the_Creator_-_Igor_%28artwork%29.jpg"),
    release_date: "2019-05-17",
    genre: "Neo-Soul / Art Pop / Hip-Hop",
    tags: ["neo-soul", "art-pop", "hip-hop", "2010s", "grammy-winner"],
    mood: "melancholic" as const,
    ...links("Tyler, the Creator", "IGOR"),
    curator_note: "A concept album about unrequited love told through an alter-ego in a blonde wig.",
  },
  {
    artist: "Cardi B",
    title: "Invasion of Privacy",
    type: "album" as const,
    artwork_url: wiki("f/f1/Invasion_of_Privacy_album.jpg"),
    release_date: "2018-04-06",
    genre: "Hip-Hop / Trap / Pop Rap",
    tags: ["hip-hop", "trap", "pop-rap", "2010s", "grammy-winner"],
    mood: "energetic" as const,
    ...links("Cardi B", "Invasion of Privacy"),
    curator_note: "First solo female rap Grammy winner. She said what she meant and meant all of it.",
  },

];

export type CatalogEntry = (typeof RELEASES)[number];

export const CATALOG_DATA = RELEASES;

// Fully-typed Release[] with deterministic ids, newest first
export const CATALOG: Release[] = RELEASES.map((r, i) => ({
  id: `catalog-${String(i).padStart(3, "0")}`,
  artist: r.artist,
  title: r.title,
  type: r.type,
  artwork_url: r.artwork_url,
  release_date: r.release_date,
  genre: r.genre ?? null,
  tags: r.tags ?? [],
  mood: r.mood ?? null,
  spotify: r.spotify,
  apple_music: r.apple_music,
  tidal: r.tidal,
  soundcloud: r.soundcloud,
  youtube_music: r.youtube_music,
  created_at: r.release_date + "T00:00:00Z",
  curator_note: r.curator_note ?? null,
})).sort((a, b) => (a.release_date < b.release_date ? 1 : -1));
