/**
 * Pulsar — Expanded Catalog vol.2
 * 172 canonical albums across jazz, reggae/dub, house/techno,
 * punk/post-punk, soul/funk/disco, latin, k-pop/city-pop, UK garage/grime,
 * African music and country/gospel/blues.
 *
 * Artwork resolves through /api/artwork (strict-matching iTunes proxy) so
 * every tile shows the album's REAL cover. Generated by a parallel
 * generate->verify multi-agent workflow.
 */

import type { Release } from "./types";

const enc = encodeURIComponent;

const links = (artist: string, title: string) => {
  const q = `${artist} ${title}`;
  return {
    spotify: `https://open.spotify.com/search/${enc(q)}`,
    apple_music: `https://music.apple.com/search?term=${enc(q)}`,
    tidal: `https://tidal.com/search?q=${enc(q)}`,
    soundcloud: `https://soundcloud.com/search?q=${enc(q)}`,
    youtube_music: `https://music.youtube.com/search?q=${enc(q)}`,
  };
};

interface Entry {
  artist: string;
  title: string;
  release_date: string;
  genre: string | null;
  tags: string[];
  mood: Release["mood"];
  curator_note: string | null;
}

const ENTRIES: Entry[] = [
  {
    "artist": "Miles Davis",
    "title": "Kind of Blue",
    "release_date": "1959-08-17",
    "genre": "Jazz / Modal",
    "tags": [
      "modal",
      "cool jazz",
      "1950s",
      "trumpet"
    ],
    "mood": "ambient",
    "curator_note": "Five first-take sketches on modes instead of chords, and somehow the most relaxed record ever cut in a Manhattan church-turned-studio."
  },
  {
    "artist": "John Coltrane",
    "title": "A Love Supreme",
    "release_date": "1965-01-01",
    "genre": "Jazz / Spiritual",
    "tags": [
      "spiritual jazz",
      "quartet",
      "suite"
    ],
    "mood": "euphoric",
    "curator_note": "A four-part prayer where Coltrane chants the title through his horn in every key, as if testing whether devotion survives transposition."
  },
  {
    "artist": "John Coltrane",
    "title": "Giant Steps",
    "release_date": "1960-02-01",
    "genre": "Jazz / Hard Bop",
    "tags": [
      "hard bop",
      "saxophone",
      "changes"
    ],
    "mood": "energetic",
    "curator_note": "The title track's chord cycle moves in thirds so fast that pianist Tommy Flanagan famously stumbles, and sixty years of saxophonists have practiced it ever since."
  },
  {
    "artist": "Charles Mingus",
    "title": "Mingus Ah Um",
    "release_date": "1959-10-01",
    "genre": "Jazz / Post-Bop",
    "tags": [
      "post-bop",
      "gospel",
      "protest"
    ],
    "mood": "raw",
    "curator_note": "Mingus eulogizes Lester Young with a sob, mocks an Arkansas governor with a sneer, and turns a gospel meeting into a bass-led riot, all on one LP."
  },
  {
    "artist": "Charles Mingus",
    "title": "The Black Saint and the Sinner Lady",
    "release_date": "1963-07-01",
    "genre": "Jazz / Avant-Garde",
    "tags": [
      "big band",
      "orchestral",
      "avant-garde"
    ],
    "mood": "cinematic",
    "curator_note": "An eleven-piece band lurches between flamenco guitar, overdubbed screams, and ballroom swing while Mingus's psychotherapist writes the liner notes."
  },
  {
    "artist": "Alice Coltrane",
    "title": "Journey in Satchidananda",
    "release_date": "1971-02-01",
    "genre": "Jazz / Spiritual",
    "tags": [
      "spiritual jazz",
      "harp",
      "drone"
    ],
    "mood": "hypnotic",
    "curator_note": "Harp glissandi ripple over a tamboura drone and Cecil McBee's two-note bass vamp until the room starts to smell faintly of incense."
  },
  {
    "artist": "Kamasi Washington",
    "title": "The Epic",
    "release_date": "2015-05-05",
    "genre": "Jazz / Spiritual",
    "tags": [
      "los angeles",
      "choir",
      "triple album"
    ],
    "mood": "cinematic",
    "curator_note": "Three hours of tenor saxophone backed by a choir and string section, made by the same South Central crew that built Kendrick's To Pimp a Butterfly."
  },
  {
    "artist": "Robert Glasper",
    "title": "Black Radio",
    "release_date": "2012-02-28",
    "genre": "Jazz / R&B",
    "tags": [
      "neo-soul",
      "hip-hop",
      "piano"
    ],
    "mood": "tender",
    "curator_note": "Glasper's trio dissolves the border between a jazz club and a late-night R&B station, closing with a Nirvana cover sung through a vocoder."
  },
  {
    "artist": "The Dave Brubeck Quartet",
    "title": "Time Out",
    "release_date": "1959-12-14",
    "genre": "Jazz / Cool Jazz",
    "tags": [
      "cool jazz",
      "odd meters",
      "1950s"
    ],
    "mood": "energetic",
    "curator_note": "Columbia executives feared no one could dance in 5/4, then Take Five became the best-selling jazz single ever pressed."
  },
  {
    "artist": "Thelonious Monk",
    "title": "Brilliant Corners",
    "release_date": "1957-04-01",
    "genre": "Jazz / Bebop",
    "tags": [
      "bebop",
      "piano",
      "angular"
    ],
    "mood": "raw",
    "curator_note": "The title tune was so knotted that twenty-five takes never yielded a complete one, so the issued version is spliced together from the wreckage."
  },
  {
    "artist": "Ornette Coleman",
    "title": "The Shape of Jazz to Come",
    "release_date": "1959-10-01",
    "genre": "Jazz / Free Jazz",
    "tags": [
      "free jazz",
      "plastic sax",
      "quartet"
    ],
    "mood": "raw",
    "curator_note": "A pianoless quartet led by a white plastic alto abandons chord changes entirely, and Lonely Woman still sounds like a wail from the desert."
  },
  {
    "artist": "Eric Dolphy",
    "title": "Out to Lunch!",
    "release_date": "1964-08-01",
    "genre": "Jazz / Avant-Garde",
    "tags": [
      "avant-garde",
      "bass clarinet",
      "blue note"
    ],
    "mood": "hypnotic",
    "curator_note": "Dolphy's bass clarinet argues with Bobby Hutcherson's vibes over Tony Williams's teenage drumming, four months before Dolphy died in Berlin."
  },
  {
    "artist": "Herbie Hancock",
    "title": "Head Hunters",
    "release_date": "1973-10-26",
    "genre": "Jazz / Funk",
    "tags": [
      "jazz-funk",
      "synthesizer",
      "1970s"
    ],
    "mood": "energetic",
    "curator_note": "Hancock swaps his acoustic grand for a bank of synthesizers and a beer-bottle intro, and Chameleon's bassline colonizes every funk band since."
  },
  {
    "artist": "Herbie Hancock",
    "title": "Maiden Voyage",
    "release_date": "1965-05-01",
    "genre": "Jazz / Post-Bop",
    "tags": [
      "post-bop",
      "modal",
      "blue note"
    ],
    "mood": "ambient",
    "curator_note": "A concept album about the ocean where suspended chords roll like swells and Freddie Hubbard's trumpet cuts through like sun on water."
  },
  {
    "artist": "Weather Report",
    "title": "Heavy Weather",
    "release_date": "1977-03-01",
    "genre": "Jazz / Fusion",
    "tags": [
      "fusion",
      "fretless bass",
      "1970s"
    ],
    "mood": "euphoric",
    "curator_note": "Jaco Pastorius's fretless bass sings Birdland's melody like a horn, and marching bands have been trying to keep up ever since."
  },
  {
    "artist": "Keith Jarrett",
    "title": "The Köln Concert",
    "release_date": "1975-11-30",
    "genre": "Jazz / Solo Piano",
    "tags": [
      "solo piano",
      "improvisation",
      "ecm"
    ],
    "mood": "tender",
    "curator_note": "Exhausted and stuck with the wrong piano, Jarrett improvised for an hour anyway, groaning along to what became the best-selling solo album in jazz history."
  },
  {
    "artist": "Art Blakey & The Jazz Messengers",
    "title": "Moanin'",
    "release_date": "1959-01-01",
    "genre": "Jazz / Hard Bop",
    "tags": [
      "hard bop",
      "gospel",
      "drums"
    ],
    "mood": "energetic",
    "curator_note": "Bobby Timmons's call-and-response title riff brought the church into the nightclub, driven by Blakey's press rolls like weather fronts."
  },
  {
    "artist": "Stan Getz & João Gilberto",
    "title": "Getz/Gilberto",
    "release_date": "1964-03-01",
    "genre": "Jazz / Bossa Nova",
    "tags": [
      "bossa nova",
      "brazil",
      "saxophone"
    ],
    "mood": "tender",
    "curator_note": "Astrud Gilberto had never sung professionally before she stepped to the mic for The Girl from Ipanema, and her shrug of a voice sold the world on bossa nova."
  },
  {
    "artist": "Wayne Shorter",
    "title": "Speak No Evil",
    "release_date": "1966-06-01",
    "genre": "Jazz / Post-Bop",
    "tags": [
      "post-bop",
      "blue note",
      "composition"
    ],
    "mood": "cinematic",
    "curator_note": "Six Shorter originals about witches and dance cadavers, played with such poise that the eeriness only registers on the third listen."
  },
  {
    "artist": "Pharoah Sanders",
    "title": "Karma",
    "release_date": "1969-05-01",
    "genre": "Jazz / Spiritual",
    "tags": [
      "spiritual jazz",
      "tenor sax",
      "1960s"
    ],
    "mood": "euphoric",
    "curator_note": "The Creator Has a Master Plan spends thirty-two minutes swinging between yodeled bliss and tenor shrieks, Leon Thomas gargling joy the whole way."
  },
  {
    "artist": "Miles Davis",
    "title": "Bitches Brew",
    "release_date": "1970-03-30",
    "genre": "Jazz / Fusion",
    "tags": [
      "fusion",
      "electric",
      "1970s"
    ],
    "mood": "hypnotic",
    "curator_note": "Two drummers, three electric pianos, and a producer's razor blade turned studio jams into a dark churn that rock kids bought by the hundreds of thousands."
  },
  {
    "artist": "Sons of Kemet",
    "title": "Your Queen Is a Reptile",
    "release_date": "2018-03-30",
    "genre": "Jazz / Afro-Caribbean",
    "tags": [
      "uk jazz",
      "tuba",
      "protest"
    ],
    "mood": "raw",
    "curator_note": "Shabaka Hutchings's sax rides a tuba and two drum kits through nine tracks, each renaming the British crown after a Black woman who actually earned it."
  },
  {
    "artist": "Jimmy Cliff",
    "title": "The Harder They Come",
    "release_date": "1972-07-07",
    "genre": "Reggae / Soundtrack",
    "tags": [
      "soundtrack",
      "kingston",
      "rocksteady",
      "1970s"
    ],
    "mood": "energetic",
    "curator_note": "The film soundtrack that carried Kingston's rude-boy swagger abroad, with 'Many Rivers to Cross' as its bruised gospel heart."
  },
  {
    "artist": "Bob Marley & The Wailers",
    "title": "Catch a Fire",
    "release_date": "1973-04-13",
    "genre": "Reggae / Roots Reggae",
    "tags": [
      "roots",
      "island records",
      "trench town"
    ],
    "mood": "raw",
    "curator_note": "Chris Blackwell laced Muscle Shoals guitar over Wailers rhythm tracks, building the bridge reggae rode out of Trench Town."
  },
  {
    "artist": "Toots & The Maytals",
    "title": "Funky Kingston",
    "release_date": "1973-01-01",
    "genre": "Reggae / Soul",
    "tags": [
      "soul",
      "ska roots",
      "kingston"
    ],
    "mood": "euphoric",
    "curator_note": "Toots Hibbert testifies like Otis Redding raised on ska, turning even 'Country Roads' into a Kingston revival meeting."
  },
  {
    "artist": "Burning Spear",
    "title": "Marcus Garvey",
    "release_date": "1975-12-12",
    "genre": "Reggae / Roots Reggae",
    "tags": [
      "roots",
      "rasta",
      "jack ruby"
    ],
    "mood": "hypnotic",
    "curator_note": "Winston Rodney intones Garveyite history over Jack Ruby's horn-heavy productions until remembrance starts to sound like prophecy."
  },
  {
    "artist": "Peter Tosh",
    "title": "Legalize It",
    "release_date": "1976-06-01",
    "genre": "Reggae / Roots Reggae",
    "tags": [
      "roots",
      "protest",
      "solo debut"
    ],
    "mood": "raw",
    "curator_note": "Tosh's opening statement after quitting the Wailers: a title track banned from Jamaican radio that became the legalization movement's anthem anyway."
  },
  {
    "artist": "Lee \"Scratch\" Perry & The Upsetters",
    "title": "Super Ape",
    "release_date": "1976-01-01",
    "genre": "Dub / Roots Reggae",
    "tags": [
      "dub",
      "black ark",
      "producer album"
    ],
    "mood": "hypnotic",
    "curator_note": "Perry sinks drums, flutes, and chanted vocals into Black Ark tape murk until the mix itself seems to breathe."
  },
  {
    "artist": "Augustus Pablo",
    "title": "King Tubbys Meets Rockers Uptown",
    "release_date": "1976-01-01",
    "genre": "Dub / Reggae",
    "tags": [
      "dub",
      "melodica",
      "king tubby"
    ],
    "mood": "hypnotic",
    "curator_note": "Pablo's minor-key melodica drifts through Tubby's dropouts and thunder-crack reverb on the most quoted title in dub."
  },
  {
    "artist": "Bob Marley & The Wailers",
    "title": "Exodus",
    "release_date": "1977-06-03",
    "genre": "Reggae / Roots Reggae",
    "tags": [
      "roots",
      "london exile",
      "one love"
    ],
    "mood": "euphoric",
    "curator_note": "Recorded in London exile after gunmen raided Hope Road, one side pleads for deliverance while the other simply dances."
  },
  {
    "artist": "Culture",
    "title": "Two Sevens Clash",
    "release_date": "1977-01-01",
    "genre": "Reggae / Roots Reggae",
    "tags": [
      "roots",
      "prophecy",
      "joe gibbs"
    ],
    "mood": "cinematic",
    "curator_note": "Joseph Hill's vision of judgment gripped Kingston so hard that shops shuttered on July 7, 1977, waiting for the sevens to clash."
  },
  {
    "artist": "The Congos",
    "title": "Heart of the Congos",
    "release_date": "1977-01-01",
    "genre": "Reggae / Roots Reggae",
    "tags": [
      "roots",
      "black ark",
      "falsetto"
    ],
    "mood": "hypnotic",
    "curator_note": "Cedric Myton's falsetto floats over mooing cow effects and phased hi-hats in the densest session the Black Ark ever yielded."
  },
  {
    "artist": "Scientist",
    "title": "Scientist Rids the World of the Evil Curse of the Vampires",
    "release_date": "1981-01-01",
    "genre": "Dub / Reggae",
    "tags": [
      "dub",
      "roots radics",
      "engineer"
    ],
    "mood": "cinematic",
    "curator_note": "A young engineer at Tubby's board strips Roots Radics riddims down to skeleton crews of drum and bass, horror-comic sleeve included."
  },
  {
    "artist": "Black Uhuru",
    "title": "Red",
    "release_date": "1981-01-01",
    "genre": "Reggae / Roots Reggae",
    "tags": [
      "roots",
      "sly and robbie",
      "militant"
    ],
    "mood": "energetic",
    "curator_note": "Sly and Robbie's syndrum cracks ricochet under Michael Rose's keening wail, roots message music refitted with chrome plating."
  },
  {
    "artist": "Sister Nancy",
    "title": "One Two",
    "release_date": "1982-01-01",
    "genre": "Dancehall / Reggae",
    "tags": [
      "dancehall",
      "deejay",
      "bam bam"
    ],
    "mood": "energetic",
    "curator_note": "The first album from a female dancehall deejay, and the home of 'Bam Bam,' the Stalag cut half of hip-hop has borrowed since."
  },
  {
    "artist": "Gregory Isaacs",
    "title": "Night Nurse",
    "release_date": "1982-08-02",
    "genre": "Reggae / Lovers Rock",
    "tags": [
      "lovers rock",
      "cool ruler",
      "roots radics"
    ],
    "mood": "tender",
    "curator_note": "The Cool Ruler murmurs his sweetest bedside plea over a Roots Radics groove unhurried enough to lower your pulse."
  },
  {
    "artist": "Shabba Ranks",
    "title": "As Raw as Ever",
    "release_date": "1991-05-21",
    "genre": "Dancehall / Ragga",
    "tags": [
      "dancehall",
      "ragga",
      "grammy"
    ],
    "mood": "energetic",
    "curator_note": "Dancehall's first Grammy went here, Shabba's diesel-engine baritone flattening every riddim Bobby Digital hands him."
  },
  {
    "artist": "Buju Banton",
    "title": "'Til Shiloh",
    "release_date": "1995-07-18",
    "genre": "Dancehall / Roots Reggae",
    "tags": [
      "dancehall",
      "rasta",
      "conscious"
    ],
    "mood": "raw",
    "curator_note": "Mid-career, the gravel-voiced deejay grew locks and conscience, folding hymns like 'Untold Stories' between dancehall salvos."
  },
  {
    "artist": "Sean Paul",
    "title": "Dutty Rock",
    "release_date": "2002-11-12",
    "genre": "Dancehall / Pop",
    "tags": [
      "dancehall",
      "crossover",
      "party"
    ],
    "mood": "energetic",
    "curator_note": "'Gimme the Light' and 'Get Busy' pushed Kingston party chat to the top of American radio without translating a syllable."
  },
  {
    "artist": "Damian \"Jr. Gong\" Marley",
    "title": "Welcome to Jamrock",
    "release_date": "2005-09-12",
    "genre": "Reggae / Hip-Hop",
    "tags": [
      "reggae",
      "hip-hop",
      "jamrock"
    ],
    "mood": "cinematic",
    "curator_note": "The youngest Marley rides an Ini Kamoze loop into a state-of-the-island address sharper than any tourist brochure."
  },
  {
    "artist": "Vybz Kartel",
    "title": "Kingston Story",
    "release_date": "2011-06-21",
    "genre": "Dancehall / Electronic",
    "tags": [
      "dancehall",
      "mixpak",
      "dre skull"
    ],
    "mood": "raw",
    "curator_note": "Dre Skull's synth-built Brooklyn riddims give Worl' Boss room to be menacing, lovesick, and funny inside a single verse."
  },
  {
    "artist": "Popcaan",
    "title": "Where We Come From",
    "release_date": "2014-06-10",
    "genre": "Dancehall / Reggae",
    "tags": [
      "dancehall",
      "unruly",
      "mixpak"
    ],
    "mood": "melancholic",
    "curator_note": "Odes to dead friends sit beside pool-party hooks as Popcaan sings his St. Thomas hillside beginnings in a reedy, wounded lilt."
  },
  {
    "artist": "Chronixx",
    "title": "Chronology",
    "release_date": "2017-07-07",
    "genre": "Reggae / Roots Reggae",
    "tags": [
      "reggae revival",
      "roots",
      "jamaica"
    ],
    "mood": "euphoric",
    "curator_note": "'Smile Jamaica' and 'Skankin' Sweet' turned the roots revival from a nostalgia exercise into a national mood swing toward joy."
  },
  {
    "artist": "Koffee",
    "title": "Rapture",
    "release_date": "2019-03-14",
    "genre": "Reggae / Dancehall",
    "tags": [
      "reggae",
      "dancehall",
      "grammy",
      "spanish town"
    ],
    "mood": "euphoric",
    "curator_note": "A teenager from Spanish Town toasts gratitude over the Toast riddim and walks off with reggae's first Grammy won by a woman."
  },
  {
    "artist": "Inner City",
    "title": "Paradise",
    "release_date": "1989-05-29",
    "genre": "House / Detroit Techno",
    "tags": [
      "detroit",
      "house",
      "techno-pop"
    ],
    "mood": "euphoric",
    "curator_note": "Paris Grey's gospel-schooled hooks turn Kevin Saunderson's Detroit machine tracks into pop, carrying 'Big Fun' and 'Good Life' from the Music Institute to the top of Europe's charts."
  },
  {
    "artist": "808 State",
    "title": "90",
    "release_date": "1989-12-04",
    "genre": "Acid House / Techno",
    "tags": [
      "acid-house",
      "manchester",
      "rave"
    ],
    "mood": "hypnotic",
    "curator_note": "A lone saxophone drifts over burbling acid lines on 'Pacific State,' smuggling Manchester's warehouse scene onto Top of the Pops."
  },
  {
    "artist": "The Orb",
    "title": "The Orb's Adventures Beyond the Ultraworld",
    "release_date": "1991-04-02",
    "genre": "Ambient House / Dub",
    "tags": [
      "ambient-house",
      "chill-out",
      "dub"
    ],
    "mood": "ambient",
    "curator_note": "Two hours of dub bass, shortwave chatter, and orbiting synth pads built for the chill-out room at 5 a.m., crowned by the rooster crows and sampled reverie of 'Little Fluffy Clouds.'"
  },
  {
    "artist": "Frankie Knuckles",
    "title": "Beyond the Mix",
    "release_date": "1991-08-06",
    "genre": "House / Deep House",
    "tags": [
      "chicago",
      "house",
      "godfather"
    ],
    "mood": "tender",
    "curator_note": "The featherlight piano riff of 'The Whistle Song' distills a decade of Warehouse sermons from the DJ who gave house music its name."
  },
  {
    "artist": "Aphex Twin",
    "title": "Selected Ambient Works 85-92",
    "release_date": "1992-11-09",
    "genre": "Ambient Techno / Electronic",
    "tags": [
      "ambient-techno",
      "idm",
      "cornwall"
    ],
    "mood": "ambient",
    "curator_note": "Recorded by a Cornish teenager onto worn cassette, these hissing, weightless techno sketches sound like club music dreaming with the lights off."
  },
  {
    "artist": "Orbital",
    "title": "Orbital 2",
    "release_date": "1993-05-24",
    "genre": "Techno / Rave",
    "tags": [
      "techno",
      "uk-rave",
      "brown-album"
    ],
    "mood": "euphoric",
    "curator_note": "The Hartnoll brothers open with a looped Star Trek monologue and close on 'Halcyon + On + On,' a shimmering track named for the tranquilizer prescribed to their mother."
  },
  {
    "artist": "Underworld",
    "title": "Dubnobasswithmyheadman",
    "release_date": "1994-01-24",
    "genre": "Techno / Progressive House",
    "tags": [
      "techno",
      "uk",
      "nineties"
    ],
    "mood": "hypnotic",
    "curator_note": "Karl Hyde's cut-up taxi-window poetry mutters through nine-minute techno arteries, making 'Dark & Long' and 'Cowgirl' feel like eavesdropping on a city at 4 a.m."
  },
  {
    "artist": "The Prodigy",
    "title": "Music for the Jilted Generation",
    "release_date": "1994-07-04",
    "genre": "Breakbeat / Rave",
    "tags": [
      "breakbeat",
      "rave",
      "uk"
    ],
    "mood": "raw",
    "curator_note": "A snarling response to the Criminal Justice Bill, with 'Voodoo People' and 'Their Law' turning rave's outlaw moment into arena-sized breakbeat."
  },
  {
    "artist": "Leftfield",
    "title": "Leftism",
    "release_date": "1995-01-30",
    "genre": "Progressive House / Dub",
    "tags": [
      "progressive-house",
      "dub",
      "uk"
    ],
    "mood": "energetic",
    "curator_note": "From John Lydon's throat-shredding turn on 'Open Up' to the bass pressure of 'Release the Pressure,' this is house music poured from reinforced concrete."
  },
  {
    "artist": "Goldie",
    "title": "Timeless",
    "release_date": "1995-08-07",
    "genre": "Drum & Bass / Jungle",
    "tags": [
      "jungle",
      "drum-and-bass",
      "metalheadz"
    ],
    "mood": "cinematic",
    "curator_note": "Diane Charlemagne's voice glides over time-stretched breakbeats across a 21-minute title suite, proving jungle could carry symphonic weight."
  },
  {
    "artist": "Daft Punk",
    "title": "Homework",
    "release_date": "1997-01-20",
    "genre": "French House / Techno",
    "tags": [
      "french-house",
      "filter-disco",
      "paris"
    ],
    "mood": "energetic",
    "curator_note": "Two Parisians with a filter and a Roland turned 'Da Funk' and 'Around the World' into blueprints the next twenty years of dance music photocopied."
  },
  {
    "artist": "The Chemical Brothers",
    "title": "Dig Your Own Hole",
    "release_date": "1997-04-07",
    "genre": "Big Beat / Electronica",
    "tags": [
      "big-beat",
      "psychedelic",
      "uk"
    ],
    "mood": "energetic",
    "curator_note": "'Block Rockin' Beats' hits like a dropped amplifier, and the closing 'Private Psychedelic Reel' spins big beat into a swirling sitar rave-up."
  },
  {
    "artist": "Fatboy Slim",
    "title": "You've Come a Long Way, Baby",
    "release_date": "1998-10-19",
    "genre": "Big Beat / House",
    "tags": [
      "big-beat",
      "brighton",
      "sampling"
    ],
    "mood": "euphoric",
    "curator_note": "Norman Cook stacks Camille Yarbrough's 'Praise You' vocal over pub-piano stomp and makes cut-and-paste beach-party house a global language."
  },
  {
    "artist": "Moby",
    "title": "Play",
    "release_date": "1999-05-17",
    "genre": "Electronica / House",
    "tags": [
      "electronica",
      "downtempo",
      "sampling"
    ],
    "mood": "melancholic",
    "curator_note": "Alan Lomax's field recordings of Delta voices ride pale synth chords on a grief-tinged record that licensed every track to advertisers yet still feels private."
  },
  {
    "artist": "Daft Punk",
    "title": "Discovery",
    "release_date": "2001-03-12",
    "genre": "French House / Disco",
    "tags": [
      "french-house",
      "disco",
      "vocoder"
    ],
    "mood": "euphoric",
    "curator_note": "Filter-disco fireworks from 'One More Time' to 'Digital Love,' equal parts Supertramp samples, vocoder tears, and Saturday-morning anime gloss."
  },
  {
    "artist": "Justice",
    "title": "Cross",
    "release_date": "2007-06-11",
    "genre": "Electro House / French Touch",
    "tags": [
      "electro-house",
      "french-touch",
      "ed-banger"
    ],
    "mood": "raw",
    "curator_note": "Justice compress Metallica riffage and Michael Jackson strut into blown-out electro, with the playground chant of 'D.A.N.C.E.' as its improbable heart."
  },
  {
    "artist": "Burial",
    "title": "Untrue",
    "release_date": "2007-11-05",
    "genre": "Dubstep / UK Garage",
    "tags": [
      "dubstep",
      "uk-garage",
      "hyperdub"
    ],
    "mood": "melancholic",
    "curator_note": "Pitch-bent voices flicker like phone screens on a rainy night bus, mourning a rave era its anonymous maker was too young to attend."
  },
  {
    "artist": "Disclosure",
    "title": "Settle",
    "release_date": "2013-05-31",
    "genre": "House / UK Garage",
    "tags": [
      "uk-garage",
      "house",
      "pop-crossover"
    ],
    "mood": "energetic",
    "curator_note": "Two brothers from Surrey rewire UK garage for festival main stages, and 'Latch' hands Sam Smith's aching falsetto to the world."
  },
  {
    "artist": "Jamie xx",
    "title": "In Colour",
    "release_date": "2015-05-29",
    "genre": "House / UK Bass",
    "tags": [
      "uk-bass",
      "house",
      "steel-drums"
    ],
    "mood": "tender",
    "curator_note": "Steel drums, sub-bass, and crowd noise from long-gone pirate broadcasts, with 'Loud Places' catching the exact moment euphoria curdles into missing someone."
  },
  {
    "artist": "Bicep",
    "title": "Bicep",
    "release_date": "2017-09-01",
    "genre": "Electronica / Breakbeat",
    "tags": [
      "breakbeat",
      "belfast",
      "nostalgia"
    ],
    "mood": "melancholic",
    "curator_note": "'Glue' pairs skeletal breakbeats with synth lines that ache like memories of raves the Belfast duo only knew from tape packs."
  },
  {
    "artist": "Fred again..",
    "title": "Actual Life (April 14 - December 17 2020)",
    "release_date": "2021-04-16",
    "genre": "House / Electronic Pop",
    "tags": [
      "house",
      "voice-notes",
      "lockdown"
    ],
    "mood": "tender",
    "curator_note": "Fred Gibson chops friends' voice notes and FaceTime fragments into lockdown-era house, a diary you can dance to."
  },
  {
    "artist": "Peggy Gou",
    "title": "I Hear You",
    "release_date": "2024-06-07",
    "genre": "House / Electro Pop",
    "tags": [
      "house",
      "nineties-revival",
      "berlin"
    ],
    "mood": "euphoric",
    "curator_note": "'(It Goes Like) Nanana' bottles a bright 90s piano-house bounce, its whistled hook engineered for festival singalongs from Berlin to Seoul."
  },
  {
    "artist": "Ramones",
    "title": "Ramones",
    "release_date": "1976-04-23",
    "genre": "Punk / Rock",
    "tags": [
      "punk",
      "1970s",
      "new york",
      "cbgb"
    ],
    "mood": "energetic",
    "curator_note": "Fourteen songs in twenty-nine minutes, recorded for about six thousand dollars, that stripped rock down to leather jackets, buzzsaw chords, and a countdown of one-two-three-four."
  },
  {
    "artist": "Sex Pistols",
    "title": "Never Mind the Bollocks, Here's the Sex Pistols",
    "release_date": "1977-10-28",
    "genre": "Punk / Rock",
    "tags": [
      "punk",
      "uk",
      "1970s"
    ],
    "mood": "raw",
    "curator_note": "Banned by shops and debated in Parliament, it still hit number one in Britain on the sheer force of Johnny Rotten's sneer and Steve Jones's wall of guitars."
  },
  {
    "artist": "Television",
    "title": "Marquee Moon",
    "release_date": "1977-02-08",
    "genre": "Post-Punk / Art Rock",
    "tags": [
      "post-punk",
      "new york",
      "guitar"
    ],
    "mood": "hypnotic",
    "curator_note": "Verlaine and Lloyd's interlocking guitars turn the ten-minute title track into a slow-blooming solo that CBGB regulars still argue was the scene's true peak."
  },
  {
    "artist": "Wire",
    "title": "Pink Flag",
    "release_date": "1977-12-01",
    "genre": "Punk / Post-Punk",
    "tags": [
      "post-punk",
      "art punk",
      "uk"
    ],
    "mood": "raw",
    "curator_note": "Twenty-one fragments that end the moment their idea is spent, a punk record built with an architect's ruler that hardcore and indie bands have been quoting ever since."
  },
  {
    "artist": "The Clash",
    "title": "London Calling",
    "release_date": "1979-12-14",
    "genre": "Punk / Rock",
    "tags": [
      "punk",
      "uk",
      "double album"
    ],
    "mood": "energetic",
    "curator_note": "A double album where punk absorbs rockabilly, reggae, and jazz without losing its nerve, wrapped in a sleeve that smashes a bass where Elvis's name used to be."
  },
  {
    "artist": "Joy Division",
    "title": "Unknown Pleasures",
    "release_date": "1979-06-15",
    "genre": "Post-Punk / Gothic Rock",
    "tags": [
      "post-punk",
      "manchester",
      "1970s"
    ],
    "mood": "melancholic",
    "curator_note": "Martin Hannett smothered the band's live fury in cavernous space and breaking glass, and Ian Curtis's baritone made a Manchester factory town sound like the end of the world."
  },
  {
    "artist": "Gang of Four",
    "title": "Entertainment!",
    "release_date": "1979-09-25",
    "genre": "Post-Punk / Funk Rock",
    "tags": [
      "post-punk",
      "funk",
      "uk"
    ],
    "mood": "energetic",
    "curator_note": "Andy Gill plays guitar like a dropped tray of cutlery while the rhythm section makes Marxist critique of leisure and love something you can actually dance to."
  },
  {
    "artist": "Dead Kennedys",
    "title": "Fresh Fruit for Rotting Vegetables",
    "release_date": "1980-09-02",
    "genre": "Hardcore / Punk",
    "tags": [
      "hardcore",
      "san francisco",
      "satire"
    ],
    "mood": "energetic",
    "curator_note": "Jello Biafra's quavering carnival-barker voice turns California politics into surf-punk grand guignol, with 'Holiday in Cambodia' as its acid centerpiece."
  },
  {
    "artist": "Black Flag",
    "title": "Damaged",
    "release_date": "1981-12-05",
    "genre": "Hardcore / Punk",
    "tags": [
      "hardcore",
      "los angeles",
      "sst"
    ],
    "mood": "raw",
    "curator_note": "Rollins's first full-length with the band sounds like a man punching a mirror for thirty-five minutes, from the six-pack jokes to the genuine dread of 'Damaged I'."
  },
  {
    "artist": "Bad Brains",
    "title": "Bad Brains",
    "release_date": "1982-02-05",
    "genre": "Hardcore / Reggae",
    "tags": [
      "hardcore",
      "reggae",
      "washington dc"
    ],
    "mood": "energetic",
    "curator_note": "Released on cassette only, the ROIR tape whiplashes between the fastest hardcore ever recorded and serene dub interludes, with H.R. treating both as acts of devotion."
  },
  {
    "artist": "Hüsker Dü",
    "title": "Zen Arcade",
    "release_date": "1984-07-01",
    "genre": "Hardcore / Post-Hardcore",
    "tags": [
      "hardcore",
      "sst",
      "concept album"
    ],
    "mood": "cinematic",
    "curator_note": "A double-album runaway narrative recorded mostly in first takes, where hardcore velocity collides with psychedelia, piano interludes, and a fourteen-minute closing jam."
  },
  {
    "artist": "Minutemen",
    "title": "Double Nickels on the Dime",
    "release_date": "1984-07-01",
    "genre": "Punk / Post-Hardcore",
    "tags": [
      "punk",
      "san pedro",
      "double album"
    ],
    "mood": "energetic",
    "curator_note": "Forty-plus songs of funk-splintered working-class punk written in a van, proof of D. Boon's creed that our band could be your life."
  },
  {
    "artist": "Rites of Spring",
    "title": "Rites of Spring",
    "release_date": "1985-06-01",
    "genre": "Emo / Post-Hardcore",
    "tags": [
      "emo",
      "post-hardcore",
      "washington dc",
      "dischord"
    ],
    "mood": "raw",
    "curator_note": "Guy Picciotto sings until his voice shreds on songs about memory and loss, and Washington DC's Revolution Summer accidentally hands emo its founding document."
  },
  {
    "artist": "Fugazi",
    "title": "Repeater",
    "release_date": "1990-04-19",
    "genre": "Post-Hardcore / Punk",
    "tags": [
      "post-hardcore",
      "dischord",
      "diy"
    ],
    "mood": "energetic",
    "curator_note": "Five-dollar shows and ten-dollar records made flesh: dub-tensed basslines and two guitars arguing about capitalism, sold in the hundreds of thousands with zero advertising."
  },
  {
    "artist": "Green Day",
    "title": "Dookie",
    "release_date": "1994-02-01",
    "genre": "Pop Punk / Punk",
    "tags": [
      "pop punk",
      "1990s",
      "california"
    ],
    "mood": "euphoric",
    "curator_note": "Three Gilman Street brats compress boredom, panic attacks, and self-abuse jokes into radio-perfect hooks and drag punk onto every suburban bedroom stereo in America."
  },
  {
    "artist": "Sunny Day Real Estate",
    "title": "Diary",
    "release_date": "1994-05-10",
    "genre": "Emo / Indie Rock",
    "tags": [
      "emo",
      "seattle",
      "sub pop",
      "1990s"
    ],
    "mood": "melancholic",
    "curator_note": "Jeremy Enigk's cracked-angel wail rides quiet-loud tides on 'Seven' and 'In Circles', giving second-wave emo its Rosetta stone from inside grunge-era Seattle."
  },
  {
    "artist": "Refused",
    "title": "The Shape of Punk to Come",
    "release_date": "1998-10-27",
    "genre": "Hardcore / Post-Hardcore",
    "tags": [
      "hardcore",
      "sweden",
      "1990s"
    ],
    "mood": "energetic",
    "curator_note": "Swedish hardcore kids splice jazz breaks, techno pulses, and manifesto liner notes into 'New Noise', break up within months, and watch the next two decades catch up."
  },
  {
    "artist": "Jimmy Eat World",
    "title": "Clarity",
    "release_date": "1999-02-23",
    "genre": "Emo / Alternative Rock",
    "tags": [
      "emo",
      "arizona",
      "1990s"
    ],
    "mood": "tender",
    "curator_note": "A commercial flop that became scripture, trading hardcore roots for chiming vibraphones, drum loops, and the sixteen-minute lullaby sprawl of 'Goodbye Sky Harbor'."
  },
  {
    "artist": "American Football",
    "title": "American Football",
    "release_date": "1999-09-14",
    "genre": "Emo / Math Rock",
    "tags": [
      "emo",
      "midwest",
      "math rock"
    ],
    "mood": "melancholic",
    "curator_note": "College kids in Urbana tune their guitars to autumn, add trumpet and odd time signatures, and the house on the cover becomes a pilgrimage site for two generations of sad teens."
  },
  {
    "artist": "Converge",
    "title": "Jane Doe",
    "release_date": "2001-09-04",
    "genre": "Hardcore / Metalcore",
    "tags": [
      "metalcore",
      "hardcore",
      "massachusetts"
    ],
    "mood": "cinematic",
    "curator_note": "A breakup album delivered as controlled demolition, Jacob Bannon's larynx-tearing grief resolving into the slow, enormous tide of the closing title track."
  },
  {
    "artist": "Interpol",
    "title": "Turn On the Bright Lights",
    "release_date": "2002-08-19",
    "genre": "Post-Punk / Indie Rock",
    "tags": [
      "post-punk revival",
      "new york",
      "2000s"
    ],
    "mood": "hypnotic",
    "curator_note": "Suit-clad New Yorkers filter post-punk gloom through the haze of a city just after September 2001, all reverb-slicked guitars and Paul Banks's deadpan non sequiturs."
  },
  {
    "artist": "My Chemical Romance",
    "title": "The Black Parade",
    "release_date": "2006-10-23",
    "genre": "Emo / Pop Punk",
    "tags": [
      "emo",
      "2000s",
      "concept album"
    ],
    "mood": "cinematic",
    "curator_note": "A dying cancer patient's life flashes by as a marching-band rock opera, turning mall-emo into stadium theater complete with Liza Minnelli cameo."
  },
  {
    "artist": "Otis Redding",
    "title": "Otis Blue: Otis Redding Sings Soul",
    "release_date": "1965-09-15",
    "genre": "Soul / Southern Soul",
    "tags": [
      "stax",
      "memphis",
      "60s soul"
    ],
    "mood": "raw",
    "curator_note": "Cut in one 24-hour Stax marathon, Redding tears through 'Respect' and 'I've Been Loving You Too Long' with a horn section that hits like a heartbeat."
  },
  {
    "artist": "Aretha Franklin",
    "title": "I Never Loved a Man the Way I Love You",
    "release_date": "1967-03-10",
    "genre": "Soul / R&B",
    "tags": [
      "atlantic",
      "muscle shoals",
      "gospel roots"
    ],
    "mood": "euphoric",
    "curator_note": "The moment Aretha sat at the Muscle Shoals piano and turned 'Respect' from a plea into a demand, soul music got its queen."
  },
  {
    "artist": "Sly and the Family Stone",
    "title": "Stand!",
    "release_date": "1969-05-03",
    "genre": "Funk / Psychedelic Soul",
    "tags": [
      "psychedelic",
      "woodstock era",
      "integration"
    ],
    "mood": "euphoric",
    "curator_note": "An integrated band preaching 'Everyday People' over fuzz bass and gospel handclaps, months before playing it to half a million people at Woodstock."
  },
  {
    "artist": "Isaac Hayes",
    "title": "Hot Buttered Soul",
    "release_date": "1969-06-01",
    "genre": "Soul / Symphonic Soul",
    "tags": [
      "stax",
      "orchestral",
      "long-form"
    ],
    "mood": "hypnotic",
    "curator_note": "Four tracks in 45 minutes, including a twelve-minute 'Walk On By' that stretches a pop single into velvet-draped orchestral obsession."
  },
  {
    "artist": "Curtis Mayfield",
    "title": "Curtis",
    "release_date": "1970-09-01",
    "genre": "Soul / Funk",
    "tags": [
      "chicago",
      "protest",
      "falsetto"
    ],
    "mood": "cinematic",
    "curator_note": "Fresh out of the Impressions, Mayfield opens his solo career with '(Don't Worry) If There's a Hell Below' — a bongo-driven sermon that still sounds like a warning."
  },
  {
    "artist": "Marvin Gaye",
    "title": "What's Going On",
    "release_date": "1971-05-21",
    "genre": "Soul / Progressive Soul",
    "tags": [
      "motown",
      "protest",
      "concept album"
    ],
    "mood": "melancholic",
    "curator_note": "A Vietnam veteran's homecoming told in one continuous suite, sung so gently that Motown's boss thought it would end Gaye's career."
  },
  {
    "artist": "Funkadelic",
    "title": "Maggot Brain",
    "release_date": "1971-07-12",
    "genre": "Funk / Psychedelic Rock",
    "tags": [
      "p-funk",
      "guitar",
      "psychedelic"
    ],
    "mood": "raw",
    "curator_note": "George Clinton told Eddie Hazel to play like his mother had just died, and the ten-minute title solo is the sound of him believing it."
  },
  {
    "artist": "Sly and the Family Stone",
    "title": "There's a Riot Goin' On",
    "release_date": "1971-11-01",
    "genre": "Funk / Soul",
    "tags": [
      "drum machine",
      "lo-fi",
      "dark"
    ],
    "mood": "hypnotic",
    "curator_note": "Recorded in a haze of overdubs and erased tape, its murky drum-machine grooves turned the 60s' brightest optimist into funk's great insomniac."
  },
  {
    "artist": "Curtis Mayfield",
    "title": "Super Fly",
    "release_date": "1972-07-01",
    "genre": "Soul / Funk",
    "tags": [
      "soundtrack",
      "blaxploitation",
      "wah-wah"
    ],
    "mood": "cinematic",
    "curator_note": "A soundtrack that quietly indicts the film it scores, with 'Freddie's Dead' mourning the pusher the movie glamorizes."
  },
  {
    "artist": "Stevie Wonder",
    "title": "Innervisions",
    "release_date": "1973-08-03",
    "genre": "Soul / Funk",
    "tags": [
      "motown",
      "synthesizer",
      "clavinet"
    ],
    "mood": "energetic",
    "curator_note": "Wonder plays nearly every instrument himself, and the clavinet snarl of 'Higher Ground' arrived days before the car crash that nearly killed him."
  },
  {
    "artist": "Al Green",
    "title": "Call Me",
    "release_date": "1973-04-01",
    "genre": "Soul / Memphis Soul",
    "tags": [
      "hi records",
      "willie mitchell",
      "falsetto"
    ],
    "mood": "tender",
    "curator_note": "Willie Mitchell's cushioned Hi Rhythm grooves give Green room to slide from a whisper to a cry, sometimes within a single syllable."
  },
  {
    "artist": "James Brown",
    "title": "The Payback",
    "release_date": "1973-12-13",
    "genre": "Funk / Soul",
    "tags": [
      "jbs",
      "groove",
      "sampled"
    ],
    "mood": "raw",
    "curator_note": "Rejected as a film score for not being funky enough, its simmering seven-minute vamps became the most sampled revenge in hip-hop history."
  },
  {
    "artist": "Earth, Wind & Fire",
    "title": "That's the Way of the World",
    "release_date": "1975-03-15",
    "genre": "Funk / Soul",
    "tags": [
      "horns",
      "kalimba",
      "70s"
    ],
    "mood": "euphoric",
    "curator_note": "Maurice White's kalimba and Philip Bailey's stratospheric falsetto make 'Shining Star' and 'Reasons' feel like sunlight with a horn chart."
  },
  {
    "artist": "Parliament",
    "title": "Mothership Connection",
    "release_date": "1975-12-15",
    "genre": "Funk / P-Funk",
    "tags": [
      "p-funk",
      "afrofuturism",
      "horns"
    ],
    "mood": "energetic",
    "curator_note": "Clinton beams Black America into orbit on a chrome spaceship while Bootsy's bass and the Horny Horns keep one foot planted on the one."
  },
  {
    "artist": "Stevie Wonder",
    "title": "Songs in the Key of Life",
    "release_date": "1976-09-28",
    "genre": "Soul / Funk",
    "tags": [
      "double album",
      "motown",
      "70s"
    ],
    "mood": "euphoric",
    "curator_note": "A double album plus bonus EP where 'Sir Duke,' 'As,' and 'Isn't She Lovely' spill out like a man who simply could not stop writing."
  },
  {
    "artist": "Funkadelic",
    "title": "One Nation Under a Groove",
    "release_date": "1978-09-22",
    "genre": "Funk / P-Funk",
    "tags": [
      "p-funk",
      "anthem",
      "dance"
    ],
    "mood": "energetic",
    "curator_note": "The title track is a constitutional convention held on a dancefloor, ratifying funk as a civic duty for seven and a half minutes."
  },
  {
    "artist": "Chic",
    "title": "C'est Chic",
    "release_date": "1978-11-01",
    "genre": "Disco / Funk",
    "tags": [
      "nile rodgers",
      "studio 54",
      "strings"
    ],
    "mood": "energetic",
    "curator_note": "Born from being turned away at Studio 54, 'Le Freak' repays the insult with the tightest rhythm-guitar chank ever pressed to vinyl."
  },
  {
    "artist": "Donna Summer",
    "title": "Bad Girls",
    "release_date": "1979-04-25",
    "genre": "Disco / R&B",
    "tags": [
      "moroder",
      "double album",
      "disco queen"
    ],
    "mood": "euphoric",
    "curator_note": "Summer and Moroder close the disco decade with 'Hot Stuff' borrowing rock guitar and the title track's toot-toot whistle patrolling the boulevard."
  },
  {
    "artist": "Michael Jackson",
    "title": "Off the Wall",
    "release_date": "1979-08-10",
    "genre": "Disco / Soul",
    "tags": [
      "quincy jones",
      "dancefloor",
      "post-motown"
    ],
    "mood": "euphoric",
    "curator_note": "Twenty-year-old Jackson meets Quincy Jones and 'Don't Stop 'Til You Get Enough' opens with a giggle before igniting the greatest disco lift-off on record."
  },
  {
    "artist": "Rick James",
    "title": "Street Songs",
    "release_date": "1981-04-07",
    "genre": "Funk / R&B",
    "tags": [
      "punk funk",
      "motown",
      "80s"
    ],
    "mood": "energetic",
    "curator_note": "'Give It to Me Baby' and 'Super Freak' strut through Motown's last great funk record with a bassline so sticky MC Hammer built a career on it."
  },
  {
    "artist": "Luther Vandross",
    "title": "Never Too Much",
    "release_date": "1981-08-12",
    "genre": "Soul / R&B",
    "tags": [
      "quiet storm",
      "80s",
      "vocals"
    ],
    "mood": "tender",
    "curator_note": "A session singer steps to the front and turns 'A House Is Not a Home' into a seven-minute study in how long you can hold heartbreak in mid-air."
  },
  {
    "artist": "Prince",
    "title": "1999",
    "release_date": "1982-10-27",
    "genre": "Funk / Synth-Pop",
    "tags": [
      "minneapolis sound",
      "linn drum",
      "double album"
    ],
    "mood": "hypnotic",
    "curator_note": "Prince parties at the apocalypse with a Linn drum machine, and 'Little Red Corvette' proves the Minneapolis sound could outrun anything on the radio."
  },
  {
    "artist": "João Gilberto",
    "title": "Chega de Saudade",
    "release_date": "1959-03-01",
    "genre": "Bossa Nova / Samba",
    "tags": [
      "bossa nova",
      "brazil",
      "guitar",
      "1950s"
    ],
    "mood": "tender",
    "curator_note": "The whispered voice-and-guitar blueprint that shrank samba down to an apartment-sized murmur and invented bossa nova in the process."
  },
  {
    "artist": "Elis Regina & Antônio Carlos Jobim",
    "title": "Elis & Tom",
    "release_date": "1974-01-01",
    "genre": "Bossa Nova / MPB",
    "tags": [
      "bossa nova",
      "mpb",
      "duets"
    ],
    "mood": "euphoric",
    "curator_note": "Elis giggles mid-take on 'Águas de Março' and the engineers wisely left it in, capturing the warmest duet Brazilian music ever taped."
  },
  {
    "artist": "Héctor Lavoe",
    "title": "La Voz",
    "release_date": "1975-01-01",
    "genre": "Salsa / Latin",
    "tags": [
      "salsa",
      "fania",
      "sonero"
    ],
    "mood": "energetic",
    "curator_note": "Lavoe's first record without Willie Colón's name up top proves the sonero from Ponce could carry an entire orchestra on phrasing alone."
  },
  {
    "artist": "Héctor Lavoe",
    "title": "Comedia",
    "release_date": "1978-01-01",
    "genre": "Salsa / Latin",
    "tags": [
      "salsa",
      "fania",
      "el cantante"
    ],
    "mood": "melancholic",
    "curator_note": "Rubén Blades wrote 'El Cantante' for himself, handed it to Lavoe, and accidentally scripted the singer's own tragedy in real time."
  },
  {
    "artist": "Willie Colón & Rubén Blades",
    "title": "Siembra",
    "release_date": "1978-10-01",
    "genre": "Salsa / Latin",
    "tags": [
      "salsa",
      "fania",
      "storytelling"
    ],
    "mood": "cinematic",
    "curator_note": "'Pedro Navaja' stretched a barrio crime story past seven minutes and still became the biggest-selling record Fania ever pressed."
  },
  {
    "artist": "Celia Cruz & Johnny Pacheco",
    "title": "Celia & Johnny",
    "release_date": "1974-01-01",
    "genre": "Salsa / Guaracha",
    "tags": [
      "salsa",
      "cuba",
      "fania",
      "1970s"
    ],
    "mood": "euphoric",
    "curator_note": "'Quimbara' opens at a rumba sprint that crowned a Cuban exile in her forties the undisputed queen of a genre built by kids in New York."
  },
  {
    "artist": "Eddie Palmieri",
    "title": "The Sun of Latin Music",
    "release_date": "1974-01-01",
    "genre": "Salsa / Latin Jazz",
    "tags": [
      "salsa",
      "latin jazz",
      "piano"
    ],
    "mood": "hypnotic",
    "curator_note": "The first Latin album to win a Grammy, with teenage vocalist Lalo Rodríguez riding out Palmieri's dissonant piano storms."
  },
  {
    "artist": "Daddy Yankee",
    "title": "Barrio Fino",
    "release_date": "2004-07-13",
    "genre": "Reggaeton / Latin Urban",
    "tags": [
      "reggaeton",
      "puerto rico",
      "gasolina"
    ],
    "mood": "energetic",
    "curator_note": "'Gasolina' detonated out of the Villa Kennedy housing projects and made reggaeton a worldwide export in under three minutes."
  },
  {
    "artist": "Tego Calderón",
    "title": "El Abayarde",
    "release_date": "2002-11-01",
    "genre": "Reggaeton / Hip-Hop",
    "tags": [
      "reggaeton",
      "bomba",
      "afro-boricua"
    ],
    "mood": "raw",
    "curator_note": "Tego's gravel drawl over bomba and plena drums dragged Afro-Puerto Rican pride to the center of a scene obsessed with dembow."
  },
  {
    "artist": "Don Omar",
    "title": "The Last Don",
    "release_date": "2003-06-01",
    "genre": "Reggaeton / Latin Urban",
    "tags": [
      "reggaeton",
      "debut",
      "puerto rico"
    ],
    "mood": "cinematic",
    "curator_note": "Street sermons and club anthems sequenced like a mob film, and 'Dile' still empties no dance floor twenty years on."
  },
  {
    "artist": "Wisin & Yandel",
    "title": "Pa'l Mundo",
    "release_date": "2005-11-01",
    "genre": "Reggaeton / Latin Pop",
    "tags": [
      "reggaeton",
      "duo",
      "luny tunes"
    ],
    "mood": "energetic",
    "curator_note": "'Rakata' and 'Llamé Pa' Verte' run the duo's stadium-scale hooks through Luny Tunes beats polished like chrome."
  },
  {
    "artist": "Ivy Queen",
    "title": "Diva",
    "release_date": "2003-01-01",
    "genre": "Reggaeton / Latin Urban",
    "tags": [
      "reggaeton",
      "women",
      "perreo"
    ],
    "mood": "raw",
    "curator_note": "Ivy Queen's nasal battle cry on 'Quiero Bailar' drew a consent line on the perreo floor that the whole genre had to reckon with."
  },
  {
    "artist": "Bad Bunny",
    "title": "X 100pre",
    "release_date": "2018-12-24",
    "genre": "Latin Trap / Reggaeton",
    "tags": [
      "latin trap",
      "puerto rico",
      "debut"
    ],
    "mood": "melancholic",
    "curator_note": "Dropped on Nochebuena with pop-punk guitars and dembow sharing one tracklist, it is the sound of Benito refusing every rule of a Latin trap debut."
  },
  {
    "artist": "Bad Bunny",
    "title": "Un Verano Sin Ti",
    "release_date": "2022-05-06",
    "genre": "Reggaeton / Latin Pop",
    "tags": [
      "reggaeton",
      "summer",
      "heartbreak"
    ],
    "mood": "euphoric",
    "curator_note": "A beach-house record about heartbreak that spent more weeks atop the Billboard 200 than any Spanish-language album before it."
  },
  {
    "artist": "Rosalía",
    "title": "El Mal Querer",
    "release_date": "2018-11-02",
    "genre": "Flamenco / Latin Pop",
    "tags": [
      "flamenco",
      "spain",
      "concept album"
    ],
    "mood": "cinematic",
    "curator_note": "Her college thesis project scores a 13th-century novel of jealous love with palmas, motorbike revs, and flamenco melisma."
  },
  {
    "artist": "Rosalía",
    "title": "Motomami",
    "release_date": "2022-03-18",
    "genre": "Latin Pop / Reggaeton",
    "tags": [
      "experimental",
      "reggaeton",
      "spain"
    ],
    "mood": "raw",
    "curator_note": "Butterfly-fragile ballads collide with distorted reggaeton; the swerve from 'Hentai' into 'Bizcochito' is the sequencing whiplash of the decade."
  },
  {
    "artist": "J Balvin",
    "title": "Vibras",
    "release_date": "2018-05-25",
    "genre": "Reggaeton / Latin Pop",
    "tags": [
      "reggaeton",
      "colombia",
      "pop"
    ],
    "mood": "hypnotic",
    "curator_note": "Pastel visuals and the global run of 'Mi Gente' made Medellín's softest-voiced star reggaeton's ambassador to the pop mainstream."
  },
  {
    "artist": "Anuel AA",
    "title": "Real Hasta la Muerte",
    "release_date": "2018-07-17",
    "genre": "Latin Trap / Reggaeton",
    "tags": [
      "latin trap",
      "puerto rico",
      "prison"
    ],
    "mood": "raw",
    "curator_note": "Recorded before his sentence and released the day Anuel walked free, its Auto-Tuned menace fixed the first canon of Latin trap."
  },
  {
    "artist": "Los Tigres del Norte",
    "title": "Jefe de Jefes",
    "release_date": "1997-01-01",
    "genre": "Norteño / Corridos",
    "tags": [
      "corridos",
      "norteño",
      "double album"
    ],
    "mood": "cinematic",
    "curator_note": "A sprawling double album of border ballads whose title corrido became the unofficial anthem of both sides of the drug war."
  },
  {
    "artist": "Peso Pluma",
    "title": "Génesis",
    "release_date": "2023-06-22",
    "genre": "Corridos Tumbados / Regional Mexican",
    "tags": [
      "corridos tumbados",
      "mexico",
      "sierreño"
    ],
    "mood": "energetic",
    "curator_note": "Peso's raspy bark over requinto and charchetas carried corridos tumbados to a Coachella stage and a top-three Billboard debut."
  },
  {
    "artist": "Natanael Cano",
    "title": "Corridos Tumbados",
    "release_date": "2019-11-01",
    "genre": "Corridos Tumbados / Latin Trap",
    "tags": [
      "corridos tumbados",
      "mexico",
      "trap"
    ],
    "mood": "raw",
    "curator_note": "A teenager from Hermosillo welded trap cadences onto acoustic requintos and named an entire movement with the album title."
  },
  {
    "artist": "Tatsuro Yamashita",
    "title": "For You",
    "release_date": "1982-01-21",
    "genre": "City Pop / Funk",
    "tags": [
      "city pop",
      "japan",
      "80s",
      "summer"
    ],
    "mood": "euphoric",
    "curator_note": "The strummed guitar intro of 'Sparkle' alone launched a thousand beach-drive playlists, and the rest of the record keeps that top-down glide going."
  },
  {
    "artist": "Tatsuro Yamashita",
    "title": "Ride on Time",
    "release_date": "1980-09-19",
    "genre": "City Pop / Soul",
    "tags": [
      "city pop",
      "japan",
      "80s"
    ],
    "mood": "energetic",
    "curator_note": "The title cut began as a cassette-deck commercial jingle and ended up the moment Yamashita's falsetto turned Tokyo studio-pop into a national obsession."
  },
  {
    "artist": "Mariya Takeuchi",
    "title": "Variety",
    "release_date": "1984-04-25",
    "genre": "City Pop / Pop",
    "tags": [
      "city pop",
      "japan",
      "80s",
      "plastic love"
    ],
    "mood": "melancholic",
    "curator_note": "Home to 'Plastic Love,' the bittersweet disco lament that sat quietly for three decades before a recommendation algorithm made it the internet's favorite Japanese song."
  },
  {
    "artist": "Taeko Onuki",
    "title": "Sunshower",
    "release_date": "1977-07-25",
    "genre": "City Pop / Jazz-Funk",
    "tags": [
      "city pop",
      "japan",
      "70s",
      "jazz"
    ],
    "mood": "tender",
    "curator_note": "With a young Ryuichi Sakamoto arranging, Onuki floats cool jazz chords over humid grooves like an air-conditioned room in a Tokyo heatwave."
  },
  {
    "artist": "Eiichi Ohtaki",
    "title": "A Long Vacation",
    "release_date": "1981-03-21",
    "genre": "City Pop / Pop",
    "tags": [
      "city pop",
      "japan",
      "80s",
      "niagara"
    ],
    "mood": "cinematic",
    "curator_note": "Ohtaki's Wall of Sound fantasy of endless resort summers, wrapped in that pastel poolside cover art that became city pop's unofficial flag."
  },
  {
    "artist": "Anri",
    "title": "Timely!!",
    "release_date": "1983-12-05",
    "genre": "City Pop / Funk",
    "tags": [
      "city pop",
      "japan",
      "80s"
    ],
    "mood": "hypnotic",
    "curator_note": "Toshiki Kadomatsu's slap-bass production and Anri's cool-headed vocals make 'Remember Summer Days' feel like nostalgia for a vacation you never actually took."
  },
  {
    "artist": "Utada Hikaru",
    "title": "First Love",
    "release_date": "1999-03-10",
    "genre": "J-Pop / R&B",
    "tags": [
      "j-pop",
      "japan",
      "90s",
      "r&b"
    ],
    "mood": "tender",
    "curator_note": "Written by a bilingual sixteen-year-old, it fused New York R&B with Japanese balladry and became the best-selling album in Japanese history almost overnight."
  },
  {
    "artist": "Utada Hikaru",
    "title": "Deep River",
    "release_date": "2002-06-19",
    "genre": "J-Pop / R&B",
    "tags": [
      "j-pop",
      "japan",
      "2000s"
    ],
    "mood": "melancholic",
    "curator_note": "'Hikari' and 'Sakura Drops' show Utada trading teenage precocity for a grown, aching restraint that half of J-pop spent the next decade chasing."
  },
  {
    "artist": "Sheena Ringo",
    "title": "Muzai Moratorium",
    "release_date": "1999-02-24",
    "genre": "J-Pop / Alternative Rock",
    "tags": [
      "j-pop",
      "japan",
      "90s",
      "rock"
    ],
    "mood": "raw",
    "curator_note": "A debut that snarls in jazz chords and rolled r's, announcing a 20-year-old who treated the J-pop chart like her personal cabaret stage."
  },
  {
    "artist": "Sheena Ringo",
    "title": "Shoso Strip",
    "release_date": "2000-03-31",
    "genre": "J-Pop / Art Rock",
    "tags": [
      "j-pop",
      "japan",
      "2000s",
      "rock"
    ],
    "mood": "energetic",
    "curator_note": "The one where 'Honno' arrived with a nurse kicking through plate glass, and the music somehow matched the image note for note."
  },
  {
    "artist": "Namie Amuro",
    "title": "Sweet 19 Blues",
    "release_date": "1996-07-22",
    "genre": "J-Pop / Dance",
    "tags": [
      "j-pop",
      "japan",
      "90s",
      "dance"
    ],
    "mood": "hypnotic",
    "curator_note": "Tetsuya Komuro's Eurobeat machinery meets an Okinawan teenager's cool detachment, and mid-90s Japan bought over three million copies of the result."
  },
  {
    "artist": "Ayumi Hamasaki",
    "title": "Duty",
    "release_date": "2000-09-27",
    "genre": "J-Pop / Dance",
    "tags": [
      "j-pop",
      "japan",
      "2000s"
    ],
    "mood": "cinematic",
    "curator_note": "Millennial dread rendered in trance synths and self-written lyrics, with the empress of Avex staring down her own fame on 'M'."
  },
  {
    "artist": "Perfume",
    "title": "GAME",
    "release_date": "2008-04-16",
    "genre": "J-Pop / Electro",
    "tags": [
      "j-pop",
      "japan",
      "electro",
      "technopop"
    ],
    "mood": "energetic",
    "curator_note": "Yasutaka Nakata vocoders three Hiroshima girls into gleaming chrome and takes technopop back to number one on Oricon for the first time since YMO."
  },
  {
    "artist": "Mr. Children",
    "title": "Atomic Heart",
    "release_date": "1994-09-01",
    "genre": "J-Pop / Rock",
    "tags": [
      "j-pop",
      "japan",
      "90s",
      "rock"
    ],
    "mood": "euphoric",
    "curator_note": "'Cross Road' and 'Innocent World' on the same record is why an entire Japanese generation learned these choruses by heart."
  },
  {
    "artist": "Seo Taiji and Boys",
    "title": "Seo Taiji and Boys",
    "release_date": "1992-03-23",
    "genre": "K-Pop / New Jack Swing",
    "tags": [
      "k-pop",
      "korea",
      "90s",
      "hip-hop"
    ],
    "mood": "raw",
    "curator_note": "Panned by TV judges on debut night, 'Nan Arayo' then sat at number one for 17 weeks and effectively invented the industry we now call K-pop."
  },
  {
    "artist": "BTS",
    "title": "Love Yourself: Tear",
    "release_date": "2018-05-18",
    "genre": "K-Pop / Hip-Hop",
    "tags": [
      "k-pop",
      "korea",
      "2010s"
    ],
    "mood": "melancholic",
    "curator_note": "The first Korean-language album to top the Billboard 200, built around 'Fake Love' and the ache of performing a self you no longer recognize."
  },
  {
    "artist": "BTS",
    "title": "Map of the Soul: 7",
    "release_date": "2020-02-21",
    "genre": "K-Pop / Pop",
    "tags": [
      "k-pop",
      "korea",
      "2020s"
    ],
    "mood": "cinematic",
    "curator_note": "Seven years into stadium fame, they filter Jungian shadow-work through 'Black Swan' and an interlude that samples their own rookie selves."
  },
  {
    "artist": "NewJeans",
    "title": "Get Up",
    "release_date": "2023-07-21",
    "genre": "K-Pop / Jersey Club",
    "tags": [
      "k-pop",
      "korea",
      "2020s",
      "jersey club"
    ],
    "mood": "euphoric",
    "curator_note": "Twelve minutes of Jersey club bounce and whispered hooks that landed atop the Billboard 200 and made every other agency rethink its playbook."
  },
  {
    "artist": "BLACKPINK",
    "title": "The Album",
    "release_date": "2020-10-02",
    "genre": "K-Pop / Pop",
    "tags": [
      "k-pop",
      "korea",
      "2020s"
    ],
    "mood": "energetic",
    "curator_note": "Eight tracks of pure detonation, from the war-drum drop of 'How You Like That' to a campfire singalong disguised as 'Lovesick Girls'."
  },
  {
    "artist": "f(x)",
    "title": "Pink Tape",
    "release_date": "2013-07-29",
    "genre": "K-Pop / Electropop",
    "tags": [
      "k-pop",
      "korea",
      "2010s",
      "electropop"
    ],
    "mood": "hypnotic",
    "curator_note": "'Rum Pum Pum Pum' compares first love to a wisdom tooth, which tells you everything about the strangest, most adored album SM ever released."
  },
  {
    "artist": "Red Velvet",
    "title": "Perfect Velvet",
    "release_date": "2017-11-17",
    "genre": "K-Pop / R&B",
    "tags": [
      "k-pop",
      "korea",
      "2010s",
      "r&b"
    ],
    "mood": "hypnotic",
    "curator_note": "'Peek-A-Boo' turns a slasher-film premise into slinky funk, anchoring the 'velvet' side of the group's split personality at its darkest and best."
  },
  {
    "artist": "Girls' Generation",
    "title": "I Got a Boy",
    "release_date": "2013-01-01",
    "genre": "K-Pop / Dance-Pop",
    "tags": [
      "k-pop",
      "korea",
      "2010s",
      "dance-pop"
    ],
    "mood": "energetic",
    "curator_note": "The title track lurches through nine tempo and style changes in under five minutes, a Frankenstein single that critics still argue about a decade later."
  },
  {
    "artist": "Massive Attack",
    "title": "Blue Lines",
    "release_date": "1991-04-08",
    "genre": "Trip-Hop / Downtempo",
    "tags": [
      "trip-hop",
      "bristol",
      "soul",
      "90s"
    ],
    "mood": "hypnotic",
    "curator_note": "Bristol's Wild Bunch slow the breakbeat to walking pace and let Shara Nelson's 'Unfinished Sympathy' float over it like a hymn for night buses."
  },
  {
    "artist": "Massive Attack",
    "title": "Mezzanine",
    "release_date": "1998-04-20",
    "genre": "Trip-Hop / Electronic",
    "tags": [
      "trip-hop",
      "dark",
      "bristol"
    ],
    "mood": "cinematic",
    "curator_note": "Paranoid basslines and Liz Fraser's ghost-voice on 'Teardrop' turn the band's velvet soul into something that watches you from the shadows."
  },
  {
    "artist": "Portishead",
    "title": "Dummy",
    "release_date": "1994-08-22",
    "genre": "Trip-Hop / Downtempo",
    "tags": [
      "trip-hop",
      "bristol",
      "mercury-prize"
    ],
    "mood": "melancholic",
    "curator_note": "Beth Gibbons sings like a torch singer trapped in a spy film while Geoff Barrow scratches vinyl crackle into every wound."
  },
  {
    "artist": "Portishead",
    "title": "Third",
    "release_date": "2008-04-28",
    "genre": "Trip-Hop / Experimental",
    "tags": [
      "trip-hop",
      "krautrock",
      "comeback"
    ],
    "mood": "raw",
    "curator_note": "Eleven years of silence broken by ukulele dread, motorik drums, and 'Machine Gun' firing snares like an air-raid siren."
  },
  {
    "artist": "Tricky",
    "title": "Maxinquaye",
    "release_date": "1995-02-20",
    "genre": "Trip-Hop / Alternative",
    "tags": [
      "trip-hop",
      "bristol",
      "90s"
    ],
    "mood": "hypnotic",
    "curator_note": "Tricky whispers through smoke while Martina Topley-Bird carries his lines like secrets, on a record named for the mother he barely knew."
  },
  {
    "artist": "Roni Size / Reprazent",
    "title": "New Forms",
    "release_date": "1997-06-23",
    "genre": "Drum & Bass / Jazz",
    "tags": [
      "drum-and-bass",
      "jungle",
      "mercury-prize",
      "bristol"
    ],
    "mood": "energetic",
    "curator_note": "A live double bass sprints alongside chopped Amen breaks, and 'Brown Paper Bag' snatched the Mercury Prize from Radiohead's hands."
  },
  {
    "artist": "A Guy Called Gerald",
    "title": "Black Secret Technology",
    "release_date": "1995-03-01",
    "genre": "Jungle / Electronic",
    "tags": [
      "jungle",
      "manchester",
      "90s"
    ],
    "mood": "hypnotic",
    "curator_note": "The 'Voodoo Ray' architect rebuilds jungle as afrofuturist science, layering breaks until they shimmer like heat off tarmac."
  },
  {
    "artist": "Craig David",
    "title": "Born to Do It",
    "release_date": "2000-08-14",
    "genre": "UK Garage / R&B",
    "tags": [
      "uk-garage",
      "r&b",
      "2step"
    ],
    "mood": "tender",
    "curator_note": "A Southampton teenager counts the days of the week over Artful Dodger shuffle and makes 2-step sound like a first crush."
  },
  {
    "artist": "The Streets",
    "title": "Original Pirate Material",
    "release_date": "2002-03-25",
    "genre": "UK Garage / Hip-Hop",
    "tags": [
      "uk-garage",
      "brit-rap",
      "birmingham"
    ],
    "mood": "raw",
    "curator_note": "Mike Skinner narrates lager, PlayStations, and heartbreak in a flat Brummie deadpan over garage beats built in a wardrobe."
  },
  {
    "artist": "MJ Cole",
    "title": "Sincere",
    "release_date": "2000-08-07",
    "genre": "UK Garage / 2-Step",
    "tags": [
      "uk-garage",
      "2step",
      "mercury-nominated"
    ],
    "mood": "euphoric",
    "curator_note": "A classically trained oboist gives 2-step its finishing-school polish, all glassy chords and snares that snap like cufflinks."
  },
  {
    "artist": "Dizzee Rascal",
    "title": "Boy in da Corner",
    "release_date": "2003-07-21",
    "genre": "Grime / Hip-Hop",
    "tags": [
      "grime",
      "east-london",
      "mercury-prize"
    ],
    "mood": "raw",
    "curator_note": "An 18-year-old from Bow squawks over sinogrime bleeps and PlayStation bass, sounding simultaneously terrified and untouchable."
  },
  {
    "artist": "Wiley",
    "title": "Treddin' on Thin Ice",
    "release_date": "2004-04-19",
    "genre": "Grime / Electronic",
    "tags": [
      "grime",
      "eskibeat",
      "east-london"
    ],
    "mood": "hypnotic",
    "curator_note": "The godfather of grime freezes garage into Eskibeat, all icy square-wave stabs and a fixation with cold that named a whole sound."
  },
  {
    "artist": "Kano",
    "title": "Home Sweet Home",
    "release_date": "2005-06-27",
    "genre": "Grime / Hip-Hop",
    "tags": [
      "grime",
      "east-london",
      "00s"
    ],
    "mood": "energetic",
    "curator_note": "East Ham's smoothest technician glides between grime tempo and rap introspection, making 'P's and Q's' a pirate-radio national anthem."
  },
  {
    "artist": "Skepta",
    "title": "Konnichiwa",
    "release_date": "2016-05-06",
    "genre": "Grime / Hip-Hop",
    "tags": [
      "grime",
      "tottenham",
      "mercury-prize"
    ],
    "mood": "energetic",
    "curator_note": "Tracksuits over red carpets: Skepta strips grime back to bare 140bpm menace and drags it to the Mercury podium on his own label."
  },
  {
    "artist": "Stormzy",
    "title": "Gang Signs & Prayer",
    "release_date": "2017-02-24",
    "genre": "Grime / Gospel",
    "tags": [
      "grime",
      "gospel",
      "south-london"
    ],
    "mood": "cinematic",
    "curator_note": "The first grime album to top the UK chart swings between 'Big for Your Boots' war cries and gospel choirs mid-sermon."
  },
  {
    "artist": "Ghetts",
    "title": "Conflict of Interest",
    "release_date": "2021-02-19",
    "genre": "Grime / UK Rap",
    "tags": [
      "grime",
      "uk-rap",
      "east-london"
    ],
    "mood": "cinematic",
    "curator_note": "Two decades of pirate-radio scars distilled into orchestral confessionals, with a flow that still corners like a stolen moped."
  },
  {
    "artist": "Dave",
    "title": "Psychodrama",
    "release_date": "2019-03-08",
    "genre": "UK Rap / Drill",
    "tags": [
      "uk-rap",
      "drill",
      "mercury-prize"
    ],
    "mood": "melancholic",
    "curator_note": "Framed as a therapy session, it moves from piano-led grief to the eleven-minute 'Lesley', a domestic-abuse story told with surgical patience."
  },
  {
    "artist": "Headie One",
    "title": "Edna",
    "release_date": "2020-10-09",
    "genre": "UK Drill / Rap",
    "tags": [
      "uk-drill",
      "tottenham",
      "2020s"
    ],
    "mood": "raw",
    "curator_note": "Named for his late mother, Tottenham's drill figurehead slides mournful melody over gliding 808s and took the sound to number one."
  },
  {
    "artist": "Central Cee",
    "title": "23",
    "release_date": "2022-02-25",
    "genre": "UK Drill / Rap",
    "tags": [
      "uk-drill",
      "west-london",
      "2020s"
    ],
    "mood": "energetic",
    "curator_note": "West London's sharpest export raps balance-sheet honesty over sample-flipping drill, turning 'Retail Therapy' hooks into export-grade UK slang."
  }
];

export const EXPANSION2: Release[] = ENTRIES.map((e, i) => ({
  id: `exp2-${String(i).padStart(3, "0")}`,
  artist: e.artist,
  title: e.title,
  type: "album",
  artwork_url: `/api/artwork?artist=${enc(e.artist)}&title=${enc(e.title)}`,
  release_date: e.release_date,
  genre: e.genre,
  tags: e.tags,
  mood: e.mood,
  ...links(e.artist, e.title),
  created_at: e.release_date + "T00:00:00Z",
  curator_note: e.curator_note,
}));
