/**
 * Pulsar — Expanded Catalog: 1990s → today
 * 155 canonical albums across hip-hop, R&B, rock, grunge,
 * shoegaze, electronic, indie, pop, amapiano/afrobeats and more.
 *
 * Artwork resolves through /api/artwork — the iTunes official-cover
 * proxy with strict artist+title matching — so every tile shows the
 * album's REAL cover (or a letter tile, never someone else's art).
 * Generated by a multi-agent generate→verify workflow.
 */

import type { Release } from "./types";

const enc = encodeURIComponent;

const links = (artist: string, title: string) => {
  const q = `${artist} ${title}`;
  return {
    spotify: `https://open.spotify.com/search/${enc(q)}`,
    apple_music: `https://music.apple.com/search?term=${enc(q)}`,
    tidal: `https://tidal.com/search?q=${enc(q)}`,
    soundcloud: `https://soundcloud.com/search?q=${enc(q)}`,
    youtube_music: `https://music.youtube.com/search?q=${enc(q)}`,
  };
};

interface Entry {
  artist: string;
  title: string;
  release_date: string;
  genre: string | null;
  tags: string[];
  mood: Release["mood"];
  curator_note: string | null;
}

const ENTRIES: Entry[] = [
  {
    "artist": "Nas",
    "title": "Illmatic",
    "release_date": "1994-04-19",
    "genre": "Hip-Hop / East Coast",
    "tags": [
      "queensbridge",
      "boom-bap",
      "lyricism"
    ],
    "mood": "cinematic",
    "curator_note": "Ten tracks of Queensbridge stairwell reportage where a twenty-year-old writes like the projects' court stenographer over beats from every great producer of the era."
  },
  {
    "artist": "The Notorious B.I.G.",
    "title": "Ready to Die",
    "release_date": "1994-09-13",
    "genre": "Hip-Hop / East Coast",
    "tags": [
      "brooklyn",
      "storytelling",
      "bad boy"
    ],
    "mood": "raw",
    "curator_note": "Biggie narrates his own birth, robberies, and imagined death with a flow so conversational it feels like he is sitting on the stoop next to you."
  },
  {
    "artist": "Wu-Tang Clan",
    "title": "Enter the Wu-Tang (36 Chambers)",
    "release_date": "1993-11-09",
    "genre": "Hip-Hop / Hardcore",
    "tags": [
      "staten island",
      "kung-fu",
      "rza"
    ],
    "mood": "raw",
    "curator_note": "Nine voices crowd a basement of dusty soul loops and kung-fu dialogue, sounding like a radio broadcast from a Staten Island that never existed on any map."
  },
  {
    "artist": "Dr. Dre",
    "title": "The Chronic",
    "release_date": "1992-12-15",
    "genre": "Hip-Hop / G-Funk",
    "tags": [
      "west coast",
      "g-funk",
      "synths"
    ],
    "mood": "hypnotic",
    "curator_note": "Whining Moog leads and low-rider bass turned Compton menace into sunshine funk, introducing a drawling unknown named Snoop along the way."
  },
  {
    "artist": "Snoop Doggy Dogg",
    "title": "Doggystyle",
    "release_date": "1993-11-23",
    "genre": "Hip-Hop / G-Funk",
    "tags": [
      "long beach",
      "g-funk",
      "death row"
    ],
    "mood": "hypnotic",
    "curator_note": "Snoop glides across Dre's liquid funk with the unhurried confidence of someone who knows every party in Long Beach will wait for him."
  },
  {
    "artist": "2Pac",
    "title": "All Eyez on Me",
    "release_date": "1996-02-13",
    "genre": "Hip-Hop / West Coast",
    "tags": [
      "double album",
      "death row",
      "west coast"
    ],
    "mood": "energetic",
    "curator_note": "Recorded in a post-prison sprint, two discs of paranoia and celebration collide as Pac raps like a man spending borrowed time as fast as he can."
  },
  {
    "artist": "A Tribe Called Quest",
    "title": "The Low End Theory",
    "release_date": "1991-09-24",
    "genre": "Hip-Hop / Jazz Rap",
    "tags": [
      "jazz rap",
      "native tongues",
      "queens"
    ],
    "mood": "hypnotic",
    "curator_note": "Ron Carter's upright bass walks beneath Q-Tip and Phife's tag-team verses, proving a rap record could swing as hard as it knocked."
  },
  {
    "artist": "OutKast",
    "title": "Aquemini",
    "release_date": "1998-09-29",
    "genre": "Hip-Hop / Southern",
    "tags": [
      "atlanta",
      "funk",
      "dungeon family"
    ],
    "mood": "cinematic",
    "curator_note": "Live horns, harmonica, and Southern-gothic storytelling stretch Atlanta rap into something that smells like red clay after a thunderstorm."
  },
  {
    "artist": "Mobb Deep",
    "title": "The Infamous",
    "release_date": "1995-04-25",
    "genre": "Hip-Hop / East Coast",
    "tags": [
      "queensbridge",
      "hardcore",
      "havoc"
    ],
    "mood": "melancholic",
    "curator_note": "Havoc's frostbitten piano loops score Prodigy's dead-eyed winter dispatches, a record that feels ten degrees colder than anything around it."
  },
  {
    "artist": "GZA",
    "title": "Liquid Swords",
    "release_date": "1995-11-07",
    "genre": "Hip-Hop / East Coast",
    "tags": [
      "wu-tang",
      "rza",
      "chess"
    ],
    "mood": "cinematic",
    "curator_note": "GZA moves through RZA's shogun-film soundscapes like a chess player narrating checkmate three moves before it happens."
  },
  {
    "artist": "Jay-Z",
    "title": "Reasonable Doubt",
    "release_date": "1996-06-25",
    "genre": "Hip-Hop / Mafioso Rap",
    "tags": [
      "brooklyn",
      "mafioso",
      "debut"
    ],
    "mood": "cinematic",
    "curator_note": "A hustler's ledger set to lush soul samples, delivered with the weary precision of someone itemizing exactly what the money cost him."
  },
  {
    "artist": "Missy Elliott",
    "title": "Supa Dupa Fly",
    "release_date": "1997-07-15",
    "genre": "Hip-Hop / R&B",
    "tags": [
      "timbaland",
      "virginia",
      "futurism"
    ],
    "mood": "energetic",
    "curator_note": "Missy and Timbaland fold beatbox stutters, cricket noises, and giggles into pop hits that sounded beamed in from five years ahead of schedule."
  },
  {
    "artist": "Lauryn Hill",
    "title": "The Miseducation of Lauryn Hill",
    "release_date": "1998-08-25",
    "genre": "R&B / Neo-Soul",
    "tags": [
      "neo-soul",
      "hip-hop",
      "grammy"
    ],
    "mood": "tender",
    "curator_note": "Classroom interludes stitch together doo-wop, reggae, and razor-sharp verses as Hill grades her own heartbreak in front of the whole world."
  },
  {
    "artist": "D'Angelo",
    "title": "Brown Sugar",
    "release_date": "1995-07-03",
    "genre": "R&B / Neo-Soul",
    "tags": [
      "neo-soul",
      "virginia",
      "smoky"
    ],
    "mood": "hypnotic",
    "curator_note": "A church-trained multi-instrumentalist slows Marvin Gaye's pulse to a smoky simmer and quietly launches an entire movement from behind a Rhodes."
  },
  {
    "artist": "Maxwell",
    "title": "Maxwell's Urban Hang Suite",
    "release_date": "1996-04-02",
    "genre": "R&B / Neo-Soul",
    "tags": [
      "neo-soul",
      "concept album",
      "romance"
    ],
    "mood": "tender",
    "curator_note": "A single romance traced from first glance to proposal, sung in a falsetto that hovers over the band like steam off a candlelit bath."
  },
  {
    "artist": "Erykah Badu",
    "title": "Baduizm",
    "release_date": "1997-02-11",
    "genre": "R&B / Neo-Soul",
    "tags": [
      "neo-soul",
      "dallas",
      "jazz"
    ],
    "mood": "hypnotic",
    "curator_note": "Badu drapes Billie Holiday phrasing over head-nod drums and incense-thick philosophy, making Dallas sound like the center of the soul universe."
  },
  {
    "artist": "TLC",
    "title": "CrazySexyCool",
    "release_date": "1994-11-15",
    "genre": "R&B / Hip-Hop Soul",
    "tags": [
      "atlanta",
      "girl group",
      "diamond-selling"
    ],
    "mood": "euphoric",
    "curator_note": "Three distinct personalities share one seamless groove, sliding from the slow-burn plea of 'Red Light Special' to the cautionary undertow of 'Waterfalls'."
  },
  {
    "artist": "Mary J. Blige",
    "title": "My Life",
    "release_date": "1994-11-29",
    "genre": "R&B / Hip-Hop Soul",
    "tags": [
      "hip-hop soul",
      "confessional",
      "samples"
    ],
    "mood": "melancholic",
    "curator_note": "Over Roy Ayers and Curtis Mayfield loops, Blige sings through depression in real time, and every crack in her voice lands like testimony."
  },
  {
    "artist": "IAM",
    "title": "L'École du micro d'argent",
    "release_date": "1997-03-18",
    "genre": "Hip-Hop / French Rap",
    "tags": [
      "marseille",
      "french rap",
      "wu-tang influence"
    ],
    "mood": "cinematic",
    "curator_note": "Marseille's answer to Wu-Tang wraps samurai imagery and immigrant-quarter chronicles in shadowy strings, and 'Demain c'est loin' still stands as French rap's Everest."
  },
  {
    "artist": "MC Solaar",
    "title": "Prose Combat",
    "release_date": "1994-02-21",
    "genre": "Hip-Hop / French Rap",
    "tags": [
      "paris",
      "french rap",
      "wordplay"
    ],
    "mood": "hypnotic",
    "curator_note": "Solaar bends the French language into triple-entendre origami over jazzy Parisian loops, rapping about death and desire with a poet's shrug."
  },
  {
    "artist": "Nirvana",
    "title": "Nevermind",
    "release_date": "1991-09-24",
    "genre": "Grunge / Alternative Rock",
    "tags": [
      "grunge",
      "seattle",
      "90s rock"
    ],
    "mood": "raw",
    "curator_note": "Butch Vig's polish turned Aberdeen scuzz into radio dynamite, and Smells Like Teen Spirit vaporized hair metal almost overnight."
  },
  {
    "artist": "Pearl Jam",
    "title": "Ten",
    "release_date": "1991-08-27",
    "genre": "Grunge / Rock",
    "tags": [
      "grunge",
      "seattle",
      "classic rock revival"
    ],
    "mood": "energetic",
    "curator_note": "Eddie Vedder's baritone surges over arena-sized riffs recorded before the band had ever set foot in an arena."
  },
  {
    "artist": "Soundgarden",
    "title": "Superunknown",
    "release_date": "1994-03-08",
    "genre": "Grunge / Alternative Metal",
    "tags": [
      "grunge",
      "heavy",
      "psychedelic"
    ],
    "mood": "melancholic",
    "curator_note": "Detuned guitars in odd time signatures made Black Hole Sun the loveliest nightmare on 1994 radio."
  },
  {
    "artist": "Alice in Chains",
    "title": "Dirt",
    "release_date": "1992-09-29",
    "genre": "Grunge / Alternative Metal",
    "tags": [
      "grunge",
      "sludge",
      "harmony vocals"
    ],
    "mood": "raw",
    "curator_note": "Layne Staley and Jerry Cantrell harmonize like a funeral choir over sludge-caked riffs that feel like slowly sinking."
  },
  {
    "artist": "My Bloody Valentine",
    "title": "Loveless",
    "release_date": "1991-11-04",
    "genre": "Shoegaze / Dream Pop",
    "tags": [
      "shoegaze",
      "noise pop",
      "creation records"
    ],
    "mood": "hypnotic",
    "curator_note": "Kevin Shields bent his tremolo arm until guitars melted into pink haze, nearly bankrupting Creation Records along the way."
  },
  {
    "artist": "Slowdive",
    "title": "Souvlaki",
    "release_date": "1993-06-01",
    "genre": "Shoegaze / Dream Pop",
    "tags": [
      "shoegaze",
      "dream pop",
      "reverb"
    ],
    "mood": "melancholic",
    "curator_note": "Made as the band was falling apart, When the Sun Hits buries a breakup under an avalanche of reverb."
  },
  {
    "artist": "Ride",
    "title": "Nowhere",
    "release_date": "1990-10-15",
    "genre": "Shoegaze / Neo-Psychedelia",
    "tags": [
      "shoegaze",
      "oxford",
      "wall of sound"
    ],
    "mood": "hypnotic",
    "curator_note": "Twin guitars swarm like weather systems while four Oxford art students harmonize about vapour trails from inside the storm."
  },
  {
    "artist": "Radiohead",
    "title": "OK Computer",
    "release_date": "1997-05-21",
    "genre": "Alternative / Art Rock",
    "tags": [
      "art rock",
      "dystopia",
      "britain"
    ],
    "mood": "cinematic",
    "curator_note": "Airbags, androids and a fitter-happier text-to-speech voice render millennial paranoia in Mellotron and dial-up static."
  },
  {
    "artist": "The Smashing Pumpkins",
    "title": "Siamese Dream",
    "release_date": "1993-07-27",
    "genre": "Alternative / Rock",
    "tags": [
      "alt rock",
      "fuzz",
      "chicago"
    ],
    "mood": "euphoric",
    "curator_note": "Billy Corgan stacked dozens of guitar tracks per song until Cherub Rock towered like a cathedral of fuzz."
  },
  {
    "artist": "Nine Inch Nails",
    "title": "The Downward Spiral",
    "release_date": "1994-03-08",
    "genre": "Industrial / Alternative Rock",
    "tags": [
      "industrial",
      "electronic rock",
      "concept album"
    ],
    "mood": "raw",
    "curator_note": "Recorded in the house at 10050 Cielo Drive, Reznor's machines grind with clinical menace toward the hushed devastation of Hurt."
  },
  {
    "artist": "R.E.M.",
    "title": "Automatic for the People",
    "release_date": "1992-10-05",
    "genre": "Rock / Alternative",
    "tags": [
      "alt rock",
      "athens georgia",
      "strings"
    ],
    "mood": "tender",
    "curator_note": "String arrangements by Led Zeppelin's John Paul Jones cradle Stipe's meditations on mortality, memory and Nightswimming."
  },
  {
    "artist": "Oasis",
    "title": "(What's the Story) Morning Glory?",
    "release_date": "1995-10-02",
    "genre": "Rock / Britpop",
    "tags": [
      "britpop",
      "manchester",
      "anthems"
    ],
    "mood": "euphoric",
    "curator_note": "Wonderwall and Champagne Supernova turned cosmic longing into pub singalongs without dropping an ounce of Manchester swagger."
  },
  {
    "artist": "Jeff Buckley",
    "title": "Grace",
    "release_date": "1994-08-23",
    "genre": "Rock / Alternative",
    "tags": [
      "singer-songwriter",
      "falsetto",
      "90s"
    ],
    "mood": "tender",
    "curator_note": "Buckley's four-octave leaps through Hallelujah and Lover, You Should've Come Over still sound impossibly weightless three decades on."
  },
  {
    "artist": "Sigur Rós",
    "title": "Ágætis byrjun",
    "release_date": "1999-06-12",
    "genre": "Post-Rock / Ambient",
    "tags": [
      "post-rock",
      "iceland",
      "bowed guitar"
    ],
    "mood": "cinematic",
    "curator_note": "Jónsi bows his electric guitar like a cello and sings in invented Hopelandic, making glaciers sound like lullabies."
  },
  {
    "artist": "Portishead",
    "title": "Dummy",
    "release_date": "1994-08-22",
    "genre": "Electronic / Trip-Hop",
    "tags": [
      "trip-hop",
      "bristol",
      "samples"
    ],
    "mood": "melancholic",
    "curator_note": "Beth Gibbons' torch-song quaver drifts over crackling spy-film samples, turning Bristol gloom into velvet."
  },
  {
    "artist": "Daft Punk",
    "title": "Homework",
    "release_date": "1997-01-20",
    "genre": "Electronic / French House",
    "tags": [
      "french house",
      "paris",
      "filter disco"
    ],
    "mood": "energetic",
    "curator_note": "Two Parisians in their early twenties ran filtered disco loops through Da Funk and rewired every dancefloor that followed."
  },
  {
    "artist": "Aphex Twin",
    "title": "Selected Ambient Works 85-92",
    "release_date": "1992-11-09",
    "genre": "Electronic / Ambient Techno",
    "tags": [
      "ambient techno",
      "cornwall",
      "tape hiss"
    ],
    "mood": "ambient",
    "curator_note": "Teenage tape experiments from Cornwall where warm bass pulses drift past like heavy machinery dreaming."
  },
  {
    "artist": "The Chemical Brothers",
    "title": "Dig Your Own Hole",
    "release_date": "1997-04-07",
    "genre": "Electronic / Big Beat",
    "tags": [
      "big beat",
      "breakbeat",
      "uk dance"
    ],
    "mood": "energetic",
    "curator_note": "Block Rockin' Beats lands like a breakbeat piledriver before The Private Psychedelic Reel dissolves everything into sitar bliss."
  },
  {
    "artist": "Boards of Canada",
    "title": "Music Has the Right to Children",
    "release_date": "1998-04-20",
    "genre": "Electronic / IDM",
    "tags": [
      "idm",
      "scotland",
      "nostalgia"
    ],
    "mood": "hypnotic",
    "curator_note": "Two Scottish brothers smear half-remembered educational-film synths across woozy hip-hop tempos until childhood nostalgia turns quietly eerie."
  },
  {
    "artist": "Björk",
    "title": "Homogenic",
    "release_date": "1997-09-20",
    "genre": "Electronic / Art Pop",
    "tags": [
      "art pop",
      "iceland",
      "strings and beats"
    ],
    "mood": "cinematic",
    "curator_note": "Volcanic programmed beats collide with an Icelandic string octet while Björk sings like tectonic plates falling in love."
  },
  {
    "artist": "OutKast",
    "title": "Stankonia",
    "release_date": "2000-10-31",
    "genre": "Hip-Hop / Southern Rap",
    "tags": [
      "atlanta",
      "funk",
      "southern"
    ],
    "mood": "energetic",
    "curator_note": "Atlanta funk cranked to drum-and-bass speed, where 'B.O.B.' sounds like a church revival caught in a wind tunnel."
  },
  {
    "artist": "OutKast",
    "title": "Speakerboxxx/The Love Below",
    "release_date": "2003-09-23",
    "genre": "Hip-Hop / Funk",
    "tags": [
      "double album",
      "atlanta",
      "diamond-certified"
    ],
    "mood": "euphoric",
    "curator_note": "Two solo albums stapled together like a friendly divorce, with Big Boi's bass sermons on one side and Andre crooning to jazz ghosts on the other."
  },
  {
    "artist": "Jay-Z",
    "title": "The Blueprint",
    "release_date": "2001-09-11",
    "genre": "Hip-Hop / East Coast",
    "tags": [
      "soul samples",
      "new york",
      "kanye production"
    ],
    "mood": "cinematic",
    "curator_note": "Sped-up Jackson 5 and Bobby Blue Bland samples give Jay a velvet throne to talk down to the entire industry from."
  },
  {
    "artist": "Eminem",
    "title": "The Marshall Mathers LP",
    "release_date": "2000-05-23",
    "genre": "Hip-Hop / Horrorcore",
    "tags": [
      "detroit",
      "controversial",
      "storytelling"
    ],
    "mood": "raw",
    "curator_note": "A tabloid nightmare narrated from inside the tabloid, where 'Stan' turns fan mail into a thunderstorm-soaked short film."
  },
  {
    "artist": "Kanye West",
    "title": "The College Dropout",
    "release_date": "2004-02-10",
    "genre": "Hip-Hop / Chipmunk Soul",
    "tags": [
      "chicago",
      "soul samples",
      "debut"
    ],
    "mood": "euphoric",
    "curator_note": "A producer in a pink polo pitch-shifts gospel choirs into helium and raps about retail jobs while his jaw is still wired shut."
  },
  {
    "artist": "50 Cent",
    "title": "Get Rich or Die Tryin'",
    "release_date": "2003-02-06",
    "genre": "Hip-Hop / Gangsta Rap",
    "tags": [
      "queens",
      "dr. dre",
      "blockbuster"
    ],
    "mood": "energetic",
    "curator_note": "Nine bullet wounds turned into a business plan, with 'In Da Club' making menace sound like a birthday party."
  },
  {
    "artist": "Madvillain",
    "title": "Madvillainy",
    "release_date": "2004-03-23",
    "genre": "Hip-Hop / Abstract",
    "tags": [
      "underground",
      "mf doom",
      "madlib"
    ],
    "mood": "hypnotic",
    "curator_note": "Madlib's dusty loops and DOOM's mask-muffled riddles collide in 22 tracks that end just as you lean in closer."
  },
  {
    "artist": "Dizzee Rascal",
    "title": "Boy in da Corner",
    "release_date": "2003-07-21",
    "genre": "Hip-Hop / Grime",
    "tags": [
      "uk",
      "grime",
      "mercury prize"
    ],
    "mood": "raw",
    "curator_note": "An 18-year-old from Bow builds grime's founding document out of PlayStation bleeps and the clenched anxiety of East London estates."
  },
  {
    "artist": "D'Angelo",
    "title": "Voodoo",
    "release_date": "2000-01-25",
    "genre": "R&B / Neo-Soul",
    "tags": [
      "neo-soul",
      "soulquarians",
      "groove"
    ],
    "mood": "hypnotic",
    "curator_note": "Questlove drags every drum hit a half-beat behind the pocket until the whole record moves like smoke through a Richmond church."
  },
  {
    "artist": "Erykah Badu",
    "title": "Mama's Gun",
    "release_date": "2000-11-21",
    "genre": "R&B / Neo-Soul",
    "tags": [
      "neo-soul",
      "electric lady",
      "confessional"
    ],
    "mood": "tender",
    "curator_note": "Recorded at Electric Lady with the Soulquarians, Badu unpacks heartbreak over live Fender Rhodes like she is thinking out loud in your kitchen."
  },
  {
    "artist": "Alicia Keys",
    "title": "Songs in A Minor",
    "release_date": "2001-06-05",
    "genre": "R&B / Soul",
    "tags": [
      "piano",
      "debut",
      "classical"
    ],
    "mood": "tender",
    "curator_note": "A 20-year-old classically trained pianist folds Chopin phrasing into Harlem soul and walks off with five Grammys."
  },
  {
    "artist": "Usher",
    "title": "Confessions",
    "release_date": "2004-03-23",
    "genre": "R&B / Pop",
    "tags": [
      "atlanta",
      "diamond-certified",
      "breakup"
    ],
    "mood": "melancholic",
    "curator_note": "A cheating scandal serialized like a soap opera, where even the guilt on 'Burn' arrives with an immaculate falsetto."
  },
  {
    "artist": "Aaliyah",
    "title": "Aaliyah",
    "release_date": "2001-07-07",
    "genre": "R&B / Alternative R&B",
    "tags": [
      "timbaland",
      "futuristic",
      "final album"
    ],
    "mood": "hypnotic",
    "curator_note": "Released weeks before her death, its whispered vocals over Timbaland's stuttering drums became the blueprint every alt-R&B singer has been tracing since."
  },
  {
    "artist": "Beyoncé",
    "title": "Dangerously in Love",
    "release_date": "2003-06-24",
    "genre": "R&B / Pop",
    "tags": [
      "solo debut",
      "crazy in love",
      "houston"
    ],
    "mood": "euphoric",
    "curator_note": "The Chi-Lites horn stab on 'Crazy in Love' announces a solo career the way a marching band announces halftime."
  },
  {
    "artist": "Amy Winehouse",
    "title": "Back to Black",
    "release_date": "2006-10-27",
    "genre": "Pop / Soul",
    "tags": [
      "uk",
      "retro-soul",
      "mark ronson"
    ],
    "mood": "melancholic",
    "curator_note": "Sixties girl-group arrangements played straight while Winehouse sings about rehab refusals in a voice that sounds already posthumous."
  },
  {
    "artist": "Justin Timberlake",
    "title": "FutureSex/LoveSounds",
    "release_date": "2006-09-12",
    "genre": "Pop / R&B",
    "tags": [
      "timbaland",
      "dance-pop",
      "suites"
    ],
    "mood": "energetic",
    "curator_note": "Timbaland stretches pop singles into seven-minute suites with beatbox interludes, and 'My Love' still sounds beamed in from a colder, better planet."
  },
  {
    "artist": "Kylie Minogue",
    "title": "Fever",
    "release_date": "2001-10-01",
    "genre": "Pop / Dance-Pop",
    "tags": [
      "australia",
      "disco",
      "club"
    ],
    "mood": "euphoric",
    "curator_note": "The la-la-la hook of 'Can't Get You Out of My Head' proved a robotic disco whisper could colonize every radio on earth."
  },
  {
    "artist": "Shakira",
    "title": "Fijación Oral, Vol. 1",
    "release_date": "2005-06-03",
    "genre": "Pop / Latin Pop",
    "tags": [
      "colombia",
      "spanish-language",
      "latin"
    ],
    "mood": "energetic",
    "curator_note": "Shakira bets a global career on a Spanish-language record and wins, with 'La Tortura' grinding accordion against reggaeton drums."
  },
  {
    "artist": "Lady Gaga",
    "title": "The Fame",
    "release_date": "2008-08-19",
    "genre": "Pop / Dance-Pop",
    "tags": [
      "electropop",
      "debut",
      "club"
    ],
    "mood": "euphoric",
    "curator_note": "A downtown New York performance artist smuggles Warhol theory into radio pop, and 'Just Dance' closes out the decade's last carefree party."
  },
  {
    "artist": "Daddy Yankee",
    "title": "Barrio Fino",
    "release_date": "2004-07-13",
    "genre": "Hip-Hop / Reggaeton",
    "tags": [
      "puerto rico",
      "reggaeton",
      "spanish-language"
    ],
    "mood": "energetic",
    "curator_note": "The dembow riddim of 'Gasolina' escaped San Juan and rewired global pop's rhythm section for the next twenty years."
  },
  {
    "artist": "Arcade Fire",
    "title": "Funeral",
    "release_date": "2004-09-14",
    "genre": "Indie Rock / Chamber Pop",
    "tags": [
      "indie rock",
      "canada",
      "2000s",
      "orchestral"
    ],
    "mood": "cinematic",
    "curator_note": "A Montreal collective turns a season of family deaths into neighborhood anthems, with strings and accordions swelling like a block party held in a blizzard."
  },
  {
    "artist": "The Strokes",
    "title": "Is This It",
    "release_date": "2001-07-30",
    "genre": "Indie Rock / Garage Rock Revival",
    "tags": [
      "garage rock",
      "new york",
      "revival"
    ],
    "mood": "energetic",
    "curator_note": "Eleven songs of leather-jacket cool recorded to sound like a great band heard through a payphone, and downtown New York spent a decade chasing the echo."
  },
  {
    "artist": "Interpol",
    "title": "Turn On the Bright Lights",
    "release_date": "2002-08-20",
    "genre": "Indie Rock / Post-Punk Revival",
    "tags": [
      "post-punk",
      "new york",
      "moody"
    ],
    "mood": "melancholic",
    "curator_note": "Suits, reverb, and Manhattan at 4 a.m.: Paul Banks intones cryptic heartbreak over basslines that prowl like taxis through empty streets."
  },
  {
    "artist": "Arctic Monkeys",
    "title": "Whatever People Say I Am, That's What I'm Not",
    "release_date": "2006-01-23",
    "genre": "Indie Rock / Post-Punk Revival",
    "tags": [
      "british",
      "debut",
      "sheffield"
    ],
    "mood": "energetic",
    "curator_note": "A teenage Alex Turner documents Sheffield taxi ranks, bouncers, and bad romances with the eye of a novelist and the tempo of a bar fight."
  },
  {
    "artist": "Animal Collective",
    "title": "Merriweather Post Pavilion",
    "release_date": "2009-01-06",
    "genre": "Indie Rock / Neo-Psychedelia",
    "tags": [
      "psychedelic",
      "experimental",
      "electronic"
    ],
    "mood": "euphoric",
    "curator_note": "Beach Boys harmonies dunked in a subwoofer, where songs about groceries and domestic love bloom into rave-sized choruses."
  },
  {
    "artist": "Sigur Rós",
    "title": "Takk...",
    "release_date": "2005-09-12",
    "genre": "Post-Rock / Ambient",
    "tags": [
      "iceland",
      "post-rock",
      "falsetto"
    ],
    "mood": "cinematic",
    "curator_note": "Bowed guitars and Jónsi's glacial falsetto build crescendos so widescreen that nature documentaries have been borrowing them ever since."
  },
  {
    "artist": "Radiohead",
    "title": "Kid A",
    "release_date": "2000-10-02",
    "genre": "Rock / Electronic",
    "tags": [
      "art rock",
      "experimental",
      "british"
    ],
    "mood": "ambient",
    "curator_note": "The biggest rock band alive shreds its own playbook, trading guitars for ondes Martenot and glitch until anxiety itself has a soundtrack."
  },
  {
    "artist": "Queens of the Stone Age",
    "title": "Songs for the Deaf",
    "release_date": "2002-08-27",
    "genre": "Rock / Stoner Rock",
    "tags": [
      "stoner rock",
      "desert",
      "grohl"
    ],
    "mood": "raw",
    "curator_note": "A desert drive from Los Angeles to Joshua Tree scored by robot-tight riffs, fake radio DJs, and Dave Grohl hitting drums like he owes them money."
  },
  {
    "artist": "The White Stripes",
    "title": "Elephant",
    "release_date": "2003-04-01",
    "genre": "Rock / Garage Rock",
    "tags": [
      "garage rock",
      "blues",
      "duo"
    ],
    "mood": "raw",
    "curator_note": "Recorded in two weeks on gear older than its makers, it opens with a bassline played on no bass and became a stadium chant anyway."
  },
  {
    "artist": "Wilco",
    "title": "Yankee Hotel Foxtrot",
    "release_date": "2002-04-23",
    "genre": "Rock / Alt-Country",
    "tags": [
      "alt-country",
      "americana",
      "experimental"
    ],
    "mood": "melancholic",
    "curator_note": "Rejected by its own label, this static-flecked heartland record turned shortwave-radio numbers and broken love songs into an American classic."
  },
  {
    "artist": "LCD Soundsystem",
    "title": "Sound of Silver",
    "release_date": "2007-03-12",
    "genre": "Electronic / Dance-Punk",
    "tags": [
      "dance-punk",
      "new york",
      "cowbell"
    ],
    "mood": "euphoric",
    "curator_note": "James Murphy makes middle age danceable, hiding a eulogy for friendship inside seven minutes of pulsing synths on 'All My Friends'."
  },
  {
    "artist": "Daft Punk",
    "title": "Discovery",
    "release_date": "2001-03-12",
    "genre": "Electronic / French House",
    "tags": [
      "french house",
      "disco",
      "robots"
    ],
    "mood": "euphoric",
    "curator_note": "Two Parisian robots melt 70s soft-rock and disco samples into filtered gold, complete with its own anime feature film."
  },
  {
    "artist": "Justice",
    "title": "Cross",
    "release_date": "2007-06-11",
    "genre": "Electronic / Electro House",
    "tags": [
      "french electro",
      "distortion",
      "dance"
    ],
    "mood": "energetic",
    "curator_note": "French house rebuilt with metal's compression and gospel choirs, so distorted the basslines seem to be tearing through the speaker cones on purpose."
  },
  {
    "artist": "The Knife",
    "title": "Silent Shout",
    "release_date": "2006-02-17",
    "genre": "Electronic / Electropop",
    "tags": [
      "sweden",
      "synthpop",
      "dark"
    ],
    "mood": "hypnotic",
    "curator_note": "A Swedish sibling duo pitch-shifts their voices into eerie strangers over icy steel-drum synths, making pop that feels overheard in a dream."
  },
  {
    "artist": "Burial",
    "title": "Untrue",
    "release_date": "2007-11-05",
    "genre": "Electronic / Dubstep",
    "tags": [
      "dubstep",
      "uk garage",
      "nocturnal"
    ],
    "mood": "melancholic",
    "curator_note": "Chopped R&B vocals ghost through rain-slicked 2-step beats, the sound of a night bus home from a rave that ended years ago."
  },
  {
    "artist": "Boards of Canada",
    "title": "Geogaddi",
    "release_date": "2002-02-18",
    "genre": "Electronic / IDM",
    "tags": [
      "idm",
      "scotland",
      "downtempo"
    ],
    "mood": "hypnotic",
    "curator_note": "Sun-bleached analog synths and half-heard children's voices, like an educational filmstrip from 1979 that keeps whispering something occult."
  },
  {
    "artist": "System of a Down",
    "title": "Toxicity",
    "release_date": "2001-09-04",
    "genre": "Metal / Alternative Metal",
    "tags": [
      "alt-metal",
      "armenian",
      "political"
    ],
    "mood": "energetic",
    "curator_note": "Armenian folk melodies collide with whiplash tempo changes and Serj Tankian's operatic yelp, hitting number one the very week of 9/11."
  },
  {
    "artist": "Mastodon",
    "title": "Leviathan",
    "release_date": "2004-08-31",
    "genre": "Metal / Sludge Metal",
    "tags": [
      "sludge",
      "progressive",
      "concept album"
    ],
    "mood": "raw",
    "curator_note": "A Moby-Dick concept album where Brann Dailor's drumming thrashes like the whale itself and every riff smells of salt and tar."
  },
  {
    "artist": "Tool",
    "title": "Lateralus",
    "release_date": "2001-05-15",
    "genre": "Metal / Progressive Metal",
    "tags": [
      "progressive",
      "polyrhythm",
      "psychedelic"
    ],
    "mood": "hypnotic",
    "curator_note": "The title track spirals through time signatures based on the Fibonacci sequence, turning math homework into an hour-plus ritual."
  },
  {
    "artist": "Opeth",
    "title": "Blackwater Park",
    "release_date": "2001-03-12",
    "genre": "Metal / Progressive Death Metal",
    "tags": [
      "sweden",
      "death metal",
      "acoustic"
    ],
    "mood": "cinematic",
    "curator_note": "Swedish death growls dissolve into fingerpicked folk passages and back again, ten-minute songs that move like weather fronts across a dark lake."
  },
  {
    "artist": "Kanye West",
    "title": "My Beautiful Dark Twisted Fantasy",
    "release_date": "2010-11-22",
    "genre": "Hip-Hop / Maximalist Rap",
    "tags": [
      "chicago",
      "orchestral",
      "ego",
      "decade-defining"
    ],
    "mood": "cinematic",
    "curator_note": "A gilded, guilt-ridden opera where King Crimson samples, Bon Iver falsettos, and a nine-minute toast to douchebags somehow cohere into rap's grandest self-portrait."
  },
  {
    "artist": "Kendrick Lamar",
    "title": "good kid, m.A.A.d city",
    "release_date": "2012-10-22",
    "genre": "Hip-Hop / West Coast",
    "tags": [
      "compton",
      "concept-album",
      "storytelling"
    ],
    "mood": "cinematic",
    "curator_note": "One night in Compton told through a borrowed minivan, a stolen prayer, and cassette-deck skits that turn a coming-of-age story into scripture."
  },
  {
    "artist": "Kendrick Lamar",
    "title": "To Pimp a Butterfly",
    "release_date": "2015-03-15",
    "genre": "Hip-Hop / Jazz-Rap",
    "tags": [
      "funk",
      "protest",
      "jazz",
      "grammy"
    ],
    "mood": "raw",
    "curator_note": "Thundercat's bass wriggles under confessions of survivor's guilt until 'Alright' erupts into the decade's defining protest chant."
  },
  {
    "artist": "Drake",
    "title": "Take Care",
    "release_date": "2011-11-15",
    "genre": "Hip-Hop / R&B",
    "tags": [
      "toronto",
      "moody",
      "40",
      "late-night"
    ],
    "mood": "melancholic",
    "curator_note": "Drake and producer 40 flood the club with fog and voicemail regret, inventing the 3 a.m. text as an album-length aesthetic."
  },
  {
    "artist": "Cardi B",
    "title": "Invasion of Privacy",
    "release_date": "2018-04-06",
    "genre": "Hip-Hop / Trap",
    "tags": [
      "bronx",
      "debut",
      "grammy"
    ],
    "mood": "energetic",
    "curator_note": "A Bronx ex-stripper turns bloody shoes and stolen paychecks into punchlines so precise the Grammys had no choice but to hand over Best Rap Album."
  },
  {
    "artist": "Tyler, The Creator",
    "title": "IGOR",
    "release_date": "2019-05-17",
    "genre": "Hip-Hop / Neo-Soul",
    "tags": [
      "heartbreak",
      "synths",
      "odd-future"
    ],
    "mood": "hypnotic",
    "curator_note": "Behind a blond wig and blown-out synth bass, Tyler charts a love triangle from thievery to acceptance without ever raising his pitched-down voice."
  },
  {
    "artist": "Bad Bunny",
    "title": "X 100pre",
    "release_date": "2018-12-24",
    "genre": "Hip-Hop / Latin Trap",
    "tags": [
      "puerto-rico",
      "reggaeton",
      "spanish-language"
    ],
    "mood": "melancholic",
    "curator_note": "Dropped on Nochebuena, it swerves from dembow heartbreak to a pop-punk detour in Spanish and made San Juan the new center of pop gravity."
  },
  {
    "artist": "Frank Ocean",
    "title": "channel ORANGE",
    "release_date": "2012-07-10",
    "genre": "R&B / Alternative R&B",
    "tags": [
      "storytelling",
      "soul",
      "debut"
    ],
    "mood": "tender",
    "curator_note": "Taxi meters, Cleopatra at the strip club, and unrequited summer love, all narrated with the calm of someone watching his own memories on TV."
  },
  {
    "artist": "Frank Ocean",
    "title": "Blonde",
    "release_date": "2016-08-20",
    "genre": "R&B / Avant-Soul",
    "tags": [
      "minimalist",
      "nostalgia",
      "independent"
    ],
    "mood": "ambient",
    "curator_note": "Drumless and dazed, it drifts through pitch-shifted voices and a mom's voicemail warning about weed, mourning a youth still in progress."
  },
  {
    "artist": "Beyoncé",
    "title": "Lemonade",
    "release_date": "2016-04-23",
    "genre": "R&B / Pop",
    "tags": [
      "visual-album",
      "betrayal",
      "southern-gothic"
    ],
    "mood": "raw",
    "curator_note": "Beyoncé swings a baseball bat through her own marriage on camera, then rebuilds it with brass bands, Jack White, and her grandmother's recipe for surviving."
  },
  {
    "artist": "SZA",
    "title": "Ctrl",
    "release_date": "2017-06-09",
    "genre": "R&B / Neo-Soul",
    "tags": [
      "tde",
      "confessional",
      "debut"
    ],
    "mood": "tender",
    "curator_note": "SZA admits to being 'the weekend' side-chick and stealing an ex's confidence with such conversational honesty that a generation adopted her diary as their own."
  },
  {
    "artist": "Solange",
    "title": "A Seat at the Table",
    "release_date": "2016-09-30",
    "genre": "R&B / Neo-Soul",
    "tags": [
      "black-identity",
      "interludes",
      "louisiana"
    ],
    "mood": "tender",
    "curator_note": "Master P's spoken interludes and feather-light harmonies frame weariness and Black pride as things you exhale slowly, not shout."
  },
  {
    "artist": "The Weeknd",
    "title": "House of Balloons",
    "release_date": "2011-03-21",
    "genre": "R&B / Alternative R&B",
    "tags": [
      "toronto",
      "mixtape",
      "dark"
    ],
    "mood": "hypnotic",
    "curator_note": "A free anonymous mixtape built on Siouxsie samples and after-party dread that made anhedonia the default temperature of 2010s R&B."
  },
  {
    "artist": "Rihanna",
    "title": "ANTI",
    "release_date": "2016-01-28",
    "genre": "R&B / Pop",
    "tags": [
      "barbados",
      "anti-pop",
      "dancehall"
    ],
    "mood": "raw",
    "curator_note": "Rihanna torches her singles-machine reputation for woozy dancehall, a Tame Impala cover, and 'Higher,' a whiskey-scorched voicemail of a love song."
  },
  {
    "artist": "Adele",
    "title": "21",
    "release_date": "2011-01-24",
    "genre": "Pop / Soul",
    "tags": [
      "heartbreak",
      "ballads",
      "diamond-selling"
    ],
    "mood": "melancholic",
    "curator_note": "A 21-year-old Londoner channels one breakup into 'Rolling in the Deep' and 'Someone Like You,' moving 30 million copies while the industry insisted albums were dead."
  },
  {
    "artist": "Taylor Swift",
    "title": "1989",
    "release_date": "2014-10-27",
    "genre": "Pop / Synth-Pop",
    "tags": [
      "reinvention",
      "80s",
      "max-martin"
    ],
    "mood": "euphoric",
    "curator_note": "Swift trades banjos for gated snares and polaroid nostalgia, turning tabloid scrutiny into 'Blank Space,' the smirking joke everyone missed at first."
  },
  {
    "artist": "Lorde",
    "title": "Melodrama",
    "release_date": "2017-06-16",
    "genre": "Pop / Electropop",
    "tags": [
      "new-zealand",
      "house-party",
      "jack-antonoff"
    ],
    "mood": "euphoric",
    "curator_note": "One house party stretched into a concept album, where the 'Green Light' piano stumbles on purpose and being 19 and alone feels enormous."
  },
  {
    "artist": "Robyn",
    "title": "Body Talk",
    "release_date": "2010-11-22",
    "genre": "Pop / Dance-Pop",
    "tags": [
      "sweden",
      "electro",
      "sad-banger"
    ],
    "mood": "melancholic",
    "curator_note": "The Swedish blueprint for crying mid-choreography: 'Dancing On My Own' watches an ex kiss someone else from the corner of the club and keeps the beat anyway."
  },
  {
    "artist": "Carly Rae Jepsen",
    "title": "Emotion",
    "release_date": "2015-06-24",
    "genre": "Pop / Synth-Pop",
    "tags": [
      "canada",
      "80s",
      "cult-classic"
    ],
    "mood": "euphoric",
    "curator_note": "Written after the 'Call Me Maybe' punchlines faded, it opens with a saxophone blast and spends 12 tracks treating a crush like a matter of life and death."
  },
  {
    "artist": "ROSALÍA",
    "title": "El Mal Querer",
    "release_date": "2018-11-02",
    "genre": "Pop / Flamenco Fusion",
    "tags": [
      "spain",
      "flamenco",
      "concept-album"
    ],
    "mood": "cinematic",
    "curator_note": "A Catalan conservatory thesis on a 13th-century novel, sung in flamenco melisma over motorcycle revs and handclaps chopped like trap hi-hats."
  },
  {
    "artist": "Radiohead",
    "title": "A Moon Shaped Pool",
    "release_date": "2016-05-08",
    "genre": "Art Rock / Electronic",
    "tags": [
      "art rock",
      "orchestral",
      "melancholy"
    ],
    "mood": "melancholic",
    "curator_note": "Jonny Greenwood's string arrangements and a choir turn decades-old live staples like 'True Love Waits' into a hushed, devastating breakup record."
  },
  {
    "artist": "Björk",
    "title": "Vulnicura",
    "release_date": "2015-01-20",
    "genre": "Art-Pop / Experimental",
    "tags": [
      "icelandic",
      "strings",
      "heartbreak"
    ],
    "mood": "raw",
    "curator_note": "Björk timestamps her separation song by song — nine months before, two months after — over Arca's fractured beats and grieving string swells."
  },
  {
    "artist": "Tame Impala",
    "title": "Currents",
    "release_date": "2015-07-17",
    "genre": "Indie / Psychedelic Pop",
    "tags": [
      "australian",
      "psych-pop",
      "synth"
    ],
    "mood": "hypnotic",
    "curator_note": "Kevin Parker trades fuzz pedals for gliding synth-bass, and 'Let It Happen' dissolves mid-song into a skipping-CD loop that somehow keeps grooving."
  },
  {
    "artist": "Arcade Fire",
    "title": "The Suburbs",
    "release_date": "2010-08-02",
    "genre": "Indie / Art Rock",
    "tags": [
      "canadian",
      "concept album",
      "nostalgia"
    ],
    "mood": "cinematic",
    "curator_note": "Cul-de-sacs, sprawl, and dashboard-lit teenage memory stretched across sixteen tracks that stunned everyone by winning Album of the Year at the Grammys."
  },
  {
    "artist": "Bon Iver",
    "title": "22, A Million",
    "release_date": "2016-09-30",
    "genre": "Indie / Experimental Folk",
    "tags": [
      "glitch-folk",
      "autotune",
      "wisconsin"
    ],
    "mood": "raw",
    "curator_note": "Justin Vernon feeds his falsetto through a homemade Messina rig, warping cabin folk into glitching, numerology-obsessed hymns."
  },
  {
    "artist": "Sufjan Stevens",
    "title": "Carrie & Lowell",
    "release_date": "2015-03-31",
    "genre": "Indie / Folk",
    "tags": [
      "grief",
      "acoustic",
      "confessional"
    ],
    "mood": "tender",
    "curator_note": "Whispered memories of an absent mother — swim lessons, video stores, a hospital deathbed — over fingerpicked figures barely louder than breath."
  },
  {
    "artist": "FKA twigs",
    "title": "LP1",
    "release_date": "2014-08-06",
    "genre": "Art-Pop / Alternative R&B",
    "tags": [
      "avant-r&b",
      "uk",
      "sensual"
    ],
    "mood": "hypnotic",
    "curator_note": "Twigs sings desire at a near-whisper while her producers stretch R&B until it creaks like a haunted music box."
  },
  {
    "artist": "James Blake",
    "title": "James Blake",
    "release_date": "2011-02-04",
    "genre": "Electronic / Post-Dubstep",
    "tags": [
      "post-dubstep",
      "minimal",
      "uk"
    ],
    "mood": "melancholic",
    "curator_note": "A dubstep producer strips the club away, leaving piano, a Feist cover chopped into stammering loops, and cavernous negative space."
  },
  {
    "artist": "Daft Punk",
    "title": "Random Access Memories",
    "release_date": "2013-05-17",
    "genre": "Electronic / Disco",
    "tags": [
      "french",
      "disco",
      "session musicians"
    ],
    "mood": "euphoric",
    "curator_note": "Two robots hire Nile Rodgers and a room of session legends to rebuild disco by hand, and 'Get Lucky' swallowed an entire summer."
  },
  {
    "artist": "Grimes",
    "title": "Visions",
    "release_date": "2012-01-31",
    "genre": "Art-Pop / Synth-Pop",
    "tags": [
      "canadian",
      "bedroom pop",
      "diy"
    ],
    "mood": "hypnotic",
    "curator_note": "Recorded in three sleepless weeks of self-imposed seclusion, its helium hooks float over goth-tinged synths on 'Oblivion' and 'Genesis'."
  },
  {
    "artist": "Beach House",
    "title": "Teen Dream",
    "release_date": "2010-01-26",
    "genre": "Indie / Dream Pop",
    "tags": [
      "dream pop",
      "baltimore",
      "organ"
    ],
    "mood": "tender",
    "curator_note": "Victoria Legrand's organ-swelled voice makes 'Zebra' and 'Silver Soul' feel like memories you are not sure you actually lived."
  },
  {
    "artist": "LCD Soundsystem",
    "title": "This Is Happening",
    "release_date": "2010-05-17",
    "genre": "Electronic / Dance-Punk",
    "tags": [
      "dance-punk",
      "new york",
      "farewell"
    ],
    "mood": "energetic",
    "curator_note": "James Murphy's intended farewell opens with 'Dance Yrself Clean' — three minutes of muttering before the synths detonate."
  },
  {
    "artist": "Vampire Weekend",
    "title": "Modern Vampires of the City",
    "release_date": "2013-05-14",
    "genre": "Indie / Art-Pop",
    "tags": [
      "baroque pop",
      "new york",
      "mortality"
    ],
    "mood": "melancholic",
    "curator_note": "Harpsichords, pitch-shifted choirs, and sudden mortality dread — the preppy kids grow up fast on 'Hannah Hunt' and 'Ya Hey'."
  },
  {
    "artist": "St. Vincent",
    "title": "St. Vincent",
    "release_date": "2014-02-24",
    "genre": "Art-Pop / Art Rock",
    "tags": [
      "angular guitar",
      "funk",
      "persona"
    ],
    "mood": "energetic",
    "curator_note": "Silver-haired on a pink throne, Annie Clark shreds fuzz guitar over drum machines and finds transcendence in taking out the garbage."
  },
  {
    "artist": "Jamie xx",
    "title": "In Colour",
    "release_date": "2015-05-29",
    "genre": "Electronic / UK Bass",
    "tags": [
      "uk bass",
      "rave",
      "steel drums"
    ],
    "mood": "euphoric",
    "curator_note": "Six years of rave archaeology distilled into steel drums, jungle breaks, and 'Loud Places' turning heartbreak into communal uplift."
  },
  {
    "artist": "Aphex Twin",
    "title": "Syro",
    "release_date": "2014-09-19",
    "genre": "Electronic / IDM",
    "tags": [
      "idm",
      "acid",
      "comeback"
    ],
    "mood": "energetic",
    "curator_note": "Richard D. James ends a thirteen-year silence with something unexpectedly generous: funk-limbed acid workouts hiding behind unpronounceable titles."
  },
  {
    "artist": "Oneohtrix Point Never",
    "title": "Replica",
    "release_date": "2011-11-08",
    "genre": "Experimental / Electronic",
    "tags": [
      "sample collage",
      "ambient",
      "hauntology"
    ],
    "mood": "ambient",
    "curator_note": "Built from looped television-advert detritus, its smeared pianos and chopped voices play like transmissions from a broadcast that never aired."
  },
  {
    "artist": "Flying Lotus",
    "title": "Cosmogramma",
    "release_date": "2010-05-03",
    "genre": "Experimental / Electronic",
    "tags": [
      "beat music",
      "jazz",
      "los angeles"
    ],
    "mood": "energetic",
    "curator_note": "Alice Coltrane's grand-nephew crams harp glissandos, Thundercat's bass, and a Thom Yorke cameo into a cosmic beat-music supernova."
  },
  {
    "artist": "Kendrick Lamar",
    "title": "Mr. Morale & the Big Steppers",
    "release_date": "2022-05-13",
    "genre": "Hip-Hop / Conscious Rap",
    "tags": [
      "west coast",
      "therapy rap",
      "double album"
    ],
    "mood": "raw",
    "curator_note": "Kendrick drags family therapy, tap-dance interludes, and generational trauma onto a double album that plays like a confession booth with a live band."
  },
  {
    "artist": "Kendrick Lamar",
    "title": "GNX",
    "release_date": "2024-11-22",
    "genre": "Hip-Hop / West Coast",
    "tags": [
      "west coast",
      "g-funk",
      "victory lap"
    ],
    "mood": "energetic",
    "curator_note": "A surprise-dropped victory lap where Mustard-bright synths and taut sub-three-minute cuts turn a beef-scorched year into a whole city's parade."
  },
  {
    "artist": "Tyler, The Creator",
    "title": "Call Me If You Get Lost",
    "release_date": "2021-06-25",
    "genre": "Hip-Hop / Alternative Rap",
    "tags": [
      "mixtape era",
      "travel",
      "dj drama"
    ],
    "mood": "cinematic",
    "curator_note": "Tyler reinvents himself as a globe-trotting Baudelaire over DJ Drama ad-libs, flexing passport stamps and heartbreak in the same breath."
  },
  {
    "artist": "Little Simz",
    "title": "Sometimes I Might Be Introvert",
    "release_date": "2021-09-03",
    "genre": "Hip-Hop / UK Rap",
    "tags": [
      "uk rap",
      "orchestral",
      "london"
    ],
    "mood": "cinematic",
    "curator_note": "Orchestral fanfares and grime-honed diction make Simz's introversion sound like a coronation staged in North London."
  },
  {
    "artist": "Doechii",
    "title": "Alligator Bites Never Heal",
    "release_date": "2024-08-30",
    "genre": "Hip-Hop / Southern Rap",
    "tags": [
      "florida",
      "mixtape",
      "grammy winner"
    ],
    "mood": "raw",
    "curator_note": "A swamp-bred Tampa mixtape where Doechii raps like she's fighting for her life and winning by technical knockout."
  },
  {
    "artist": "SZA",
    "title": "SOS",
    "release_date": "2022-12-09",
    "genre": "R&B / Alternative R&B",
    "tags": [
      "heartbreak",
      "alt r&b",
      "tde"
    ],
    "mood": "melancholic",
    "curator_note": "SZA turns romantic spite into 23 tracks of pop-punk detours, murder fantasies, and the decade's most quotable voicemails to an ex."
  },
  {
    "artist": "The Weeknd",
    "title": "After Hours",
    "release_date": "2020-03-20",
    "genre": "R&B / Synth-Pop",
    "tags": [
      "synthwave",
      "toronto",
      "blinding lights"
    ],
    "mood": "cinematic",
    "curator_note": "Vegas-red neon and dead-eyed falsetto turned pandemic-era loneliness into 'Blinding Lights,' Billboard's No. 1 Hot 100 song of all time."
  },
  {
    "artist": "Summer Walker",
    "title": "Still Over It",
    "release_date": "2021-11-05",
    "genre": "R&B / Contemporary R&B",
    "tags": [
      "breakup",
      "atlanta",
      "confessional"
    ],
    "mood": "melancholic",
    "curator_note": "Summer Walker airs out an ex over silk-sheet production and lets Ciara close the whole album with a literal spoken prayer."
  },
  {
    "artist": "Victoria Monét",
    "title": "Jaguar II",
    "release_date": "2023-08-25",
    "genre": "R&B / Funk",
    "tags": [
      "funk",
      "horns",
      "grammy winner"
    ],
    "mood": "euphoric",
    "curator_note": "A horn-stacked funk revue that sounds like Motown re-budgeted for 2023, right down to her baby daughter cooing on 'Hollywood'."
  },
  {
    "artist": "Taylor Swift",
    "title": "folklore",
    "release_date": "2020-07-24",
    "genre": "Pop / Indie Folk",
    "tags": [
      "lockdown",
      "storytelling",
      "indie folk"
    ],
    "mood": "tender",
    "curator_note": "Recorded in lockdown secrecy, Swift trades stadium fireworks for cardigan-gray character studies about a teenage love triangle."
  },
  {
    "artist": "Olivia Rodrigo",
    "title": "SOUR",
    "release_date": "2021-05-21",
    "genre": "Pop / Pop Rock",
    "tags": [
      "breakup",
      "pop punk",
      "debut"
    ],
    "mood": "raw",
    "curator_note": "A seventeen-year-old weaponizes her driver's license into pop-punk catharsis, screaming where lesser breakup albums would only sigh."
  },
  {
    "artist": "Dua Lipa",
    "title": "Future Nostalgia",
    "release_date": "2020-03-27",
    "genre": "Pop / Nu-Disco",
    "tags": [
      "disco",
      "dancefloor",
      "quarantine"
    ],
    "mood": "euphoric",
    "curator_note": "Released the week the world shut down, its mirrorball escapism gave a million empty kitchens their own private dancefloors."
  },
  {
    "artist": "Billie Eilish",
    "title": "HIT ME HARD AND SOFT",
    "release_date": "2024-05-17",
    "genre": "Pop / Alternative Pop",
    "tags": [
      "alt pop",
      "whisper vocals",
      "finneas"
    ],
    "mood": "hypnotic",
    "curator_note": "Billie murmurs 'Birds of a Feather' devotion one minute and detonates into club-siren basslines the next, often inside the same song."
  },
  {
    "artist": "Charli xcx",
    "title": "brat",
    "release_date": "2024-06-07",
    "genre": "Pop / Electropop",
    "tags": [
      "club",
      "hyperpop",
      "brat summer"
    ],
    "mood": "energetic",
    "curator_note": "A lime-green cover, clattering club beats, and diary-entry anxieties made Charli's party record the internet's entire summer of 2024."
  },
  {
    "artist": "Beyoncé",
    "title": "RENAISSANCE",
    "release_date": "2022-07-29",
    "genre": "Pop / Dance",
    "tags": [
      "house",
      "ballroom",
      "disco"
    ],
    "mood": "euphoric",
    "curator_note": "Beyoncé's mirrored-horse ride through Chicago house and ballroom culture, sequenced like one uninterrupted 4am DJ set."
  },
  {
    "artist": "Burna Boy",
    "title": "Twice as Tall",
    "release_date": "2020-08-14",
    "genre": "Afrobeats / Afro-Fusion",
    "tags": [
      "nigeria",
      "afro-fusion",
      "grammy winner"
    ],
    "mood": "energetic",
    "curator_note": "Burna stacks Fela-sized horns against a Naughty by Nature feature and dares the entire diaspora to keep pace."
  },
  {
    "artist": "Wizkid",
    "title": "Made in Lagos",
    "release_date": "2020-10-30",
    "genre": "Afrobeats / R&B",
    "tags": [
      "nigeria",
      "essence",
      "smooth"
    ],
    "mood": "tender",
    "curator_note": "Wizkid slows Lagos to a candlelit simmer, and 'Essence' with Tems became the song of two consecutive summers."
  },
  {
    "artist": "Asake",
    "title": "Mr. Money with the Vibe",
    "release_date": "2022-09-08",
    "genre": "Afrobeats / Amapiano",
    "tags": [
      "nigeria",
      "fuji",
      "log drums"
    ],
    "mood": "energetic",
    "curator_note": "Asake floods amapiano log drums with Fuji-style choirs until every track feels like a street carnival crashing a church service."
  },
  {
    "artist": "Tyla",
    "title": "TYLA",
    "release_date": "2024-03-22",
    "genre": "Amapiano / Pop",
    "tags": [
      "south africa",
      "popiano",
      "water"
    ],
    "mood": "hypnotic",
    "curator_note": "The Johannesburg singer bottles amapiano's log-drum bounce into 'Water' and glides past every prior pop-crossover attempt from the continent."
  },
  {
    "artist": "Kabza De Small",
    "title": "I Am the King of Amapiano: Sweet & Dust",
    "release_date": "2020-06-26",
    "genre": "Amapiano / House",
    "tags": [
      "south africa",
      "amapiano",
      "pretoria"
    ],
    "mood": "hypnotic",
    "curator_note": "Twenty-seven tracks of shakers, log drums, and gospel-touched keys — the Pretoria producer's mid-lockdown claim to the amapiano throne."
  },
  {
    "artist": "Fiona Apple",
    "title": "Fetch the Bolt Cutters",
    "release_date": "2020-04-17",
    "genre": "Alternative / Art Rock",
    "tags": [
      "art rock",
      "percussion",
      "home recording"
    ],
    "mood": "raw",
    "curator_note": "Recorded at home with barking dogs left in the mix, it turns Apple's Venice Beach living room into a full percussion section."
  },
  {
    "artist": "Phoebe Bridgers",
    "title": "Punisher",
    "release_date": "2020-06-18",
    "genre": "Indie / Folk-Rock",
    "tags": [
      "indie folk",
      "singer-songwriter",
      "los angeles"
    ],
    "mood": "melancholic",
    "curator_note": "Bridgers whispers apocalyptic jokes over funeral-parlor guitars until the closing track erupts into brass and screaming."
  },
  {
    "artist": "Tame Impala",
    "title": "The Slow Rush",
    "release_date": "2020-02-14",
    "genre": "Rock / Psychedelic Pop",
    "tags": [
      "psychedelic",
      "australia",
      "synth"
    ],
    "mood": "hypnotic",
    "curator_note": "Kevin Parker stretches disco basslines and phaser-soaked synths into a concept record about watching whole decades slip past."
  },
  {
    "artist": "Jessie Ware",
    "title": "What's Your Pleasure?",
    "release_date": "2020-06-26",
    "genre": "Dance / Disco",
    "tags": [
      "disco",
      "nu-disco",
      "strings"
    ],
    "mood": "hypnotic",
    "curator_note": "Ware trades kitchen-table soul for velvet-rope disco, all whispered come-ons floating over strings and slap bass."
  },
  {
    "artist": "Caribou",
    "title": "Suddenly",
    "release_date": "2020-02-28",
    "genre": "Electronic / House",
    "tags": [
      "electronic",
      "sampling",
      "canada"
    ],
    "mood": "tender",
    "curator_note": "Dan Snaith folds pitch-shifted soul samples and family grief into house tracks that swerve direction mid-bar."
  },
  {
    "artist": "Bicep",
    "title": "Isles",
    "release_date": "2021-01-22",
    "genre": "Electronic / Breakbeat",
    "tags": [
      "breakbeat",
      "rave",
      "belfast"
    ],
    "mood": "hypnotic",
    "curator_note": "Two Belfast producers distill decades of rave memory into glacial breakbeats built as much for headphones as warehouses."
  },
  {
    "artist": "Turnstile",
    "title": "Glow On",
    "release_date": "2021-08-27",
    "genre": "Rock / Hardcore",
    "tags": [
      "hardcore",
      "punk",
      "baltimore"
    ],
    "mood": "energetic",
    "curator_note": "Baltimore hardcore shot through with dream-pop shimmer and Blood Orange cameos, where mosh calls land beside synth washes."
  },
  {
    "artist": "Wet Leg",
    "title": "Wet Leg",
    "release_date": "2022-04-08",
    "genre": "Indie Rock / Post-Punk",
    "tags": [
      "post-punk",
      "debut",
      "deadpan"
    ],
    "mood": "energetic",
    "curator_note": "Two friends from the Isle of Wight deadpan about chaise longues and ex-boyfriends over riffs that snap like bubblegum."
  },
  {
    "artist": "Big Thief",
    "title": "Dragon New Warm Mountain I Believe in You",
    "release_date": "2022-02-11",
    "genre": "Indie Folk / Rock",
    "tags": [
      "indie folk",
      "double album",
      "americana"
    ],
    "mood": "tender",
    "curator_note": "A twenty-song sprawl cut in four different studios, swinging from trip-hop murk to fiddle tunes about potatoes without blinking."
  },
  {
    "artist": "Black Country, New Road",
    "title": "Ants From Up There",
    "release_date": "2022-02-04",
    "genre": "Indie / Chamber Rock",
    "tags": [
      "post-rock",
      "chamber",
      "uk"
    ],
    "mood": "melancholic",
    "curator_note": "Released four days after singer Isaac Wood left the band, its chamber-rock crescendos about Concorde jets read like a farewell letter."
  },
  {
    "artist": "The Smile",
    "title": "A Light for Attracting Attention",
    "release_date": "2022-05-13",
    "genre": "Rock / Art Rock",
    "tags": [
      "art rock",
      "radiohead",
      "jazz drums"
    ],
    "mood": "cinematic",
    "curator_note": "Thom Yorke and Jonny Greenwood loosen Radiohead's bolts and let Tom Skinner's jazz drumming swing beneath the paranoia."
  },
  {
    "artist": "Fred again..",
    "title": "Actual Life 3 (January 1 - September 9 2022)",
    "release_date": "2022-10-28",
    "genre": "Electronic / UK Dance",
    "tags": [
      "electronic",
      "sampling",
      "club"
    ],
    "mood": "melancholic",
    "curator_note": "Voice notes and FaceTime fragments from friends get chopped into piano house, making the club feel like a group hug at 4 a.m."
  },
  {
    "artist": "Alvvays",
    "title": "Blue Rev",
    "release_date": "2022-10-07",
    "genre": "Indie Rock / Shoegaze",
    "tags": [
      "shoegaze",
      "power pop",
      "canada"
    ],
    "mood": "energetic",
    "curator_note": "Molly Rankin buries razor-sharp hooks about exes and Bible school under a gleaming avalanche of fuzz pedals."
  },
  {
    "artist": "boygenius",
    "title": "the record",
    "release_date": "2023-03-31",
    "genre": "Indie Rock / Folk",
    "tags": [
      "supergroup",
      "harmonies",
      "indie rock"
    ],
    "mood": "tender",
    "curator_note": "Bridgers, Baker, and Dacus trade verses like letters between best friends, harmonizing on the word 'always' until it aches."
  },
  {
    "artist": "Sufjan Stevens",
    "title": "Javelin",
    "release_date": "2023-10-06",
    "genre": "Indie / Folk",
    "tags": [
      "indie folk",
      "orchestral",
      "grief"
    ],
    "mood": "melancholic",
    "curator_note": "Dedicated to his late partner, Stevens layers banjo, choirs, and soft electronics into grief that keeps opening upward toward light."
  },
  {
    "artist": "Fontaines D.C.",
    "title": "Romance",
    "release_date": "2024-08-23",
    "genre": "Rock / Post-Punk",
    "tags": [
      "post-punk",
      "ireland",
      "alt-rock"
    ],
    "mood": "cinematic",
    "curator_note": "Dublin's post-punk laureates swap grey overcoats for neon, chasing Korn-sized riffs and shoegaze haze while Grian Chatten croons about doomed love."
  },
  {
    "artist": "Jamie xx",
    "title": "In Waves",
    "release_date": "2024-09-20",
    "genre": "Electronic / Dance",
    "tags": [
      "dance",
      "uk",
      "club"
    ],
    "mood": "euphoric",
    "curator_note": "Nine years after In Colour, Jamie xx rounds up Robyn and his xx bandmates for steel-drum flickers and peak-time release."
  }
];

export const EXPANSION: Release[] = ENTRIES.map((e, i) => ({
  id: `exp-${String(i).padStart(3, "0")}`,
  artist: e.artist,
  title: e.title,
  type: "album",
  artwork_url: `/api/artwork?artist=${enc(e.artist)}&title=${enc(e.title)}`,
  release_date: e.release_date,
  genre: e.genre,
  tags: e.tags,
  mood: e.mood,
  ...links(e.artist, e.title),
  created_at: e.release_date + "T00:00:00Z",
  curator_note: e.curator_note,
}));
