/**
 * Grammy-winning artists (any category), 1967 → 2026.
 *
 * GENERATED FILE — do not edit by hand.
 * Regenerate with:  npm run grammy
 * Source: Wikidata (award received → Grammy Award and all category subclasses).
 *
 * 1336 winners.
 */

export const GRAMMY_ARTISTS: string[] = [
  "\"Weird Al\" Yankovic",
  "2Pac",
  "50 Cent",
  "A Taste of Honey",
  "A Tribe Called Quest",
  "A. R. Rahman",
  "Aaron Copland",
  "ABBA",
  "AC/DC",
  "Adele",
  "Aerosmith",
  "Agnes Baltsa",
  "Ahmad Jamal",
  "Ahmet Ertegün",
  "Al Bell",
  "Al Green",
  "Al Jarreau",
  "Al Schmitt",
  "Alabama Shakes",
  "Alan Bergman",
  "Alan Boyd",
  "Alan Broadbent",
  "Alan Freed",
  "Alan Jackson",
  "Alan Jay Lerner",
  "Alan Lomax",
  "Alan Menken",
  "Alan W. Livingston",
  "Alanis Morissette",
  "Alannah Myles",
  "Alejandro Sanz",
  "Alessia Cara",
  "Alex Cuba",
  "Alex Klein",
  "Alexandre Desplat",
  "Alfred Lion",
  "Ali Farka Touré",
  "Alice in Chains",
  "Alicia Keys",
  "Alison Brown",
  "Alison Krauss",
  "Allen Toussaint",
  "Allison Russell",
  "America",
  "Amy Allen",
  "Amy Winehouse",
  "Anari",
  "Anderson .Paak",
  "André Previn",
  "Andrés Segovia",
  "Andrew Lloyd Webber",
  "Andrew Solt",
  "Andy Griffith",
  "Andy Picheta",
  "Andy Wiswell",
  "Angelique Kidjo",
  "Angelo Badalamenti",
  "Angie Stone",
  "Ani DiFranco",
  "Anita Baker",
  "Anne Murray",
  "Anthony Hamilton",
  "Anthony Ramos",
  "Antônio Carlos Jobim",
  "Ants Soots",
  "Aoife O'Donovan",
  "Aphex Twin",
  "Arcade Fire",
  "Arcángel",
  "Aretha Franklin",
  "Ariana Grande",
  "Arif Mardin",
  "Armando Manzanero",
  "Arooj Aftab",
  "Arrested Development",
  "Art Blakey",
  "Art Rosenbaum",
  "Art Tatum",
  "Arthur Lewis Costa",
  "Arthur Rubinstein",
  "Artie Shaw",
  "Arturo Toscanini",
  "Asake",
  "Ashley McBryde",
  "Atticus Ross",
  "Audioslave",
  "Audrey Hepburn",
  "Aymée Nuviola",
  "Ayra Starr",
  "Baby Keem",
  "Babyface",
  "Bad Bunny",
  "Barack Obama",
  "Barbara Mandrell",
  "Barbra Streisand",
  "Baroness",
  "Beabadoobee",
  "Beastie Boys",
  "Bebo Valdés",
  "Beck",
  "Bee Gees",
  "Béla Bartók",
  "Ben Kingsley",
  "Ben Platt",
  "Benny Carter",
  "Benny Goodman",
  "Bernard Herrmann",
  "Berry Gordy",
  "Bessie Smith",
  "Bette Midler",
  "Betty White",
  "Betty Wright",
  "Beyoncé",
  "Big Sean",
  "Bilal",
  "Bill Clinton",
  "Bill Evans",
  "Bill Harley",
  "Bill Monroe",
  "Bill Putnam",
  "Bill Withers",
  "Billie Eilish",
  "Billie Holiday",
  "Billy Childs",
  "Billy Eckstine",
  "Billy Joel",
  "Billy Porter",
  "Billy Strayhorn",
  "Billy Strings",
  "Billy Taylor",
  "Björk",
  "Black Coffee",
  "Black Eyed Peas",
  "Black Pumas",
  "Blood, Sweat & Tears",
  "Blues Traveler",
  "Blur",
  "Bo Diddley",
  "Bob Dylan",
  "Bob James",
  "Bob Marley",
  "Bob Marley & The Wailers",
  "Bob Wills",
  "Bobbie Gentry",
  "Bobby Bland",
  "Bobby Darin",
  "Bobby McFerrin",
  "Bobby Rush",
  "Bon Iver",
  "Bon Jovi",
  "Bonnie Raitt",
  "Bono",
  "Bonobo",
  "Booker T. & the M.G.'s",
  "boygenius",
  "Boyz II Men",
  "Boz Scaggs",
  "Brad Mehldau",
  "Brad Paisley",
  "Bradley Cooper",
  "Brandi Carlile",
  "Brandy",
  "Brandy Clark",
  "Brandy Norwood",
  "Branford Marsalis",
  "Brenda Lee",
  "Brian Soko",
  "Brian Wilson",
  "Britney Spears",
  "Bronwyn Keith-Hynes",
  "Bruce Gowers",
  "Bruce Hornsby",
  "Bruce Hornsby and the Range",
  "Bruce Lundvall",
  "Bruce Springsteen",
  "Bruno Mars",
  "Bryan Adams",
  "Buddy Guy",
  "Buddy Holly",
  "Buena Vista Social Club",
  "Burna Boy",
  "Burning Spear",
  "Burt Bacharach",
  "Busta Rhymes",
  "Cab Calloway",
  "Cachao",
  "Café Tacvba",
  "Cage the Elephant",
  "Calle 13",
  "Calmatic",
  "Calvin Harris",
  "Camila Cabello",
  "Cannonball Adderley",
  "Cardi B",
  "Carín León",
  "Carlos Vives",
  "Carly Simon",
  "Carol Cymbala",
  "Carole King",
  "Carolina Chocolate Drops",
  "Caroline Shaw",
  "Carrie Underwood",
  "Carter Family",
  "Cassandra Wilson",
  "Casting Crowns",
  "CeCe Winans",
  "Cecil McBee",
  "Cécile McLorin Salvant",
  "Cecilia Bartoli",
  "Celia Cruz",
  "Celine Dion",
  "Céline Dion",
  "Cesária Évora",
  "Chad Hugo",
  "Chaka Khan",
  "Chance McCoy",
  "Chance the Rapper",
  "Chappell Roan",
  "Charles Dutoit",
  "Charles Flores",
  "Charles Mingus",
  "Charles Neville",
  "Charley Pride",
  "Charli XCX",
  "Charlie Haden",
  "Charlie Musselwhite",
  "Charlie Parker",
  "Charlie Rich",
  "Cher",
  "Chet Atkins",
  "Chicago",
  "Chick Corea",
  "Childish Gambino",
  "Chips Moman",
  "Chris Albertson",
  "Chris Blackwell",
  "Chris Brown",
  "Chris Stapleton",
  "Chris Thile",
  "Christian McBride",
  "Christina Aguilera",
  "Christine M. Farnon",
  "Christone Ingram",
  "Christopher Cerf",
  "Christopher Cross",
  "Christopher Reeve",
  "Christopher Rouse",
  "Christopher Tin",
  "Chucho Valdés",
  "Chuck Berry",
  "Clarence \"Gatemouth\" Brown",
  "Clark Terry",
  "Claudio Abbado",
  "Clean Bandit",
  "Clifton Chenier",
  "Clive Davis",
  "Coco Jones",
  "Colbie Caillat",
  "Coldplay",
  "Cole Porter",
  "Colin Davis",
  "Common",
  "Coolio",
  "Corinne Bailey Rae",
  "Cornell MacNeil",
  "Cosimo Matassa",
  "Count Basie",
  "Counting Crows",
  "Cream",
  "Cristin Milioti",
  "Cristina Pato",
  "Crosby, Stills & Nash",
  "Crystal Gayle",
  "Culture Club",
  "Curtis Mayfield",
  "Cy Coleman",
  "Cyndi Lauper",
  "Cynthia Erivo",
  "Cynthia Weil",
  "D'Angelo",
  "Daft Punk",
  "Dale Clevenger",
  "Danger Mouse",
  "Daniel Barenboim",
  "Daniel Caesar",
  "Daniel Lanois",
  "Danny Elfman",
  "Darlene Love",
  "Dashon Burton",
  "Dave Alvin",
  "Dave Bartholomew",
  "Dave Brubeck",
  "Dave Chappelle",
  "Dave Grohl",
  "Dave Grusin",
  "Dave Matthews Band",
  "Dave Pirner",
  "Dave Smith",
  "Daveed Diggs",
  "David Baker",
  "David Bowie",
  "David Edward Byrd",
  "David Edwards",
  "David Evans",
  "David Foster",
  "David Hein",
  "David Holt",
  "David Morales",
  "David Murray",
  "David Oistrakh",
  "David Russell",
  "David Sanborn",
  "David Zinman",
  "Davido",
  "Dawn Upshaw",
  "Dazz Band",
  "Deadmau5",
  "Dean Martin",
  "Death Cab for Cutie",
  "Debby Boone",
  "Deep Forest",
  "Def Leppard",
  "Delious Kennedy",
  "Destiny's Child",
  "Detail",
  "Devo",
  "Dexter Gordon",
  "Diana Krall",
  "Diana Ross",
  "Diane Curry",
  "Diane Schuur",
  "Dianne Reeves",
  "Dick Clark",
  "Diplo",
  "Dire Straits",
  "Disclosure",
  "Dixie Chicks",
  "Dizzy Gillespie",
  "DJ Jazzy Jeff & The Fresh Prince",
  "DJ Lamberto",
  "Doc Watson",
  "Doe",
  "Doechii",
  "Doja Cat",
  "Dolly Parton",
  "Don Cornelius",
  "Don Davis",
  "Donald Glover",
  "Donald McIntyre",
  "Donna Fargo",
  "Donna Summer",
  "Donny Hathaway",
  "Doris Day",
  "Dottie West",
  "Dr. Dre",
  "Dr. John",
  "Drake",
  "Dre Moon",
  "Dream Theater",
  "Dua Lipa",
  "Duane Eddy",
  "Dudley Moore",
  "Duffy",
  "Duke Ellington",
  "Duncan Sheik",
  "Dwan Hill",
  "Dweezil Zappa",
  "Eagles",
  "Earl Klugh",
  "Earl Scruggs",
  "Earth, Wind & Fire",
  "Eberhard Sengpiel",
  "Ed Sheeran",
  "Ed Thrasher",
  "Eddie Murphy",
  "Edgar Meyer",
  "Edwin Hawkins",
  "Eiko Ishioka",
  "Ejae",
  "Ekaterina Lekhina",
  "Eldridge R. Johnson",
  "Elizabeth Cotten",
  "Ella Fitzgerald",
  "Ella Jenkins",
  "Elliott Carter",
  "Elton John",
  "Elvis Crespo",
  "Elvis Presley",
  "Emile Berliner",
  "Eminem",
  "Emma Walton Hamilton",
  "Emmylou Harris",
  "En Vogue",
  "Ennio Morricone",
  "Enrico Caruso",
  "Enrique Iglesias",
  "Eric Clapton",
  "Erica Campbell",
  "Erykah Badu",
  "Esperanza Spalding",
  "Estelle Axton",
  "Etta James",
  "Evanescence",
  "Eve",
  "Evelyn Glennie",
  "Evgeny Kissin",
  "Ewan MacColl",
  "Faith Hill",
  "Fall Out Boy",
  "Fantastic Negrito",
  "Fatboy Slim",
  "Fats Domino",
  "Fats Waller",
  "Femi Kuti",
  "Fergie",
  "Finneas",
  "Finneas O'Connell",
  "Fiona Apple",
  "Fito Páez",
  "Fleetwood Mac",
  "Florence + The Machine",
  "Florence Greenberg",
  "Flowdan",
  "Flume",
  "Fontaines D.C.",
  "Foo Fighters",
  "For King & Country",
  "Foreigner",
  "Four Tops",
  "Fran Walsh",
  "Frances Preston",
  "Francesco Donadello",
  "Francis Lawrence",
  "Frank Foster",
  "Frank Ocean",
  "Frank Sinatra",
  "Frank Zappa",
  "Fraser T. Smith",
  "Fred Again",
  "Fred Astaire",
  "Fred Hammond",
  "Freddie Mercury",
  "Frederick Loewe",
  "Fuerza Regida",
  "Fugees",
  "Fun",
  "Gabriel Banat",
  "Gabriela Ortiz",
  "Gaby Moreno",
  "Galt MacDermot",
  "Garrison Keillor",
  "Garth Brooks",
  "Gary Burton",
  "Gary Clark Jr.",
  "Gene Autry",
  "Genesis",
  "Geoff Emerick",
  "Georg Solti",
  "George Avakian",
  "George Benson",
  "George Beverly Shea",
  "George Burns",
  "George Carlin",
  "George Clinton",
  "George Gershwin",
  "George Harrison",
  "George Holz",
  "George Jellinek",
  "George Jones",
  "George Martin",
  "George Massenburg",
  "George Michael",
  "George Strait",
  "George T. Simon",
  "Gerald Levert",
  "Gerome Ragni",
  "Gerry Goffin",
  "Gerry Mulligan",
  "Ghost",
  "Gil Evans",
  "Gil Scott-Heron",
  "Gilberto Gil",
  "Gilberto Santa Rosa",
  "Gilda Radner",
  "Giorgio Moroder",
  "Giveon",
  "Gladys Knight & the Pips",
  "Gladys Knight & The Pips",
  "Glen Campbell",
  "Glenn Gould",
  "Glenn Miller",
  "Gloria Estefan",
  "Gloria Gaither",
  "GloRilla",
  "Gnarls Barkley",
  "Goddard Lieberson",
  "Gojira",
  "Gordon Goodwin",
  "Gordon Jenkins",
  "Graham Nash",
  "Grandmaster Flash and the Furious Five",
  "Grateful Dead",
  "Green Day",
  "Greg Kurstin",
  "Greta Svabo Bech",
  "Greta Van Fleet",
  "Grover Washington Jr.",
  "Grupo Frontera",
  "Grupo Niche",
  "Guns N' Roses",
  "Guy Clark",
  "Guy-Manuel de Homem-Christo",
  "Gwen Stefani",
  "H.E.R.",
  "Hal David",
  "Halestorm",
  "Halsey",
  "Hank Jones",
  "Hank Williams",
  "Hank Williams Jr.",
  "Hans Zimmer",
  "Harold Arlen",
  "Harold Bradley",
  "Harold Faltermeyer",
  "Harry Belafonte",
  "Harry Everett Smith",
  "Harry Nilsson",
  "Hayley Williams",
  "Heart",
  "Heather Headley",
  "Helen Hayes",
  "Helen Reddy",
  "Henry Fonda",
  "Henry Mancini",
  "Henryk Szeryng",
  "Herb Alpert",
  "Herbie Hancock",
  "Hex Hector",
  "High on Fire",
  "Hildur Guðnadóttir",
  "Hillsong Worship",
  "Hiromi Uehara",
  "Hoagy Carmichael",
  "Hootie & the Blowfish",
  "Horacio Hernandez",
  "Howard Ashman",
  "Howard Shore",
  "Huey Lewis and the News",
  "Humberto Gatico",
  "Ian Cuttler",
  "Ibrahim Ferrer",
  "Ice Spice",
  "Ice-T",
  "Idles",
  "Igor Stravinsky",
  "Ike Turner",
  "Ike Turner, Jr.",
  "Ikutaro Kakehashi",
  "Ildar Abdrazakov",
  "Imagine Dragons",
  "Imanbek",
  "India.Arie",
  "Ira Gershwin",
  "Irakere",
  "Iron Maiden",
  "Irving Berlin",
  "Isaac Hayes",
  "Isaac Stern",
  "Isabelle Demers",
  "Isaiah \"Ikey\" Owens",
  "Itzhak Perlman",
  "J Balvin",
  "J. Cole",
  "J. Harrison Ghee",
  "J. Ivy",
  "Jac Holzman",
  "Jack Antonoff",
  "Jack Harlow",
  "Jack Nicholson",
  "Jack White",
  "Jackson Browne",
  "Jacob Collier",
  "James Brown",
  "James Fauntleroy II",
  "James Horner",
  "James Ingram",
  "James Mallinson",
  "James Newton Howard",
  "James Rado",
  "James Taylor",
  "Jamie Foxx",
  "Jan Hammer",
  "Janet Baker",
  "Janis Ian",
  "Janis Joplin",
  "János Starker",
  "Jascha Heifetz",
  "Jason Isbell",
  "Jason Mraz",
  "Jay Graydon",
  "Jay Rock",
  "Jay-Z",
  "Jazmine Sullivan",
  "Jeff Beck",
  "Jeff Scott",
  "Jelly Roll Morton",
  "Jennifer Hudson",
  "Jennifer Lopez",
  "Jerome Harmon",
  "Jerome Kern",
  "Jerry Duplessis",
  "Jerry Lee Lewis",
  "Jerry Moss",
  "Jerry Reed",
  "Jerry Wexler",
  "Jess Glynne",
  "Jessye Norman",
  "Jethro Tull",
  "Jewel",
  "Jill Scott",
  "Jim Croce",
  "Jim Lauderdale",
  "Jim Marshall",
  "Jimi Hendrix",
  "Jimmie Haskell",
  "Jimmy Bowen",
  "Jimmy Carter",
  "Jimmy Cliff",
  "Jimmy Iovine",
  "Jimmy Jam",
  "Joan Baez",
  "Joan Sebastian",
  "João Gilberto",
  "Joaquin Phoenix",
  "Jody Miller",
  "Jody Watley",
  "Joe Cocker",
  "Joe Jackson",
  "Joe Raposo",
  "Joe Simon",
  "Joe Williams",
  "Joel Dorn",
  "John Adams",
  "John Barry",
  "John Beasley",
  "John Berg",
  "John Boylan",
  "John Browning",
  "John Coltrane",
  "John Culshaw",
  "John Denver",
  "John Entwistle",
  "John Gielgud",
  "John Hammond",
  "John Jones",
  "John Kander",
  "John Lee Hooker",
  "John Legend",
  "John Lennon",
  "John M. Eargle",
  "John Mayer",
  "John Molo",
  "John Prine",
  "John Starling",
  "John Williams",
  "Johnny Cash",
  "Johnny Mathis",
  "Johnny Mercer",
  "Johnny Winter",
  "Jon Batiste",
  "Jon Secada",
  "Jonas Åkerlund",
  "Jonathan Winters",
  "Joni Mitchell",
  "Jordan Tupper",
  "José Feliciano",
  "Joshua Redman",
  "Journey",
  "Joyce DiDonato",
  "Juan Luis Guerra",
  "Juanes",
  "Judas Priest",
  "Judy Collins",
  "Judy Garland",
  "Julia Bullock",
  "Julie Andrews",
  "Julie Harris",
  "Julien Baker",
  "Julieta Venegas",
  "Julio Iglesias",
  "Justice",
  "Justin Timberlake",
  "k.d. lang",
  "Kacey Musgraves",
  "Kanye West",
  "Karol G",
  "Katy Perry",
  "Kayhan Kalhor",
  "Kaytranada",
  "Keb' Mo'",
  "Kehlani",
  "Keith Urban",
  "Kelly Clarkson",
  "Kelly Rowland",
  "Ken Burns",
  "Kendrick Lamar",
  "Kenny Chesney",
  "Kenny G",
  "Kenny Rogers",
  "Killer Mike",
  "Kim Petras",
  "King Curtis",
  "Kings of Leon",
  "Kip Lornell",
  "Kirk Franklin",
  "Kitty Wells",
  "Klaus Voormann",
  "Kool & The Gang",
  "Korn",
  "Kraftwerk",
  "Kris Kristofferson",
  "Kristen Anderson-Lopez",
  "Krzysztof Penderecki",
  "La Capella Reial de Catalunya",
  "La Mafia",
  "Lady A",
  "Lady Gaga",
  "Ladysmith Black Mambazo",
  "Lainey Wilson",
  "Lalah Hathaway",
  "Lalo Schifrin",
  "Lana Del Rey",
  "Larry Butler",
  "Larry Carlton",
  "Larry Hiller",
  "Larry Klein",
  "László Polgár",
  "Latto",
  "Laufey",
  "Laura Pausini",
  "Lauren Daigle",
  "Lauryn Hill",
  "LeAnn Rimes",
  "Lebo M.",
  "Lecrae",
  "Led Zeppelin",
  "Lee \"Scratch\" Perry",
  "Lee Ann Womack",
  "Lena Horne",
  "Leo Fender",
  "Leon Bridges",
  "Leonard Bernstein",
  "Leonard Chess",
  "Leonard Cohen",
  "Leonard Slatkin",
  "Leontyne Price",
  "Leopold Stokowski",
  "Les Paul",
  "LeVar Burton",
  "Lightnin' Hopkins",
  "Lil Nas X",
  "Lil Wayne",
  "Lily Tomlin",
  "Liminha",
  "Lin-Manuel Miranda",
  "Linda Davis",
  "Linda Ronstadt",
  "Linkin Park",
  "Lionel Richie",
  "Little Big Town",
  "Little Richard",
  "Liza Minnelli",
  "Lizzo",
  "LL Cool J",
  "Logic",
  "Lola Young",
  "Lorde",
  "Lorenz Hart",
  "Loretta Lynn",
  "Lorin Maazel",
  "Los Lobos",
  "Lou Reed",
  "Louis Armstrong",
  "Louis Jordan",
  "Lucas Richman",
  "Lucinda Williams",
  "Lucky Daye",
  "Lucky Oceans",
  "Lucy Dacus",
  "Ludacris",
  "Ludwig Göransson",
  "Luis Enrique",
  "Luis Miguel",
  "Luke Combs",
  "Luther Vandross",
  "Lyle Lovett",
  "Lzzy Hale",
  "Machito",
  "Macklemore",
  "Macklemore & Ryan Lewis",
  "Madonna",
  "Maggie Rogers",
  "Magic Johnson",
  "Magicenelbeat",
  "Magnus Lindgren",
  "Mahalia Jackson",
  "Major Lazer",
  "Malcolm-Jamal Warner",
  "Mamadou Diabaté",
  "Maná",
  "Måneskin",
  "Manhattan Transfer",
  "Marc Anthony",
  "Marc Cohn",
  "Maren Morris",
  "Maria Meneghini Callas",
  "Maria Schneider",
  "Mariachi los Camperos",
  "Mariah Carey",
  "Marian Anderson",
  "Marian McPartland",
  "Marilyn Bergman",
  "Marina Domashenko",
  "Marina Viotti",
  "Mario McNulty",
  "Mark Knopfler",
  "Mark Linett",
  "Mark Phythian",
  "Mark Ronson",
  "Mark Willsher",
  "Markus Illko",
  "Maroon 5",
  "Martha Argerich",
  "Martin Scorsese",
  "Marty Robbins",
  "Marvin Gaye",
  "Marvin Hamlisch",
  "Marvin Sapp",
  "Mary Chapin Carpenter",
  "Mary J. Blige",
  "Mary Youngblood",
  "Masanori Takumi",
  "Mason Bates",
  "Massive Attack",
  "Mastodon",
  "Mat Leffler-Schulman",
  "Mathew Cullen",
  "Matti Salminen",
  "Maud Powell",
  "Maurice White",
  "Max Martin",
  "Max Roach",
  "Maxim Vengerov",
  "Maxwell",
  "Maya Angelou",
  "MC Hammer",
  "Meat Loaf",
  "Megan Thee Stallion",
  "Meghan Trainor",
  "Mel Brooks",
  "Mel Tormé",
  "Melissa Etheridge",
  "Men at Work",
  "MercyMe",
  "Merle Haggard",
  "Merle Travis",
  "Meshell Ndegeocello",
  "Metallica",
  "Method Man",
  "MGMT",
  "Michael Apted",
  "Michael Bolton",
  "Michael Bublé",
  "Michael Giacchino",
  "Michael J. Fox",
  "Michael Jackson",
  "Michael Lang",
  "Michael League",
  "Michael McKean",
  "Michael Nesmith",
  "Michael Suk-Young Chwe",
  "Michelle Obama",
  "Mickey Hart",
  "Miguel Zenón",
  "Mike Oldfield",
  "Mike Post",
  "Mikhail Gorbachev",
  "Miles Davis",
  "Miley Cyrus",
  "Milli Vanilli",
  "Milt Gabler",
  "Mimy Succar",
  "Miranda Lambert",
  "Mirella Freni",
  "Miri Ben-Ari",
  "Missy Elliott",
  "Mitch Miller",
  "Mitsuko Uchida",
  "Moby",
  "Molly Tuttle",
  "Monica",
  "Morgan Wallen",
  "Morton Gould",
  "Mos Def",
  "Muddy Waters",
  "Mumford & Sons",
  "Muni Long",
  "Mura Masa",
  "Muse",
  "Nan Schwartz",
  "Nanci Griffith",
  "Nancy Wilson",
  "Napoleon Murphy Brock",
  "Nas",
  "Nashville Bluegrass Band",
  "Nasuhi Ertegün",
  "Nat King Cole",
  "Natalia Lafourcade",
  "Natalie Cole",
  "Natalie MacMaster",
  "Natanael Cano",
  "Naughty by Nature",
  "Ne-Yo",
  "Neil Aspinall",
  "Neil Diamond",
  "Neil Young",
  "Nelly",
  "New Kids on the Block",
  "Nicki Minaj",
  "Nicolai Gedda",
  "Nikolaus Harnoncourt",
  "Nine Inch Nails",
  "Nino Rota",
  "Nirvana",
  "No Doubt",
  "No I.D.",
  "Nora Guthrie",
  "Norah Jones",
  "Norman Granz",
  "Norman Newell",
  "Oasis",
  "Odesza",
  "Old Crow Medicine Show",
  "Olivia Dean",
  "Olivia Harrison",
  "Olivia Newton-John",
  "Olivia Rodrigo",
  "OneRepublic",
  "Ornette Coleman",
  "Orrin Keepnews",
  "Óscar Gómez",
  "Oscar Hammerstein II",
  "Oscar Peterson",
  "Osmo Vänskä",
  "Ossie Davis",
  "Osvaldo Golijov",
  "Otis Redding",
  "Otis Rush",
  "Otto Gerdes",
  "OutKast",
  "Owen Bradley",
  "Ozzy Osbourne",
  "Panic! At The Disco",
  "Paramore",
  "Parliament-Funkadelic",
  "Pat Benatar",
  "Pat Metheny",
  "Patrick Stewart",
  "Patsy Cline",
  "Patti LaBelle",
  "Patti LuPone",
  "Patti Page",
  "Patton Oswalt",
  "Patty Griffin",
  "Pau Casals",
  "Paul Buckmaster",
  "Paul Epworth",
  "Paul Jacobs",
  "Paul McCartney",
  "Paul Robeson",
  "Paul Simon",
  "Paul Weston",
  "Paul Williams",
  "Paula Cole",
  "Paweł Pańta",
  "Pearl Jam",
  "Peggy Lee",
  "Pentatonix",
  "Perry Como",
  "Peso Pluma",
  "Pete Seeger",
  "Peter Bogdanovich",
  "Peter Frampton",
  "Peter Gabriel",
  "Petra Lang",
  "Pharrell Williams",
  "Phil Chess",
  "Phil Collins",
  "Phil Ramone",
  "Phil Spector",
  "Phoebe Bridgers",
  "Phoenix",
  "Pierre Boulez",
  "Pierre Cossette",
  "Pinetop Perkins",
  "Pink",
  "Pink Floyd",
  "Portishead",
  "Post Malone",
  "Prince",
  "Public Enemy",
  "Puff Daddy",
  "Queen",
  "Queen Latifah",
  "Quincy Jones",
  "R. Kelly",
  "R.E.M.",
  "Radiohead",
  "Rage Against the Machine",
  "Rahki",
  "Ramones",
  "Randy Travis",
  "Raphael Saadiq",
  "Rascal Flatts",
  "Rasool Diaz",
  "Rauw Alejandro",
  "Ravi Shankar",
  "Ray Barretto",
  "Ray Charles",
  "Ray Dolby",
  "Ray LaMontagne",
  "Ray Parker Jr.",
  "Reba McEntire",
  "Red Hot Chili Peppers",
  "Reggie Lucas",
  "René Pape",
  "Renée Elise Goldsberry",
  "Return to Forever",
  "Ricardo Arjona",
  "Riccardo Muti",
  "Richard Burton",
  "Richard Freed",
  "Richard Harris",
  "Richard Pryor",
  "Richard Rodgers",
  "Rick Hall",
  "Rick James",
  "Rickie Lee Jones",
  "Ricky Martin",
  "Ricky Skaggs",
  "Rihanna",
  "Rikki Hughes",
  "Rita Moreno",
  "Rob McConnell",
  "Rob Thomas",
  "Rob Zombie",
  "Robert Glasper",
  "Robert Glasper Experiment",
  "Robert Guillaume",
  "Robert Johnson",
  "Robert Lockwood Jr.",
  "Robert Lopez",
  "Robert Moog",
  "Robert Plant",
  "Robert Shakespeare",
  "Roberta Flack",
  "Roberto Blades",
  "Roberto Carlos",
  "Robin Gibb",
  "Robin Williams",
  "Rod Stewart",
  "Roger Linn",
  "Roger Miller",
  "Roger Nichols",
  "Roger Norrington",
  "Ronnie Milsap",
  "Rosalía",
  "Rosanne Cash",
  "Rosemary Clooney",
  "Roy Acuff",
  "Roy Hargrove",
  "Roy Haynes",
  "Roy Orbison",
  "Rubén Blades",
  "Rudy Van Gelder",
  "Run the Jewels",
  "Run-DMC",
  "Rupert Neve",
  "Rush",
  "Russell Elevado",
  "Ry Cooder",
  "Ryan Lewis",
  "Sabrina Carpenter",
  "Sadaharu Yagi",
  "Sade",
  "Sade Adu",
  "Salt-N-Pepa",
  "Sam Cooke",
  "Sam Phillips",
  "Sam Smith",
  "Samara Joy",
  "Sammy Davis Jr.",
  "Sandeep Das",
  "Santana",
  "Sarah McLachlan",
  "Sarah Vaughan",
  "Seal",
  "Sean Combs",
  "Sean Paul",
  "Sebastian Cabot",
  "Seiji Ozawa",
  "Selena",
  "Selena Gomez",
  "Sérgio Mendes",
  "Serj Tankian",
  "Seun Kuti",
  "Shaboozey",
  "Shakira",
  "Shania Twain",
  "Shaun Martin",
  "Shawn Colvin",
  "Sheena Easton",
  "Shelby Lynne",
  "Sheryl Crow",
  "Sia",
  "Sidney Poitier",
  "Sierra Ferrell",
  "Silk Sonic",
  "Simon & Garfunkel",
  "Simon Rattle",
  "Sinéad O'Connor",
  "Sirah",
  "Skrillex",
  "Slipknot",
  "Sly Stone",
  "Smashing Pumpkins",
  "Smokey Robinson",
  "Snarky Puppy",
  "Snoop Dogg",
  "Sonny Rollins",
  "Sophie Muller",
  "Soul II Soul",
  "Soundgarden",
  "Soweto Gospel Choir",
  "Spin Doctors",
  "Spyro Gyra",
  "St. Vincent",
  "Stacey Mindich",
  "Stan Getz",
  "Starland Vocal Band",
  "Steely Dan",
  "Stéphane Grappelli",
  "Stephen Albert",
  "Stephen Colbert",
  "Stephen Hartke",
  "Stephen Holden",
  "Stephen Schwartz",
  "Stephen Sondheim",
  "Steve Earle",
  "Steve Fishell",
  "Steve Goodman",
  "Steve Jobs",
  "Steve Stevens",
  "Steve Vai",
  "Steven Gizicki",
  "Steven Paul",
  "Steven Spielberg",
  "Stevie Ray Vaughan",
  "Stevie Wonder",
  "Sting",
  "Stone Temple Pilots",
  "Stromae",
  "Stuart Benjamin",
  "Sturgill Simpson",
  "Sue Gilad",
  "Sufjan Stevens",
  "Sugarland",
  "Supriyo Bandyopadhyay",
  "Suzanne Vega",
  "Sviatoslav Richter",
  "System of a Down",
  "SZA",
  "T Bone Burnett",
  "T.I.",
  "Tak Matsumoto",
  "Take 6",
  "Talib Kweli",
  "Talking Heads",
  "Tame Impala",
  "Tammy Wynette",
  "Tanya Tucker",
  "Tasha Cobbs Leonard",
  "Taylor Swift",
  "Taylor York",
  "Tedeschi Trucks Band",
  "Tems",
  "Tenacious D",
  "Terence Blanchard",
  "Teresa Stratas",
  "Terrance Simien",
  "Terri Lyne Carrington",
  "Terry Lewis",
  "The 1975",
  "The 5th Dimension",
  "The Allman Brothers Band",
  "The Band",
  "The Band Perry",
  "The Beach Boys",
  "The Beatles",
  "The Black Keys",
  "The Blind Boys of Alabama",
  "The Carpenters",
  "The Cars",
  "The Chemical Brothers",
  "The Doors",
  "The Earls of Leicester",
  "The Fray",
  "The Funk Brothers",
  "The Isley Brothers",
  "The Judds",
  "The Kingston Trio",
  "The Klezmatics",
  "The Memphis Horns",
  "The Mills Brothers",
  "The National",
  "The Notorious B.I.G.",
  "The O'Jays",
  "The Offspring",
  "The Pointer Sisters",
  "The Police",
  "The Prodigy",
  "The Rolling Stones",
  "The Roots",
  "The Staple Singers",
  "The Temptations",
  "The Weavers",
  "The Weeknd",
  "The White Stripes",
  "The Who",
  "The-Dream",
  "Thelonious Monk",
  "They Might Be Giants",
  "Thom Bell",
  "Thomas A. Dorsey",
  "Thomas Adès",
  "Thomas Edison",
  "Thomas Newman",
  "Thomas Stockham",
  "Thundercat",
  "Tia Carrere",
  "Tim Rice",
  "Tina Turner",
  "Tinariwen",
  "Tito Puente",
  "TLC",
  "Tobias Forge",
  "TobyMac",
  "Todd McFarlane",
  "Tom Dowd",
  "Tom MacDougall",
  "Tom Paxton",
  "Tom Petty",
  "Tom Wasinger",
  "Toni Braxton",
  "Tony Bennett",
  "Tony Kaye",
  "Tony Succar",
  "Tool",
  "Toto",
  "Tracy Chapman",
  "Train",
  "Travis Scott",
  "Trent Reznor",
  "Tricky Stewart",
  "Trisha Yearwood",
  "Turnstile",
  "Twenty One Pilots",
  "Tyla",
  "Tylana Renga Enomoto",
  "Tyler, The Creator",
  "U2",
  "Underworld",
  "Usher",
  "Valerie Faris",
  "Vampire Weekend",
  "Van Cliburn",
  "Van Halen",
  "Van McCoy",
  "Van Morrison",
  "Vicente Fernández",
  "Victoria Monét",
  "Vince Gill",
  "Vince Guaraldi",
  "Vince Staples",
  "Viola Davis",
  "Vladimir Horowitz",
  "W. C. Handy",
  "Walt Disney",
  "Walter Afanasieff",
  "Walter C. Miller",
  "Walter Mosley",
  "Waylon Jennings",
  "Weather Report",
  "Wendy Carlos",
  "Wes Montgomery",
  "Wet Leg",
  "Whitney Houston",
  "Whoopi Goldberg",
  "Wilco",
  "Will Smith",
  "will.i.am",
  "William Primrose",
  "Willie Mitchell",
  "Willie Nelson",
  "Wilma Cozart Fine",
  "Wisin & Yandel",
  "Wizkid",
  "Wolf-Dieter Karwatky",
  "Woody Guthrie",
  "Woody Herman",
  "Wu-Tang Clan",
  "Wynton Marsalis",
  "Yefim Bronfman",
  "Yellowjackets",
  "Yoko Ono",
  "Yolanda Adams",
  "Youssou N'Dour",
  "Youssou N’Dour",
  "Yungblud",
  "Yury Bashmet",
  "Zac Brown Band",
  "Zach Braff",
  "Zach Bryan",
  "Zakir Hussain",
  "Zedd",
  "Ziggy Marley",
];

export const GRAMMY_ARTISTS_UNIQUE: string[] = [
  ...new Set(GRAMMY_ARTISTS.map((n) => n.trim()).filter(Boolean)),
];
